#![allow(nonstandard_style)]

//  ______                        _               _  _  _
//  |  _  \                      | |             | |(_)| |
//  | | | |  ___    _ __    ___  | |_    ___   __| | _ | |_
//  | | | | / _ \  | '_ \  / _ \ | __|  / _ \ / _` || || __|
//  | |/ / | (_) | | | | || (_) || |_  |  __/| (_| || || |_
//  |___/   \___/  |_| |_| \___/  \__|  \___| \__,_||_| \__|
//
// Generated by skir-rust-gen
// Home: https://github.com/gepheum/skir-rust-gen
//
// To install the Skir client library, run:
//   cargo add skir-client

// ==============================================================================
// struct WatchUserOrganizationsRequest
// ==============================================================================

#[derive(Clone, Debug, PartialEq, Default)]
pub struct WatchUserOrganizationsRequest {
    /// Set this to None when you're creating a struct.
    pub _unrecognized: Option<crate::skir_client::UnrecognizedFields<WatchUserOrganizationsRequest>>,
}

impl WatchUserOrganizationsRequest {
    pub fn default_ref() -> &'static WatchUserOrganizationsRequest {
        static D: std::sync::LazyLock<WatchUserOrganizationsRequest> = std::sync::LazyLock::new(WatchUserOrganizationsRequest::default);
        &D
    }
}

impl WatchUserOrganizationsRequest {
    fn _adapter() -> &'static crate::skir_client::internal::StructAdapter<WatchUserOrganizationsRequest> {
        static ADAPTER: std::sync::LazyLock<crate::skir_client::internal::StructAdapter<WatchUserOrganizationsRequest>> =
            std::sync::LazyLock::new(|| {
                crate::skir_client::internal::StructAdapter::new(
                    "organization/v1/user.skir",
                    "WatchUserOrganizationsRequest",
                    "",
                    |x: &WatchUserOrganizationsRequest| &x._unrecognized,
                    |x: &mut WatchUserOrganizationsRequest, u| x._unrecognized = u,
                )
            });
        &*ADAPTER
    }
    pub fn serializer() -> crate::skir_client::Serializer<WatchUserOrganizationsRequest> {
        initialize_module_serializers();
        crate::skir_client::internal::struct_serializer_from_static(WatchUserOrganizationsRequest::_adapter())
    }
}

// ==============================================================================
// struct WatchUserOrganizationsResponse.InternalError
// ==============================================================================

#[derive(Clone, Debug, PartialEq, Default)]
pub struct WatchUserOrganizationsResponse_InternalError {
    /// Set this to None when you're creating a struct.
    pub _unrecognized: Option<crate::skir_client::UnrecognizedFields<WatchUserOrganizationsResponse_InternalError>>,
}

impl WatchUserOrganizationsResponse_InternalError {
    pub fn default_ref() -> &'static WatchUserOrganizationsResponse_InternalError {
        static D: std::sync::LazyLock<WatchUserOrganizationsResponse_InternalError> = std::sync::LazyLock::new(WatchUserOrganizationsResponse_InternalError::default);
        &D
    }
}

impl WatchUserOrganizationsResponse_InternalError {
    fn _adapter() -> &'static crate::skir_client::internal::StructAdapter<WatchUserOrganizationsResponse_InternalError> {
        static ADAPTER: std::sync::LazyLock<crate::skir_client::internal::StructAdapter<WatchUserOrganizationsResponse_InternalError>> =
            std::sync::LazyLock::new(|| {
                crate::skir_client::internal::StructAdapter::new(
                    "organization/v1/user.skir",
                    "WatchUserOrganizationsResponse.InternalError",
                    "",
                    |x: &WatchUserOrganizationsResponse_InternalError| &x._unrecognized,
                    |x: &mut WatchUserOrganizationsResponse_InternalError, u| x._unrecognized = u,
                )
            });
        &*ADAPTER
    }
    pub fn serializer() -> crate::skir_client::Serializer<WatchUserOrganizationsResponse_InternalError> {
        initialize_module_serializers();
        crate::skir_client::internal::struct_serializer_from_static(WatchUserOrganizationsResponse_InternalError::_adapter())
    }
}

// ==============================================================================
// enum WatchUserOrganizationsResponse
// ==============================================================================

#[derive(Debug, Clone, PartialEq)]
pub enum WatchUserOrganizationsResponse {
    Unknown(Option<crate::skir_client::UnrecognizedVariant<WatchUserOrganizationsResponse>>),
    List(Vec<crate::skirout::base::organization::v1::organization::Organization>),
    Add(Box<crate::skirout::base::organization::v1::organization::Organization>),
    Remove(Box<crate::skirout::base::kernel::v1::record_id::RecordId>),
    InternalError(Box<WatchUserOrganizationsResponse_InternalError>),
}

impl Default for WatchUserOrganizationsResponse {
    fn default() -> Self {
        WatchUserOrganizationsResponse::Unknown(None)
    }
}

impl WatchUserOrganizationsResponse {
    fn _adapter() -> &'static crate::skir_client::internal::EnumAdapter<WatchUserOrganizationsResponse> {
        static ADAPTER: std::sync::LazyLock<crate::skir_client::internal::EnumAdapter<WatchUserOrganizationsResponse>> =
            std::sync::LazyLock::new(|| {
                crate::skir_client::internal::EnumAdapter::new(
                    |x: &WatchUserOrganizationsResponse| match x {
                        WatchUserOrganizationsResponse::Unknown(_) => 0,
                        WatchUserOrganizationsResponse::List(_) => 1,
                        WatchUserOrganizationsResponse::Add(_) => 2,
                        WatchUserOrganizationsResponse::Remove(_) => 3,
                        WatchUserOrganizationsResponse::InternalError(_) => 4,
                    },
                    |u| WatchUserOrganizationsResponse::Unknown(Some(u)),
                    |x: &WatchUserOrganizationsResponse| match x { WatchUserOrganizationsResponse::Unknown(Some(u)) => Some(u.as_ref()), _ => None },
                    "organization/v1/user.skir",
                    "WatchUserOrganizationsResponse",
                    "",
                )
            });
        &*ADAPTER
    }
    pub fn serializer() -> crate::skir_client::Serializer<WatchUserOrganizationsResponse> {
        initialize_module_serializers();
        crate::skir_client::internal::enum_serializer_from_static(WatchUserOrganizationsResponse::_adapter())
    }
}

// ==============================================================================
// struct WatchUserJoinRequestsRequest
// ==============================================================================

#[derive(Clone, Debug, PartialEq, Default)]
pub struct WatchUserJoinRequestsRequest {
    /// Set this to None when you're creating a struct.
    pub _unrecognized: Option<crate::skir_client::UnrecognizedFields<WatchUserJoinRequestsRequest>>,
}

impl WatchUserJoinRequestsRequest {
    pub fn default_ref() -> &'static WatchUserJoinRequestsRequest {
        static D: std::sync::LazyLock<WatchUserJoinRequestsRequest> = std::sync::LazyLock::new(WatchUserJoinRequestsRequest::default);
        &D
    }
}

impl WatchUserJoinRequestsRequest {
    fn _adapter() -> &'static crate::skir_client::internal::StructAdapter<WatchUserJoinRequestsRequest> {
        static ADAPTER: std::sync::LazyLock<crate::skir_client::internal::StructAdapter<WatchUserJoinRequestsRequest>> =
            std::sync::LazyLock::new(|| {
                crate::skir_client::internal::StructAdapter::new(
                    "organization/v1/user.skir",
                    "WatchUserJoinRequestsRequest",
                    "",
                    |x: &WatchUserJoinRequestsRequest| &x._unrecognized,
                    |x: &mut WatchUserJoinRequestsRequest, u| x._unrecognized = u,
                )
            });
        &*ADAPTER
    }
    pub fn serializer() -> crate::skir_client::Serializer<WatchUserJoinRequestsRequest> {
        initialize_module_serializers();
        crate::skir_client::internal::struct_serializer_from_static(WatchUserJoinRequestsRequest::_adapter())
    }
}

// ==============================================================================
// struct WatchUserJoinRequestsResponse.InternalError
// ==============================================================================

#[derive(Clone, Debug, PartialEq, Default)]
pub struct WatchUserJoinRequestsResponse_InternalError {
    /// Set this to None when you're creating a struct.
    pub _unrecognized: Option<crate::skir_client::UnrecognizedFields<WatchUserJoinRequestsResponse_InternalError>>,
}

impl WatchUserJoinRequestsResponse_InternalError {
    pub fn default_ref() -> &'static WatchUserJoinRequestsResponse_InternalError {
        static D: std::sync::LazyLock<WatchUserJoinRequestsResponse_InternalError> = std::sync::LazyLock::new(WatchUserJoinRequestsResponse_InternalError::default);
        &D
    }
}

impl WatchUserJoinRequestsResponse_InternalError {
    fn _adapter() -> &'static crate::skir_client::internal::StructAdapter<WatchUserJoinRequestsResponse_InternalError> {
        static ADAPTER: std::sync::LazyLock<crate::skir_client::internal::StructAdapter<WatchUserJoinRequestsResponse_InternalError>> =
            std::sync::LazyLock::new(|| {
                crate::skir_client::internal::StructAdapter::new(
                    "organization/v1/user.skir",
                    "WatchUserJoinRequestsResponse.InternalError",
                    "",
                    |x: &WatchUserJoinRequestsResponse_InternalError| &x._unrecognized,
                    |x: &mut WatchUserJoinRequestsResponse_InternalError, u| x._unrecognized = u,
                )
            });
        &*ADAPTER
    }
    pub fn serializer() -> crate::skir_client::Serializer<WatchUserJoinRequestsResponse_InternalError> {
        initialize_module_serializers();
        crate::skir_client::internal::struct_serializer_from_static(WatchUserJoinRequestsResponse_InternalError::_adapter())
    }
}

// ==============================================================================
// enum WatchUserJoinRequestsResponse
// ==============================================================================

#[derive(Debug, Clone, PartialEq)]
pub enum WatchUserJoinRequestsResponse {
    Unknown(Option<crate::skir_client::UnrecognizedVariant<WatchUserJoinRequestsResponse>>),
    List(Vec<crate::skirout::base::organization::v1::join_request::UserJoinRequest>),
    Add(Box<crate::skirout::base::organization::v1::join_request::UserJoinRequest>),
    Remove(Box<crate::skirout::base::kernel::v1::record_id::RecordId>),
    InternalError(Box<WatchUserJoinRequestsResponse_InternalError>),
}

impl Default for WatchUserJoinRequestsResponse {
    fn default() -> Self {
        WatchUserJoinRequestsResponse::Unknown(None)
    }
}

impl WatchUserJoinRequestsResponse {
    fn _adapter() -> &'static crate::skir_client::internal::EnumAdapter<WatchUserJoinRequestsResponse> {
        static ADAPTER: std::sync::LazyLock<crate::skir_client::internal::EnumAdapter<WatchUserJoinRequestsResponse>> =
            std::sync::LazyLock::new(|| {
                crate::skir_client::internal::EnumAdapter::new(
                    |x: &WatchUserJoinRequestsResponse| match x {
                        WatchUserJoinRequestsResponse::Unknown(_) => 0,
                        WatchUserJoinRequestsResponse::List(_) => 1,
                        WatchUserJoinRequestsResponse::Add(_) => 2,
                        WatchUserJoinRequestsResponse::Remove(_) => 3,
                        WatchUserJoinRequestsResponse::InternalError(_) => 4,
                    },
                    |u| WatchUserJoinRequestsResponse::Unknown(Some(u)),
                    |x: &WatchUserJoinRequestsResponse| match x { WatchUserJoinRequestsResponse::Unknown(Some(u)) => Some(u.as_ref()), _ => None },
                    "organization/v1/user.skir",
                    "WatchUserJoinRequestsResponse",
                    "",
                )
            });
        &*ADAPTER
    }
    pub fn serializer() -> crate::skir_client::Serializer<WatchUserJoinRequestsResponse> {
        initialize_module_serializers();
        crate::skir_client::internal::enum_serializer_from_static(WatchUserJoinRequestsResponse::_adapter())
    }
}

// ==============================================================================
// struct SubmitUserJoinRequestRequest
// ==============================================================================

#[derive(Clone, Debug, PartialEq, Default)]
pub struct SubmitUserJoinRequestRequest {
    pub code: crate::skirout::base::kernel::v1::record_id::RecordId,
    /// Set this to None when you're creating a struct.
    pub _unrecognized: Option<crate::skir_client::UnrecognizedFields<SubmitUserJoinRequestRequest>>,
}

impl SubmitUserJoinRequestRequest {
    pub fn default_ref() -> &'static SubmitUserJoinRequestRequest {
        static D: std::sync::LazyLock<SubmitUserJoinRequestRequest> = std::sync::LazyLock::new(SubmitUserJoinRequestRequest::default);
        &D
    }
}

impl SubmitUserJoinRequestRequest {
    fn _adapter() -> &'static crate::skir_client::internal::StructAdapter<SubmitUserJoinRequestRequest> {
        static ADAPTER: std::sync::LazyLock<crate::skir_client::internal::StructAdapter<SubmitUserJoinRequestRequest>> =
            std::sync::LazyLock::new(|| {
                crate::skir_client::internal::StructAdapter::new(
                    "organization/v1/user.skir",
                    "SubmitUserJoinRequestRequest",
                    "",
                    |x: &SubmitUserJoinRequestRequest| &x._unrecognized,
                    |x: &mut SubmitUserJoinRequestRequest, u| x._unrecognized = u,
                )
            });
        &*ADAPTER
    }
    pub fn serializer() -> crate::skir_client::Serializer<SubmitUserJoinRequestRequest> {
        initialize_module_serializers();
        crate::skir_client::internal::struct_serializer_from_static(SubmitUserJoinRequestRequest::_adapter())
    }
}

// ==============================================================================
// struct SubmitUserJoinRequestResponse.CodeNotFoundError
// ==============================================================================

#[derive(Clone, Debug, PartialEq, Default)]
pub struct SubmitUserJoinRequestResponse_CodeNotFoundError {
    pub code: crate::skirout::base::kernel::v1::record_id::RecordId,
    /// Set this to None when you're creating a struct.
    pub _unrecognized: Option<crate::skir_client::UnrecognizedFields<SubmitUserJoinRequestResponse_CodeNotFoundError>>,
}

impl SubmitUserJoinRequestResponse_CodeNotFoundError {
    pub fn default_ref() -> &'static SubmitUserJoinRequestResponse_CodeNotFoundError {
        static D: std::sync::LazyLock<SubmitUserJoinRequestResponse_CodeNotFoundError> = std::sync::LazyLock::new(SubmitUserJoinRequestResponse_CodeNotFoundError::default);
        &D
    }
}

impl SubmitUserJoinRequestResponse_CodeNotFoundError {
    fn _adapter() -> &'static crate::skir_client::internal::StructAdapter<SubmitUserJoinRequestResponse_CodeNotFoundError> {
        static ADAPTER: std::sync::LazyLock<crate::skir_client::internal::StructAdapter<SubmitUserJoinRequestResponse_CodeNotFoundError>> =
            std::sync::LazyLock::new(|| {
                crate::skir_client::internal::StructAdapter::new(
                    "organization/v1/user.skir",
                    "SubmitUserJoinRequestResponse.CodeNotFoundError",
                    "",
                    |x: &SubmitUserJoinRequestResponse_CodeNotFoundError| &x._unrecognized,
                    |x: &mut SubmitUserJoinRequestResponse_CodeNotFoundError, u| x._unrecognized = u,
                )
            });
        &*ADAPTER
    }
    pub fn serializer() -> crate::skir_client::Serializer<SubmitUserJoinRequestResponse_CodeNotFoundError> {
        initialize_module_serializers();
        crate::skir_client::internal::struct_serializer_from_static(SubmitUserJoinRequestResponse_CodeNotFoundError::_adapter())
    }
}

// ==============================================================================
// struct SubmitUserJoinRequestResponse.AlreadyMemberError
// ==============================================================================

#[derive(Clone, Debug, PartialEq, Default)]
pub struct SubmitUserJoinRequestResponse_AlreadyMemberError {
    /// Set this to None when you're creating a struct.
    pub _unrecognized: Option<crate::skir_client::UnrecognizedFields<SubmitUserJoinRequestResponse_AlreadyMemberError>>,
}

impl SubmitUserJoinRequestResponse_AlreadyMemberError {
    pub fn default_ref() -> &'static SubmitUserJoinRequestResponse_AlreadyMemberError {
        static D: std::sync::LazyLock<SubmitUserJoinRequestResponse_AlreadyMemberError> = std::sync::LazyLock::new(SubmitUserJoinRequestResponse_AlreadyMemberError::default);
        &D
    }
}

impl SubmitUserJoinRequestResponse_AlreadyMemberError {
    fn _adapter() -> &'static crate::skir_client::internal::StructAdapter<SubmitUserJoinRequestResponse_AlreadyMemberError> {
        static ADAPTER: std::sync::LazyLock<crate::skir_client::internal::StructAdapter<SubmitUserJoinRequestResponse_AlreadyMemberError>> =
            std::sync::LazyLock::new(|| {
                crate::skir_client::internal::StructAdapter::new(
                    "organization/v1/user.skir",
                    "SubmitUserJoinRequestResponse.AlreadyMemberError",
                    "",
                    |x: &SubmitUserJoinRequestResponse_AlreadyMemberError| &x._unrecognized,
                    |x: &mut SubmitUserJoinRequestResponse_AlreadyMemberError, u| x._unrecognized = u,
                )
            });
        &*ADAPTER
    }
    pub fn serializer() -> crate::skir_client::Serializer<SubmitUserJoinRequestResponse_AlreadyMemberError> {
        initialize_module_serializers();
        crate::skir_client::internal::struct_serializer_from_static(SubmitUserJoinRequestResponse_AlreadyMemberError::_adapter())
    }
}

// ==============================================================================
// struct SubmitUserJoinRequestResponse.NoAssignableRolesError
// ==============================================================================

#[derive(Clone, Debug, PartialEq, Default)]
pub struct SubmitUserJoinRequestResponse_NoAssignableRolesError {
    /// Set this to None when you're creating a struct.
    pub _unrecognized: Option<crate::skir_client::UnrecognizedFields<SubmitUserJoinRequestResponse_NoAssignableRolesError>>,
}

impl SubmitUserJoinRequestResponse_NoAssignableRolesError {
    pub fn default_ref() -> &'static SubmitUserJoinRequestResponse_NoAssignableRolesError {
        static D: std::sync::LazyLock<SubmitUserJoinRequestResponse_NoAssignableRolesError> = std::sync::LazyLock::new(SubmitUserJoinRequestResponse_NoAssignableRolesError::default);
        &D
    }
}

impl SubmitUserJoinRequestResponse_NoAssignableRolesError {
    fn _adapter() -> &'static crate::skir_client::internal::StructAdapter<SubmitUserJoinRequestResponse_NoAssignableRolesError> {
        static ADAPTER: std::sync::LazyLock<crate::skir_client::internal::StructAdapter<SubmitUserJoinRequestResponse_NoAssignableRolesError>> =
            std::sync::LazyLock::new(|| {
                crate::skir_client::internal::StructAdapter::new(
                    "organization/v1/user.skir",
                    "SubmitUserJoinRequestResponse.NoAssignableRolesError",
                    "",
                    |x: &SubmitUserJoinRequestResponse_NoAssignableRolesError| &x._unrecognized,
                    |x: &mut SubmitUserJoinRequestResponse_NoAssignableRolesError, u| x._unrecognized = u,
                )
            });
        &*ADAPTER
    }
    pub fn serializer() -> crate::skir_client::Serializer<SubmitUserJoinRequestResponse_NoAssignableRolesError> {
        initialize_module_serializers();
        crate::skir_client::internal::struct_serializer_from_static(SubmitUserJoinRequestResponse_NoAssignableRolesError::_adapter())
    }
}

// ==============================================================================
// struct SubmitUserJoinRequestResponse.MaxPendingRequestsError
// ==============================================================================

#[derive(Clone, Debug, PartialEq, Default)]
pub struct SubmitUserJoinRequestResponse_MaxPendingRequestsError {
    /// Set this to None when you're creating a struct.
    pub _unrecognized: Option<crate::skir_client::UnrecognizedFields<SubmitUserJoinRequestResponse_MaxPendingRequestsError>>,
}

impl SubmitUserJoinRequestResponse_MaxPendingRequestsError {
    pub fn default_ref() -> &'static SubmitUserJoinRequestResponse_MaxPendingRequestsError {
        static D: std::sync::LazyLock<SubmitUserJoinRequestResponse_MaxPendingRequestsError> = std::sync::LazyLock::new(SubmitUserJoinRequestResponse_MaxPendingRequestsError::default);
        &D
    }
}

impl SubmitUserJoinRequestResponse_MaxPendingRequestsError {
    fn _adapter() -> &'static crate::skir_client::internal::StructAdapter<SubmitUserJoinRequestResponse_MaxPendingRequestsError> {
        static ADAPTER: std::sync::LazyLock<crate::skir_client::internal::StructAdapter<SubmitUserJoinRequestResponse_MaxPendingRequestsError>> =
            std::sync::LazyLock::new(|| {
                crate::skir_client::internal::StructAdapter::new(
                    "organization/v1/user.skir",
                    "SubmitUserJoinRequestResponse.MaxPendingRequestsError",
                    "",
                    |x: &SubmitUserJoinRequestResponse_MaxPendingRequestsError| &x._unrecognized,
                    |x: &mut SubmitUserJoinRequestResponse_MaxPendingRequestsError, u| x._unrecognized = u,
                )
            });
        &*ADAPTER
    }
    pub fn serializer() -> crate::skir_client::Serializer<SubmitUserJoinRequestResponse_MaxPendingRequestsError> {
        initialize_module_serializers();
        crate::skir_client::internal::struct_serializer_from_static(SubmitUserJoinRequestResponse_MaxPendingRequestsError::_adapter())
    }
}

// ==============================================================================
// struct SubmitUserJoinRequestResponse.PendingRequestExistsError
// ==============================================================================

#[derive(Clone, Debug, PartialEq, Default)]
pub struct SubmitUserJoinRequestResponse_PendingRequestExistsError {
    /// Set this to None when you're creating a struct.
    pub _unrecognized: Option<crate::skir_client::UnrecognizedFields<SubmitUserJoinRequestResponse_PendingRequestExistsError>>,
}

impl SubmitUserJoinRequestResponse_PendingRequestExistsError {
    pub fn default_ref() -> &'static SubmitUserJoinRequestResponse_PendingRequestExistsError {
        static D: std::sync::LazyLock<SubmitUserJoinRequestResponse_PendingRequestExistsError> = std::sync::LazyLock::new(SubmitUserJoinRequestResponse_PendingRequestExistsError::default);
        &D
    }
}

impl SubmitUserJoinRequestResponse_PendingRequestExistsError {
    fn _adapter() -> &'static crate::skir_client::internal::StructAdapter<SubmitUserJoinRequestResponse_PendingRequestExistsError> {
        static ADAPTER: std::sync::LazyLock<crate::skir_client::internal::StructAdapter<SubmitUserJoinRequestResponse_PendingRequestExistsError>> =
            std::sync::LazyLock::new(|| {
                crate::skir_client::internal::StructAdapter::new(
                    "organization/v1/user.skir",
                    "SubmitUserJoinRequestResponse.PendingRequestExistsError",
                    "",
                    |x: &SubmitUserJoinRequestResponse_PendingRequestExistsError| &x._unrecognized,
                    |x: &mut SubmitUserJoinRequestResponse_PendingRequestExistsError, u| x._unrecognized = u,
                )
            });
        &*ADAPTER
    }
    pub fn serializer() -> crate::skir_client::Serializer<SubmitUserJoinRequestResponse_PendingRequestExistsError> {
        initialize_module_serializers();
        crate::skir_client::internal::struct_serializer_from_static(SubmitUserJoinRequestResponse_PendingRequestExistsError::_adapter())
    }
}

// ==============================================================================
// struct SubmitUserJoinRequestResponse.InternalError
// ==============================================================================

#[derive(Clone, Debug, PartialEq, Default)]
pub struct SubmitUserJoinRequestResponse_InternalError {
    /// Set this to None when you're creating a struct.
    pub _unrecognized: Option<crate::skir_client::UnrecognizedFields<SubmitUserJoinRequestResponse_InternalError>>,
}

impl SubmitUserJoinRequestResponse_InternalError {
    pub fn default_ref() -> &'static SubmitUserJoinRequestResponse_InternalError {
        static D: std::sync::LazyLock<SubmitUserJoinRequestResponse_InternalError> = std::sync::LazyLock::new(SubmitUserJoinRequestResponse_InternalError::default);
        &D
    }
}

impl SubmitUserJoinRequestResponse_InternalError {
    fn _adapter() -> &'static crate::skir_client::internal::StructAdapter<SubmitUserJoinRequestResponse_InternalError> {
        static ADAPTER: std::sync::LazyLock<crate::skir_client::internal::StructAdapter<SubmitUserJoinRequestResponse_InternalError>> =
            std::sync::LazyLock::new(|| {
                crate::skir_client::internal::StructAdapter::new(
                    "organization/v1/user.skir",
                    "SubmitUserJoinRequestResponse.InternalError",
                    "",
                    |x: &SubmitUserJoinRequestResponse_InternalError| &x._unrecognized,
                    |x: &mut SubmitUserJoinRequestResponse_InternalError, u| x._unrecognized = u,
                )
            });
        &*ADAPTER
    }
    pub fn serializer() -> crate::skir_client::Serializer<SubmitUserJoinRequestResponse_InternalError> {
        initialize_module_serializers();
        crate::skir_client::internal::struct_serializer_from_static(SubmitUserJoinRequestResponse_InternalError::_adapter())
    }
}

// ==============================================================================
// enum SubmitUserJoinRequestResponse
// ==============================================================================

#[derive(Debug, Clone, PartialEq)]
pub enum SubmitUserJoinRequestResponse {
    Unknown(Option<crate::skir_client::UnrecognizedVariant<SubmitUserJoinRequestResponse>>),
    RequestMade(Box<crate::skirout::base::organization::v1::join_request::UserJoinRequest>),
    AutoAccepted(Box<crate::skirout::base::organization::v1::join_request::AutoAcceptedMember>),
    CodeNotFoundError(Box<SubmitUserJoinRequestResponse_CodeNotFoundError>),
    AlreadyMemberError(Box<SubmitUserJoinRequestResponse_AlreadyMemberError>),
    NoAssignableRolesError(Box<SubmitUserJoinRequestResponse_NoAssignableRolesError>),
    MaxPendingRequestsError(Box<SubmitUserJoinRequestResponse_MaxPendingRequestsError>),
    PendingRequestExistsError(Box<SubmitUserJoinRequestResponse_PendingRequestExistsError>),
    InternalError(Box<SubmitUserJoinRequestResponse_InternalError>),
}

impl Default for SubmitUserJoinRequestResponse {
    fn default() -> Self {
        SubmitUserJoinRequestResponse::Unknown(None)
    }
}

impl SubmitUserJoinRequestResponse {
    fn _adapter() -> &'static crate::skir_client::internal::EnumAdapter<SubmitUserJoinRequestResponse> {
        static ADAPTER: std::sync::LazyLock<crate::skir_client::internal::EnumAdapter<SubmitUserJoinRequestResponse>> =
            std::sync::LazyLock::new(|| {
                crate::skir_client::internal::EnumAdapter::new(
                    |x: &SubmitUserJoinRequestResponse| match x {
                        SubmitUserJoinRequestResponse::Unknown(_) => 0,
                        SubmitUserJoinRequestResponse::RequestMade(_) => 1,
                        SubmitUserJoinRequestResponse::AutoAccepted(_) => 2,
                        SubmitUserJoinRequestResponse::CodeNotFoundError(_) => 3,
                        SubmitUserJoinRequestResponse::AlreadyMemberError(_) => 4,
                        SubmitUserJoinRequestResponse::NoAssignableRolesError(_) => 5,
                        SubmitUserJoinRequestResponse::MaxPendingRequestsError(_) => 6,
                        SubmitUserJoinRequestResponse::PendingRequestExistsError(_) => 7,
                        SubmitUserJoinRequestResponse::InternalError(_) => 8,
                    },
                    |u| SubmitUserJoinRequestResponse::Unknown(Some(u)),
                    |x: &SubmitUserJoinRequestResponse| match x { SubmitUserJoinRequestResponse::Unknown(Some(u)) => Some(u.as_ref()), _ => None },
                    "organization/v1/user.skir",
                    "SubmitUserJoinRequestResponse",
                    "",
                )
            });
        &*ADAPTER
    }
    pub fn serializer() -> crate::skir_client::Serializer<SubmitUserJoinRequestResponse> {
        initialize_module_serializers();
        crate::skir_client::internal::enum_serializer_from_static(SubmitUserJoinRequestResponse::_adapter())
    }
}

// ==============================================================================
// struct CancelUserJoinRequestRequest
// ==============================================================================

#[derive(Clone, Debug, PartialEq, Default)]
pub struct CancelUserJoinRequestRequest {
    pub request_id: crate::skirout::base::kernel::v1::record_id::RecordId,
    /// Set this to None when you're creating a struct.
    pub _unrecognized: Option<crate::skir_client::UnrecognizedFields<CancelUserJoinRequestRequest>>,
}

impl CancelUserJoinRequestRequest {
    pub fn default_ref() -> &'static CancelUserJoinRequestRequest {
        static D: std::sync::LazyLock<CancelUserJoinRequestRequest> = std::sync::LazyLock::new(CancelUserJoinRequestRequest::default);
        &D
    }
}

impl CancelUserJoinRequestRequest {
    fn _adapter() -> &'static crate::skir_client::internal::StructAdapter<CancelUserJoinRequestRequest> {
        static ADAPTER: std::sync::LazyLock<crate::skir_client::internal::StructAdapter<CancelUserJoinRequestRequest>> =
            std::sync::LazyLock::new(|| {
                crate::skir_client::internal::StructAdapter::new(
                    "organization/v1/user.skir",
                    "CancelUserJoinRequestRequest",
                    "",
                    |x: &CancelUserJoinRequestRequest| &x._unrecognized,
                    |x: &mut CancelUserJoinRequestRequest, u| x._unrecognized = u,
                )
            });
        &*ADAPTER
    }
    pub fn serializer() -> crate::skir_client::Serializer<CancelUserJoinRequestRequest> {
        initialize_module_serializers();
        crate::skir_client::internal::struct_serializer_from_static(CancelUserJoinRequestRequest::_adapter())
    }
}

// ==============================================================================
// struct CancelUserJoinRequestResponse.Success
// ==============================================================================

#[derive(Clone, Debug, PartialEq, Default)]
pub struct CancelUserJoinRequestResponse_Success {
    /// Set this to None when you're creating a struct.
    pub _unrecognized: Option<crate::skir_client::UnrecognizedFields<CancelUserJoinRequestResponse_Success>>,
}

impl CancelUserJoinRequestResponse_Success {
    pub fn default_ref() -> &'static CancelUserJoinRequestResponse_Success {
        static D: std::sync::LazyLock<CancelUserJoinRequestResponse_Success> = std::sync::LazyLock::new(CancelUserJoinRequestResponse_Success::default);
        &D
    }
}

impl CancelUserJoinRequestResponse_Success {
    fn _adapter() -> &'static crate::skir_client::internal::StructAdapter<CancelUserJoinRequestResponse_Success> {
        static ADAPTER: std::sync::LazyLock<crate::skir_client::internal::StructAdapter<CancelUserJoinRequestResponse_Success>> =
            std::sync::LazyLock::new(|| {
                crate::skir_client::internal::StructAdapter::new(
                    "organization/v1/user.skir",
                    "CancelUserJoinRequestResponse.Success",
                    "",
                    |x: &CancelUserJoinRequestResponse_Success| &x._unrecognized,
                    |x: &mut CancelUserJoinRequestResponse_Success, u| x._unrecognized = u,
                )
            });
        &*ADAPTER
    }
    pub fn serializer() -> crate::skir_client::Serializer<CancelUserJoinRequestResponse_Success> {
        initialize_module_serializers();
        crate::skir_client::internal::struct_serializer_from_static(CancelUserJoinRequestResponse_Success::_adapter())
    }
}

// ==============================================================================
// struct CancelUserJoinRequestResponse.RequestNotFoundError
// ==============================================================================

#[derive(Clone, Debug, PartialEq, Default)]
pub struct CancelUserJoinRequestResponse_RequestNotFoundError {
    pub request_id: crate::skirout::base::kernel::v1::record_id::RecordId,
    /// Set this to None when you're creating a struct.
    pub _unrecognized: Option<crate::skir_client::UnrecognizedFields<CancelUserJoinRequestResponse_RequestNotFoundError>>,
}

impl CancelUserJoinRequestResponse_RequestNotFoundError {
    pub fn default_ref() -> &'static CancelUserJoinRequestResponse_RequestNotFoundError {
        static D: std::sync::LazyLock<CancelUserJoinRequestResponse_RequestNotFoundError> = std::sync::LazyLock::new(CancelUserJoinRequestResponse_RequestNotFoundError::default);
        &D
    }
}

impl CancelUserJoinRequestResponse_RequestNotFoundError {
    fn _adapter() -> &'static crate::skir_client::internal::StructAdapter<CancelUserJoinRequestResponse_RequestNotFoundError> {
        static ADAPTER: std::sync::LazyLock<crate::skir_client::internal::StructAdapter<CancelUserJoinRequestResponse_RequestNotFoundError>> =
            std::sync::LazyLock::new(|| {
                crate::skir_client::internal::StructAdapter::new(
                    "organization/v1/user.skir",
                    "CancelUserJoinRequestResponse.RequestNotFoundError",
                    "",
                    |x: &CancelUserJoinRequestResponse_RequestNotFoundError| &x._unrecognized,
                    |x: &mut CancelUserJoinRequestResponse_RequestNotFoundError, u| x._unrecognized = u,
                )
            });
        &*ADAPTER
    }
    pub fn serializer() -> crate::skir_client::Serializer<CancelUserJoinRequestResponse_RequestNotFoundError> {
        initialize_module_serializers();
        crate::skir_client::internal::struct_serializer_from_static(CancelUserJoinRequestResponse_RequestNotFoundError::_adapter())
    }
}

// ==============================================================================
// struct CancelUserJoinRequestResponse.InternalError
// ==============================================================================

#[derive(Clone, Debug, PartialEq, Default)]
pub struct CancelUserJoinRequestResponse_InternalError {
    /// Set this to None when you're creating a struct.
    pub _unrecognized: Option<crate::skir_client::UnrecognizedFields<CancelUserJoinRequestResponse_InternalError>>,
}

impl CancelUserJoinRequestResponse_InternalError {
    pub fn default_ref() -> &'static CancelUserJoinRequestResponse_InternalError {
        static D: std::sync::LazyLock<CancelUserJoinRequestResponse_InternalError> = std::sync::LazyLock::new(CancelUserJoinRequestResponse_InternalError::default);
        &D
    }
}

impl CancelUserJoinRequestResponse_InternalError {
    fn _adapter() -> &'static crate::skir_client::internal::StructAdapter<CancelUserJoinRequestResponse_InternalError> {
        static ADAPTER: std::sync::LazyLock<crate::skir_client::internal::StructAdapter<CancelUserJoinRequestResponse_InternalError>> =
            std::sync::LazyLock::new(|| {
                crate::skir_client::internal::StructAdapter::new(
                    "organization/v1/user.skir",
                    "CancelUserJoinRequestResponse.InternalError",
                    "",
                    |x: &CancelUserJoinRequestResponse_InternalError| &x._unrecognized,
                    |x: &mut CancelUserJoinRequestResponse_InternalError, u| x._unrecognized = u,
                )
            });
        &*ADAPTER
    }
    pub fn serializer() -> crate::skir_client::Serializer<CancelUserJoinRequestResponse_InternalError> {
        initialize_module_serializers();
        crate::skir_client::internal::struct_serializer_from_static(CancelUserJoinRequestResponse_InternalError::_adapter())
    }
}

// ==============================================================================
// enum CancelUserJoinRequestResponse
// ==============================================================================

#[derive(Debug, Clone, PartialEq)]
pub enum CancelUserJoinRequestResponse {
    Unknown(Option<crate::skir_client::UnrecognizedVariant<CancelUserJoinRequestResponse>>),
    Success(Box<CancelUserJoinRequestResponse_Success>),
    RequestNotFoundError(Box<CancelUserJoinRequestResponse_RequestNotFoundError>),
    InternalError(Box<CancelUserJoinRequestResponse_InternalError>),
}

impl Default for CancelUserJoinRequestResponse {
    fn default() -> Self {
        CancelUserJoinRequestResponse::Unknown(None)
    }
}

impl CancelUserJoinRequestResponse {
    fn _adapter() -> &'static crate::skir_client::internal::EnumAdapter<CancelUserJoinRequestResponse> {
        static ADAPTER: std::sync::LazyLock<crate::skir_client::internal::EnumAdapter<CancelUserJoinRequestResponse>> =
            std::sync::LazyLock::new(|| {
                crate::skir_client::internal::EnumAdapter::new(
                    |x: &CancelUserJoinRequestResponse| match x {
                        CancelUserJoinRequestResponse::Unknown(_) => 0,
                        CancelUserJoinRequestResponse::Success(_) => 1,
                        CancelUserJoinRequestResponse::RequestNotFoundError(_) => 2,
                        CancelUserJoinRequestResponse::InternalError(_) => 3,
                    },
                    |u| CancelUserJoinRequestResponse::Unknown(Some(u)),
                    |x: &CancelUserJoinRequestResponse| match x { CancelUserJoinRequestResponse::Unknown(Some(u)) => Some(u.as_ref()), _ => None },
                    "organization/v1/user.skir",
                    "CancelUserJoinRequestResponse",
                    "",
                )
            });
        &*ADAPTER
    }
    pub fn serializer() -> crate::skir_client::Serializer<CancelUserJoinRequestResponse> {
        initialize_module_serializers();
        crate::skir_client::internal::enum_serializer_from_static(CancelUserJoinRequestResponse::_adapter())
    }
}

// ==============================================================================
// initialize_module_serializers()
// ==============================================================================

fn initialize_module_serializers() {
    static INIT: std::sync::LazyLock<()> =
        std::sync::LazyLock::new(|| {
            unsafe {
                let a: *mut crate::skir_client::internal::StructAdapter<WatchUserOrganizationsRequest> = WatchUserOrganizationsRequest::_adapter() as *const _ as *mut _;
                (*a).finalize();
            }
            unsafe {
                let a: *mut crate::skir_client::internal::StructAdapter<WatchUserOrganizationsResponse_InternalError> = WatchUserOrganizationsResponse_InternalError::_adapter() as *const _ as *mut _;
                (*a).finalize();
            }
            unsafe {
                let a: *mut crate::skir_client::internal::EnumAdapter<WatchUserOrganizationsResponse> = WatchUserOrganizationsResponse::_adapter() as *const _ as *mut _;
                (*a).add_wrapper_variant("list", 1, 1, crate::skir_client::Serializer::array(crate::skirout::base::organization::v1::organization::Organization::serializer()), "", |v| WatchUserOrganizationsResponse::List(v), |x| match x { WatchUserOrganizationsResponse::List(v) => v, _ => unreachable!() });
                (*a).add_wrapper_variant("add", 2, 2, crate::skirout::base::organization::v1::organization::Organization::serializer(), "", |v| WatchUserOrganizationsResponse::Add(Box::new(v)), |x| match x { WatchUserOrganizationsResponse::Add(b) => b.as_ref(), _ => unreachable!() });
                (*a).add_wrapper_variant("remove", 3, 3, crate::skirout::base::kernel::v1::record_id::RecordId::serializer(), "", |v| WatchUserOrganizationsResponse::Remove(Box::new(v)), |x| match x { WatchUserOrganizationsResponse::Remove(b) => b.as_ref(), _ => unreachable!() });
                (*a).add_wrapper_variant("internal_error", 4, 4, crate::skir_client::internal::struct_serializer_from_static(WatchUserOrganizationsResponse_InternalError::_adapter()), "", |v| WatchUserOrganizationsResponse::InternalError(Box::new(v)), |x| match x { WatchUserOrganizationsResponse::InternalError(b) => b.as_ref(), _ => unreachable!() });
                (*a).finalize();
            }
            unsafe {
                let a: *mut crate::skir_client::internal::StructAdapter<WatchUserJoinRequestsRequest> = WatchUserJoinRequestsRequest::_adapter() as *const _ as *mut _;
                (*a).finalize();
            }
            unsafe {
                let a: *mut crate::skir_client::internal::StructAdapter<WatchUserJoinRequestsResponse_InternalError> = WatchUserJoinRequestsResponse_InternalError::_adapter() as *const _ as *mut _;
                (*a).finalize();
            }
            unsafe {
                let a: *mut crate::skir_client::internal::EnumAdapter<WatchUserJoinRequestsResponse> = WatchUserJoinRequestsResponse::_adapter() as *const _ as *mut _;
                (*a).add_wrapper_variant("list", 1, 1, crate::skir_client::Serializer::array(crate::skirout::base::organization::v1::join_request::UserJoinRequest::serializer()), "", |v| WatchUserJoinRequestsResponse::List(v), |x| match x { WatchUserJoinRequestsResponse::List(v) => v, _ => unreachable!() });
                (*a).add_wrapper_variant("add", 2, 2, crate::skirout::base::organization::v1::join_request::UserJoinRequest::serializer(), "", |v| WatchUserJoinRequestsResponse::Add(Box::new(v)), |x| match x { WatchUserJoinRequestsResponse::Add(b) => b.as_ref(), _ => unreachable!() });
                (*a).add_wrapper_variant("remove", 3, 3, crate::skirout::base::kernel::v1::record_id::RecordId::serializer(), "", |v| WatchUserJoinRequestsResponse::Remove(Box::new(v)), |x| match x { WatchUserJoinRequestsResponse::Remove(b) => b.as_ref(), _ => unreachable!() });
                (*a).add_wrapper_variant("internal_error", 4, 4, crate::skir_client::internal::struct_serializer_from_static(WatchUserJoinRequestsResponse_InternalError::_adapter()), "", |v| WatchUserJoinRequestsResponse::InternalError(Box::new(v)), |x| match x { WatchUserJoinRequestsResponse::InternalError(b) => b.as_ref(), _ => unreachable!() });
                (*a).finalize();
            }
            unsafe {
                let a: *mut crate::skir_client::internal::StructAdapter<SubmitUserJoinRequestRequest> = SubmitUserJoinRequestRequest::_adapter() as *const _ as *mut _;
                (*a).add_field("code", 0, crate::skirout::base::kernel::v1::record_id::RecordId::serializer(), "", |x: &SubmitUserJoinRequestRequest| &x.code, |x: &mut SubmitUserJoinRequestRequest, v| x.code = v);
                (*a).finalize();
            }
            unsafe {
                let a: *mut crate::skir_client::internal::StructAdapter<SubmitUserJoinRequestResponse_CodeNotFoundError> = SubmitUserJoinRequestResponse_CodeNotFoundError::_adapter() as *const _ as *mut _;
                (*a).add_field("code", 0, crate::skirout::base::kernel::v1::record_id::RecordId::serializer(), "", |x: &SubmitUserJoinRequestResponse_CodeNotFoundError| &x.code, |x: &mut SubmitUserJoinRequestResponse_CodeNotFoundError, v| x.code = v);
                (*a).finalize();
            }
            unsafe {
                let a: *mut crate::skir_client::internal::StructAdapter<SubmitUserJoinRequestResponse_AlreadyMemberError> = SubmitUserJoinRequestResponse_AlreadyMemberError::_adapter() as *const _ as *mut _;
                (*a).finalize();
            }
            unsafe {
                let a: *mut crate::skir_client::internal::StructAdapter<SubmitUserJoinRequestResponse_NoAssignableRolesError> = SubmitUserJoinRequestResponse_NoAssignableRolesError::_adapter() as *const _ as *mut _;
                (*a).finalize();
            }
            unsafe {
                let a: *mut crate::skir_client::internal::StructAdapter<SubmitUserJoinRequestResponse_MaxPendingRequestsError> = SubmitUserJoinRequestResponse_MaxPendingRequestsError::_adapter() as *const _ as *mut _;
                (*a).finalize();
            }
            unsafe {
                let a: *mut crate::skir_client::internal::StructAdapter<SubmitUserJoinRequestResponse_PendingRequestExistsError> = SubmitUserJoinRequestResponse_PendingRequestExistsError::_adapter() as *const _ as *mut _;
                (*a).finalize();
            }
            unsafe {
                let a: *mut crate::skir_client::internal::StructAdapter<SubmitUserJoinRequestResponse_InternalError> = SubmitUserJoinRequestResponse_InternalError::_adapter() as *const _ as *mut _;
                (*a).finalize();
            }
            unsafe {
                let a: *mut crate::skir_client::internal::EnumAdapter<SubmitUserJoinRequestResponse> = SubmitUserJoinRequestResponse::_adapter() as *const _ as *mut _;
                (*a).add_wrapper_variant("request_made", 1, 1, crate::skirout::base::organization::v1::join_request::UserJoinRequest::serializer(), "", |v| SubmitUserJoinRequestResponse::RequestMade(Box::new(v)), |x| match x { SubmitUserJoinRequestResponse::RequestMade(b) => b.as_ref(), _ => unreachable!() });
                (*a).add_wrapper_variant("auto_accepted", 2, 2, crate::skirout::base::organization::v1::join_request::AutoAcceptedMember::serializer(), "", |v| SubmitUserJoinRequestResponse::AutoAccepted(Box::new(v)), |x| match x { SubmitUserJoinRequestResponse::AutoAccepted(b) => b.as_ref(), _ => unreachable!() });
                (*a).add_wrapper_variant("code_not_found_error", 3, 3, crate::skir_client::internal::struct_serializer_from_static(SubmitUserJoinRequestResponse_CodeNotFoundError::_adapter()), "", |v| SubmitUserJoinRequestResponse::CodeNotFoundError(Box::new(v)), |x| match x { SubmitUserJoinRequestResponse::CodeNotFoundError(b) => b.as_ref(), _ => unreachable!() });
                (*a).add_wrapper_variant("already_member_error", 4, 4, crate::skir_client::internal::struct_serializer_from_static(SubmitUserJoinRequestResponse_AlreadyMemberError::_adapter()), "", |v| SubmitUserJoinRequestResponse::AlreadyMemberError(Box::new(v)), |x| match x { SubmitUserJoinRequestResponse::AlreadyMemberError(b) => b.as_ref(), _ => unreachable!() });
                (*a).add_wrapper_variant("no_assignable_roles_error", 5, 5, crate::skir_client::internal::struct_serializer_from_static(SubmitUserJoinRequestResponse_NoAssignableRolesError::_adapter()), "", |v| SubmitUserJoinRequestResponse::NoAssignableRolesError(Box::new(v)), |x| match x { SubmitUserJoinRequestResponse::NoAssignableRolesError(b) => b.as_ref(), _ => unreachable!() });
                (*a).add_wrapper_variant("max_pending_requests_error", 6, 6, crate::skir_client::internal::struct_serializer_from_static(SubmitUserJoinRequestResponse_MaxPendingRequestsError::_adapter()), "", |v| SubmitUserJoinRequestResponse::MaxPendingRequestsError(Box::new(v)), |x| match x { SubmitUserJoinRequestResponse::MaxPendingRequestsError(b) => b.as_ref(), _ => unreachable!() });
                (*a).add_wrapper_variant("pending_request_exists_error", 7, 7, crate::skir_client::internal::struct_serializer_from_static(SubmitUserJoinRequestResponse_PendingRequestExistsError::_adapter()), "", |v| SubmitUserJoinRequestResponse::PendingRequestExistsError(Box::new(v)), |x| match x { SubmitUserJoinRequestResponse::PendingRequestExistsError(b) => b.as_ref(), _ => unreachable!() });
                (*a).add_wrapper_variant("internal_error", 8, 8, crate::skir_client::internal::struct_serializer_from_static(SubmitUserJoinRequestResponse_InternalError::_adapter()), "", |v| SubmitUserJoinRequestResponse::InternalError(Box::new(v)), |x| match x { SubmitUserJoinRequestResponse::InternalError(b) => b.as_ref(), _ => unreachable!() });
                (*a).finalize();
            }
            unsafe {
                let a: *mut crate::skir_client::internal::StructAdapter<CancelUserJoinRequestRequest> = CancelUserJoinRequestRequest::_adapter() as *const _ as *mut _;
                (*a).add_field("request_id", 0, crate::skirout::base::kernel::v1::record_id::RecordId::serializer(), "", |x: &CancelUserJoinRequestRequest| &x.request_id, |x: &mut CancelUserJoinRequestRequest, v| x.request_id = v);
                (*a).finalize();
            }
            unsafe {
                let a: *mut crate::skir_client::internal::StructAdapter<CancelUserJoinRequestResponse_Success> = CancelUserJoinRequestResponse_Success::_adapter() as *const _ as *mut _;
                (*a).finalize();
            }
            unsafe {
                let a: *mut crate::skir_client::internal::StructAdapter<CancelUserJoinRequestResponse_RequestNotFoundError> = CancelUserJoinRequestResponse_RequestNotFoundError::_adapter() as *const _ as *mut _;
                (*a).add_field("request_id", 0, crate::skirout::base::kernel::v1::record_id::RecordId::serializer(), "", |x: &CancelUserJoinRequestResponse_RequestNotFoundError| &x.request_id, |x: &mut CancelUserJoinRequestResponse_RequestNotFoundError, v| x.request_id = v);
                (*a).finalize();
            }
            unsafe {
                let a: *mut crate::skir_client::internal::StructAdapter<CancelUserJoinRequestResponse_InternalError> = CancelUserJoinRequestResponse_InternalError::_adapter() as *const _ as *mut _;
                (*a).finalize();
            }
            unsafe {
                let a: *mut crate::skir_client::internal::EnumAdapter<CancelUserJoinRequestResponse> = CancelUserJoinRequestResponse::_adapter() as *const _ as *mut _;
                (*a).add_wrapper_variant("success", 1, 1, crate::skir_client::internal::struct_serializer_from_static(CancelUserJoinRequestResponse_Success::_adapter()), "", |v| CancelUserJoinRequestResponse::Success(Box::new(v)), |x| match x { CancelUserJoinRequestResponse::Success(b) => b.as_ref(), _ => unreachable!() });
                (*a).add_wrapper_variant("request_not_found_error", 2, 2, crate::skir_client::internal::struct_serializer_from_static(CancelUserJoinRequestResponse_RequestNotFoundError::_adapter()), "", |v| CancelUserJoinRequestResponse::RequestNotFoundError(Box::new(v)), |x| match x { CancelUserJoinRequestResponse::RequestNotFoundError(b) => b.as_ref(), _ => unreachable!() });
                (*a).add_wrapper_variant("internal_error", 3, 3, crate::skir_client::internal::struct_serializer_from_static(CancelUserJoinRequestResponse_InternalError::_adapter()), "", |v| CancelUserJoinRequestResponse::InternalError(Box::new(v)), |x| match x { CancelUserJoinRequestResponse::InternalError(b) => b.as_ref(), _ => unreachable!() });
                (*a).finalize();
            }
        });
    let _ = *INIT;
}

// ==============================================================================
// Methods
// ==============================================================================

pub fn watch_user_organizations_method() -> &'static crate::skir_client::Method<WatchUserOrganizationsRequest, WatchUserOrganizationsResponse> {
    static METHOD: std::sync::LazyLock<crate::skir_client::Method<WatchUserOrganizationsRequest, WatchUserOrganizationsResponse>> = std::sync::LazyLock::new(|| {
        crate::skir_client::Method {
            name: "WatchUserOrganizations".to_string(),
            number: 246975_i64,
            request_serializer: WatchUserOrganizationsRequest::serializer(),
            response_serializer: WatchUserOrganizationsResponse::serializer(),
            doc: "".to_string(),
        }
    });
    &*METHOD
}

pub fn watch_user_join_requests_method() -> &'static crate::skir_client::Method<WatchUserJoinRequestsRequest, WatchUserJoinRequestsResponse> {
    static METHOD: std::sync::LazyLock<crate::skir_client::Method<WatchUserJoinRequestsRequest, WatchUserJoinRequestsResponse>> = std::sync::LazyLock::new(|| {
        crate::skir_client::Method {
            name: "WatchUserJoinRequests".to_string(),
            number: 939197_i64,
            request_serializer: WatchUserJoinRequestsRequest::serializer(),
            response_serializer: WatchUserJoinRequestsResponse::serializer(),
            doc: "".to_string(),
        }
    });
    &*METHOD
}

pub fn submit_user_join_request_method() -> &'static crate::skir_client::Method<SubmitUserJoinRequestRequest, SubmitUserJoinRequestResponse> {
    static METHOD: std::sync::LazyLock<crate::skir_client::Method<SubmitUserJoinRequestRequest, SubmitUserJoinRequestResponse>> = std::sync::LazyLock::new(|| {
        crate::skir_client::Method {
            name: "SubmitUserJoinRequest".to_string(),
            number: 4962_i64,
            request_serializer: SubmitUserJoinRequestRequest::serializer(),
            response_serializer: SubmitUserJoinRequestResponse::serializer(),
            doc: "".to_string(),
        }
    });
    &*METHOD
}

pub fn cancel_user_join_request_method() -> &'static crate::skir_client::Method<CancelUserJoinRequestRequest, CancelUserJoinRequestResponse> {
    static METHOD: std::sync::LazyLock<crate::skir_client::Method<CancelUserJoinRequestRequest, CancelUserJoinRequestResponse>> = std::sync::LazyLock::new(|| {
        crate::skir_client::Method {
            name: "CancelUserJoinRequest".to_string(),
            number: 387737_i64,
            request_serializer: CancelUserJoinRequestRequest::serializer(),
            response_serializer: CancelUserJoinRequestResponse::serializer(),
            doc: "".to_string(),
        }
    });
    &*METHOD
}
