apiVersion: surrealdb.seamlezz.com/v1alpha1
kind: SurrealDBCredential
metadata:
  name: surrealdb-credentials-auth-typewriter-permissions
  namespace: typewriter
spec:
  policyRef:
    name: typewriter
  level: Database
  database: typewriter
  roles:
    - EDITOR
  targetSecret:
    name: surrealdb-credentials-auth-typewriter-permissions
