apiVersion: runtime.wasmcloud.dev/v1alpha1
kind: WorkloadDeployment
metadata:
  name: auth-auth-typewriter-permissions
  namespace: typewriter
spec:
  replicas: 1
  template:
    spec:
      environment: wasmcloud
      hostSelector:
        hostgroup: default
      components:
        - name: auth-auth-typewriter-permissions
      hostInterfaces:
        - namespace: wasi
          package: otel
          version: "0.2.0-rc.2"
          interfaces:
            - tracing
        - namespace: wasmcloud
          package: nats
          version: "0.1.0"
          interfaces:
            - core-handler
            - core
            - jetstream
          config:
            core-subscriptions: auth.permissions.typewriter-panel:typewriter.auth-auth-typewriter-permissions,auth.permissions.typewriter-services:typewriter.auth-auth-typewriter-permissions
        - namespace: seamlezz
          package: surrealdb
          version: "0.4.0"
          interfaces:
            - call
          secretFrom:
            - name: surrealdb-credentials-auth-typewriter-permissions
