[package]
name = "auth-typewriter-permissions"
version = "0.2.0"
edition.workspace = true
rust-version.workspace = true
repository.workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
base64.workspace = true
jose.workspace = true
nats-jwt-rs.workspace = true
serde.workspace = true
serde_json.workspace = true
wstd.workspace = true

wasmcloud-utils.workspace = true
wit-bindgen.workspace = true

opentelemetry.workspace = true
otel-wasi.workspace = true
tracing.workspace = true
tracing-opentelemetry.workspace = true

[dev-dependencies]
rstest.workspace = true
