[package]
name = "typewriter-component-test"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
publish.workspace = true
repository.workspace = true

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
component-test.workspace = true
indexmap.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
skir-client.workspace = true
surrealdb.workspace = true
tokio.workspace = true
toml.workspace = true
uuid.workspace = true
wash-runtime.workspace = true
wasmcloud-plugin-surrealdb.workspace = true
wasmcloud-utils = { path = "../../../../wasmcloud-utils" }

[build-dependencies]
indexmap.workspace = true
serde.workspace = true
toml.workspace = true

[dev-dependencies]
trybuild = "1"
