// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PermissionRequest {
    #[prost(string, optional, tag = "1")]
    pub organization_id: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(bytes = "vec", tag = "2")]
    pub jwt_claims: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PermissionResponse {
    #[prost(message, optional, tag = "1")]
    pub permissions: ::core::option::Option<super::super::models::v1::Permissions>,
    #[prost(string, repeated, tag = "2")]
    pub tags: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
/// GetSentinelCredentialsRequest requests the NATS sentinel credentials.
/// This endpoint is unauthenticated as sentinel credentials are needed
/// before authentication can occur.
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct GetSentinelCredentialsRequest {}
/// GetSentinelCredentialsResponse returns the sentinel credentials or an error.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetSentinelCredentialsResponse {
    #[prost(oneof = "get_sentinel_credentials_response::Result", tags = "1, 2")]
    pub result: ::core::option::Option<get_sentinel_credentials_response::Result>,
}
/// Nested message and enum types in `GetSentinelCredentialsResponse`.
pub mod get_sentinel_credentials_response {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Result {
        #[prost(message, tag = "1")]
        Credentials(super::SentinelCredentials),
        #[prost(message, tag = "2")]
        Error(super::super::super::models::v1::Error),
    }
}
/// SentinelCredentials contains the NATS sentinel JWT and seed.
/// These credentials have no permissions and are only used to identify
/// the account during NATS auth callout.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SentinelCredentials {
    #[prost(string, tag = "1")]
    pub jwt: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub seed: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct ListBooksRequest {}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListBooksResponse {
    #[prost(oneof = "list_books_response::Result", tags = "1, 2")]
    pub result: ::core::option::Option<list_books_response::Result>,
}
/// Nested message and enum types in `ListBooksResponse`.
pub mod list_books_response {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Result {
        #[prost(message, tag = "1")]
        Books(super::ListBooks),
        #[prost(message, tag = "2")]
        Error(super::super::super::models::v1::Error),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListBooks {
    #[prost(message, repeated, tag = "1")]
    pub books: ::prost::alloc::vec::Vec<super::super::models::v1::Book>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetBookRequest {
    #[prost(string, tag = "1")]
    pub book_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetBookResponse {
    #[prost(oneof = "get_book_response::Result", tags = "1, 2")]
    pub result: ::core::option::Option<get_book_response::Result>,
}
/// Nested message and enum types in `GetBookResponse`.
pub mod get_book_response {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Result {
        #[prost(message, tag = "1")]
        Book(super::super::super::models::v1::Book),
        #[prost(message, tag = "2")]
        Error(super::super::super::models::v1::Error),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UpdateBookRequest {
    #[prost(message, optional, tag = "1")]
    pub book: ::core::option::Option<super::super::models::v1::Book>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UpdateBookResponse {
    #[prost(oneof = "update_book_response::Result", tags = "1, 2")]
    pub result: ::core::option::Option<update_book_response::Result>,
}
/// Nested message and enum types in `UpdateBookResponse`.
pub mod update_book_response {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Result {
        #[prost(message, tag = "1")]
        Book(super::super::super::models::v1::Book),
        #[prost(message, tag = "2")]
        Error(super::super::super::models::v1::Error),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CreatePageRequest {
    #[prost(string, tag = "1")]
    pub book_id: ::prost::alloc::string::String,
    #[prost(string, optional, tag = "2")]
    pub name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(enumeration = "super::super::models::v1::PageType", tag = "3")]
    pub r#type: i32,
    #[prost(string, optional, tag = "4")]
    pub chapter: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int32, optional, tag = "5")]
    pub priority: ::core::option::Option<i32>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CreatePageResponse {
    #[prost(oneof = "create_page_response::Result", tags = "1, 2")]
    pub result: ::core::option::Option<create_page_response::Result>,
}
/// Nested message and enum types in `CreatePageResponse`.
pub mod create_page_response {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Result {
        #[prost(string, tag = "1")]
        PageId(::prost::alloc::string::String),
        #[prost(message, tag = "2")]
        Error(super::super::super::models::v1::Error),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DeletePageRequest {
    #[prost(string, tag = "1")]
    pub page_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DeletePageResponse {
    #[prost(oneof = "delete_page_response::Result", tags = "1, 2")]
    pub result: ::core::option::Option<delete_page_response::Result>,
}
/// Nested message and enum types in `DeletePageResponse`.
pub mod delete_page_response {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Result {
        #[prost(bool, tag = "1")]
        Success(bool),
        #[prost(message, tag = "2")]
        Error(super::super::super::models::v1::Error),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ChangePagesChaptersRequest {
    #[prost(string, tag = "1")]
    pub book_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub old_chapter: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub new_chapter: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ChangePagesChaptersResponse {
    #[prost(oneof = "change_pages_chapters_response::Result", tags = "1, 2")]
    pub result: ::core::option::Option<change_pages_chapters_response::Result>,
}
/// Nested message and enum types in `ChangePagesChaptersResponse`.
pub mod change_pages_chapters_response {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Result {
        #[prost(bool, tag = "1")]
        Success(bool),
        #[prost(message, tag = "2")]
        Error(super::super::super::models::v1::Error),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CreateBookRequest {
    #[prost(string, optional, tag = "1")]
    pub title: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "2")]
    pub icon: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(message, optional, tag = "3")]
    pub color: ::core::option::Option<super::super::models::v1::Color>,
    #[prost(string, repeated, tag = "4")]
    pub tag_ids: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CreateBookResponse {
    #[prost(oneof = "create_book_response::Result", tags = "1, 2")]
    pub result: ::core::option::Option<create_book_response::Result>,
}
/// Nested message and enum types in `CreateBookResponse`.
pub mod create_book_response {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Result {
        #[prost(message, tag = "1")]
        Book(super::super::super::models::v1::Book),
        #[prost(message, tag = "2")]
        Error(super::super::super::models::v1::Error),
    }
}
/// ListMembersRequest requests all members in the organization.
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct ListMembersRequest {}
/// ListMembersResponse contains all members in the organization.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListMembersResponse {
    #[prost(oneof = "list_members_response::Result", tags = "1, 2")]
    pub result: ::core::option::Option<list_members_response::Result>,
}
/// Nested message and enum types in `ListMembersResponse`.
pub mod list_members_response {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Result {
        #[prost(message, tag = "1")]
        Members(super::ListMembers),
        #[prost(message, tag = "2")]
        Error(super::super::super::models::v1::Error),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListMembers {
    #[prost(message, repeated, tag = "1")]
    pub members: ::prost::alloc::vec::Vec<super::super::models::v1::OrganizationMember>,
}
/// UpdateMemberRolesRequest updates the roles assigned to a member.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UpdateMemberRolesRequest {
    /// User ID of the member to update
    #[prost(string, tag = "1")]
    pub user_id: ::prost::alloc::string::String,
    /// List of role IDs to assign to the member
    #[prost(string, repeated, tag = "2")]
    pub role_ids: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
/// UpdateMemberRolesResponse returns the updated member or an error.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UpdateMemberRolesResponse {
    #[prost(oneof = "update_member_roles_response::Result", tags = "1, 2")]
    pub result: ::core::option::Option<update_member_roles_response::Result>,
}
/// Nested message and enum types in `UpdateMemberRolesResponse`.
pub mod update_member_roles_response {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Result {
        #[prost(message, tag = "1")]
        Member(super::super::super::models::v1::OrganizationMember),
        #[prost(message, tag = "2")]
        Error(super::super::super::models::v1::Error),
    }
}
/// RemoveMemberRequest removes a member from the organization.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RemoveMemberRequest {
    /// User ID of the member to remove
    #[prost(string, tag = "1")]
    pub user_id: ::prost::alloc::string::String,
}
/// RemoveMemberResponse indicates success or returns an error.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RemoveMemberResponse {
    #[prost(oneof = "remove_member_response::Result", tags = "1, 2")]
    pub result: ::core::option::Option<remove_member_response::Result>,
}
/// Nested message and enum types in `RemoveMemberResponse`.
pub mod remove_member_response {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Result {
        #[prost(bool, tag = "1")]
        Success(bool),
        #[prost(message, tag = "2")]
        Error(super::super::super::models::v1::Error),
    }
}
/// ListJoinRequestsRequest requests all pending join requests to the organization.
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct ListJoinRequestsRequest {}
/// ListJoinRequestsResponse contains all pending join requests.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListJoinRequestsResponse {
    #[prost(oneof = "list_join_requests_response::Result", tags = "1, 2")]
    pub result: ::core::option::Option<list_join_requests_response::Result>,
}
/// Nested message and enum types in `ListJoinRequestsResponse`.
pub mod list_join_requests_response {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Result {
        #[prost(message, tag = "1")]
        Requests(super::ListJoinRequests),
        #[prost(message, tag = "2")]
        Error(super::super::super::models::v1::Error),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListJoinRequests {
    #[prost(message, repeated, tag = "1")]
    pub requests: ::prost::alloc::vec::Vec<super::super::models::v1::JoinRequest>,
}
/// ApproveJoinRequestRequest approves a pending join request and assigns roles.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ApproveJoinRequestRequest {
    /// Unique identifier of the join request to approve
    #[prost(string, tag = "1")]
    pub request_id: ::prost::alloc::string::String,
    /// List of role IDs to assign to the new member
    #[prost(string, repeated, tag = "2")]
    pub role_ids: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
/// ApproveJoinRequestResponse returns the new member or an error.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ApproveJoinRequestResponse {
    #[prost(oneof = "approve_join_request_response::Result", tags = "1, 2")]
    pub result: ::core::option::Option<approve_join_request_response::Result>,
}
/// Nested message and enum types in `ApproveJoinRequestResponse`.
pub mod approve_join_request_response {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Result {
        #[prost(message, tag = "1")]
        Member(super::super::super::models::v1::OrganizationMember),
        #[prost(message, tag = "2")]
        Error(super::super::super::models::v1::Error),
    }
}
/// DeclineJoinRequestRequest declines a pending join request.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DeclineJoinRequestRequest {
    /// Unique identifier of the join request to decline
    #[prost(string, tag = "1")]
    pub request_id: ::prost::alloc::string::String,
}
/// DeclineJoinRequestResponse indicates success or returns an error.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DeclineJoinRequestResponse {
    #[prost(oneof = "decline_join_request_response::Result", tags = "1, 2")]
    pub result: ::core::option::Option<decline_join_request_response::Result>,
}
/// Nested message and enum types in `DeclineJoinRequestResponse`.
pub mod decline_join_request_response {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Result {
        #[prost(bool, tag = "1")]
        Success(bool),
        #[prost(message, tag = "2")]
        Error(super::super::super::models::v1::Error),
    }
}
/// GenerateJoinCodeRequest generates a new join code for the organization.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GenerateJoinCodeRequest {
    /// Whether this code can only be used once (default: true)
    #[prost(bool, tag = "1")]
    pub single_use: bool,
    /// Expiration configuration
    #[prost(message, optional, tag = "2")]
    pub expiration: ::core::option::Option<JoinCodeExpiration>,
    /// Auto-accept configuration (omit for manual approval)
    #[prost(message, optional, tag = "3")]
    pub auto_accept: ::core::option::Option<JoinCodeAutoAcceptConfig>,
}
/// JoinCodeExpiration specifies when the join code expires.
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct JoinCodeExpiration {
    #[prost(oneof = "join_code_expiration::Expiration", tags = "1, 2")]
    pub expiration: ::core::option::Option<join_code_expiration::Expiration>,
}
/// Nested message and enum types in `JoinCodeExpiration`.
pub mod join_code_expiration {
    #[derive(Clone, Copy, PartialEq, ::prost::Oneof)]
    pub enum Expiration {
        /// Set to true for a code that never expires
        #[prost(bool, tag = "1")]
        Never(bool),
        /// Expires after this many seconds from creation
        #[prost(int64, tag = "2")]
        DurationSeconds(i64),
    }
}
/// JoinCodeAutoAcceptConfig specifies auto-accept settings for code generation.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct JoinCodeAutoAcceptConfig {
    /// Role IDs to assign to auto-accepted users
    #[prost(string, repeated, tag = "1")]
    pub role_ids: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
/// GenerateJoinCodeResponse returns the generated join code or an error.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GenerateJoinCodeResponse {
    #[prost(oneof = "generate_join_code_response::Result", tags = "1, 2")]
    pub result: ::core::option::Option<generate_join_code_response::Result>,
}
/// Nested message and enum types in `GenerateJoinCodeResponse`.
pub mod generate_join_code_response {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Result {
        #[prost(message, tag = "1")]
        JoinCode(super::super::super::models::v1::JoinCode),
        #[prost(message, tag = "2")]
        Error(super::super::super::models::v1::Error),
    }
}
/// ListJoinCodesRequest requests all active join codes for the organization.
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct ListJoinCodesRequest {}
/// ListJoinCodesResponse contains all active join codes.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListJoinCodesResponse {
    #[prost(oneof = "list_join_codes_response::Result", tags = "1, 2")]
    pub result: ::core::option::Option<list_join_codes_response::Result>,
}
/// Nested message and enum types in `ListJoinCodesResponse`.
pub mod list_join_codes_response {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Result {
        #[prost(message, tag = "1")]
        JoinCodes(super::ListJoinCodes),
        #[prost(message, tag = "2")]
        Error(super::super::super::models::v1::Error),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListJoinCodes {
    #[prost(message, repeated, tag = "1")]
    pub join_codes: ::prost::alloc::vec::Vec<super::super::models::v1::JoinCode>,
}
/// RevokeJoinCodeRequest revokes a join code.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RevokeJoinCodeRequest {
    /// Unique identifier of the join code to revoke
    #[prost(string, tag = "1")]
    pub code_id: ::prost::alloc::string::String,
}
/// RevokeJoinCodeResponse indicates success or returns an error.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RevokeJoinCodeResponse {
    #[prost(oneof = "revoke_join_code_response::Result", tags = "1, 2")]
    pub result: ::core::option::Option<revoke_join_code_response::Result>,
}
/// Nested message and enum types in `RevokeJoinCodeResponse`.
pub mod revoke_join_code_response {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Result {
        #[prost(bool, tag = "1")]
        Success(bool),
        #[prost(message, tag = "2")]
        Error(super::super::super::models::v1::Error),
    }
}
/// ListRolesRequest requests all available roles in the organization.
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct ListRolesRequest {}
/// ListRolesResponse contains all available roles in the organization.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListRolesResponse {
    #[prost(oneof = "list_roles_response::Result", tags = "1, 2")]
    pub result: ::core::option::Option<list_roles_response::Result>,
}
/// Nested message and enum types in `ListRolesResponse`.
pub mod list_roles_response {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Result {
        #[prost(message, tag = "1")]
        Roles(super::ListRoles),
        #[prost(message, tag = "2")]
        Error(super::super::super::models::v1::Error),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListRoles {
    #[prost(message, repeated, tag = "1")]
    pub roles: ::prost::alloc::vec::Vec<super::super::models::v1::Role>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SearchPagesRequest {
    #[prost(string, tag = "1")]
    pub book_id: ::prost::alloc::string::String,
    #[prost(string, optional, tag = "2")]
    pub search: ::core::option::Option<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SearchPagesResult {
    #[prost(message, repeated, tag = "1")]
    pub pages: ::prost::alloc::vec::Vec<super::super::models::v1::Page>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SearchPagesResponse {
    #[prost(oneof = "search_pages_response::Result", tags = "1, 2")]
    pub result: ::core::option::Option<search_pages_response::Result>,
}
/// Nested message and enum types in `SearchPagesResponse`.
pub mod search_pages_response {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Result {
        #[prost(message, tag = "1")]
        Pages(super::SearchPagesResult),
        #[prost(message, tag = "2")]
        Error(super::super::super::models::v1::Error),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetPageRequest {
    #[prost(string, tag = "1")]
    pub page_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetPageResponse {
    #[prost(oneof = "get_page_response::Result", tags = "1, 2")]
    pub result: ::core::option::Option<get_page_response::Result>,
}
/// Nested message and enum types in `GetPageResponse`.
pub mod get_page_response {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Result {
        #[prost(message, tag = "1")]
        Page(super::super::super::models::v1::Page),
        #[prost(message, tag = "2")]
        Error(super::super::super::models::v1::Error),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UpdatePageRequest {
    #[prost(message, optional, tag = "1")]
    pub page: ::core::option::Option<super::super::models::v1::Page>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UpdatePageResponse {
    #[prost(oneof = "update_page_response::Result", tags = "1, 2")]
    pub result: ::core::option::Option<update_page_response::Result>,
}
/// Nested message and enum types in `UpdatePageResponse`.
pub mod update_page_response {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Result {
        #[prost(message, tag = "1")]
        Page(super::super::super::models::v1::Page),
        #[prost(message, tag = "2")]
        Error(super::super::super::models::v1::Error),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ChangePageChapterRequest {
    #[prost(string, tag = "1")]
    pub page_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub chapter: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ChangePageChapterResponse {
    #[prost(oneof = "change_page_chapter_response::Result", tags = "1, 2")]
    pub result: ::core::option::Option<change_page_chapter_response::Result>,
}
/// Nested message and enum types in `ChangePageChapterResponse`.
pub mod change_page_chapter_response {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Result {
        #[prost(bool, tag = "1")]
        Success(bool),
        #[prost(message, tag = "2")]
        Error(super::super::super::models::v1::Error),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ChangePagePriorityRequest {
    #[prost(string, tag = "1")]
    pub page_id: ::prost::alloc::string::String,
    #[prost(int32, tag = "2")]
    pub priority: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ChangePagePriorityResponse {
    #[prost(oneof = "change_page_priority_response::Result", tags = "1, 2")]
    pub result: ::core::option::Option<change_page_priority_response::Result>,
}
/// Nested message and enum types in `ChangePagePriorityResponse`.
pub mod change_page_priority_response {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Result {
        #[prost(bool, tag = "1")]
        Success(bool),
        #[prost(message, tag = "2")]
        Error(super::super::super::models::v1::Error),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RenamePageRequest {
    #[prost(string, tag = "1")]
    pub page_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RenamePageResponse {
    #[prost(oneof = "rename_page_response::Result", tags = "1, 2")]
    pub result: ::core::option::Option<rename_page_response::Result>,
}
/// Nested message and enum types in `RenamePageResponse`.
pub mod rename_page_response {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Result {
        #[prost(bool, tag = "1")]
        Success(bool),
        #[prost(message, tag = "2")]
        Error(super::super::super::models::v1::Error),
    }
}
/// GetServiceStatusRequest queries a service's binding status.
/// Service ID is extracted from the NATS subject.
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct GetServiceStatusRequest {}
/// GetServiceStatusResponse returns the service's binding status.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetServiceStatusResponse {
    #[prost(oneof = "get_service_status_response::Result", tags = "1, 2")]
    pub result: ::core::option::Option<get_service_status_response::Result>,
}
/// Nested message and enum types in `GetServiceStatusResponse`.
pub mod get_service_status_response {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Result {
        #[prost(message, tag = "1")]
        Status(super::ServiceStatus),
        #[prost(message, tag = "2")]
        Error(super::super::super::models::v1::Error),
    }
}
/// ServiceStatus indicates whether a service is bound to an organization.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ServiceStatus {
    #[prost(oneof = "service_status::Binding", tags = "1, 2")]
    pub binding: ::core::option::Option<service_status::Binding>,
}
/// Nested message and enum types in `ServiceStatus`.
pub mod service_status {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Binding {
        #[prost(message, tag = "1")]
        Bound(super::BoundStatus),
        #[prost(message, tag = "2")]
        Unbound(super::UnboundStatus),
    }
}
/// BoundStatus indicates the service is bound to an organization.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BoundStatus {
    #[prost(string, tag = "1")]
    pub organization_id: ::prost::alloc::string::String,
    #[prost(string, optional, tag = "2")]
    pub organization_name: ::core::option::Option<::prost::alloc::string::String>,
}
/// UnboundStatus indicates the service needs registration.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UnboundStatus {
    #[prost(string, optional, tag = "1")]
    pub registration_token: ::core::option::Option<::prost::alloc::string::String>,
}
/// BindServiceRequest binds a service to the organization using a token.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BindServiceRequest {
    #[prost(string, tag = "1")]
    pub registration_token: ::prost::alloc::string::String,
}
/// BindServiceResponse returns the bound service or an error.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BindServiceResponse {
    #[prost(oneof = "bind_service_response::Result", tags = "1, 2")]
    pub result: ::core::option::Option<bind_service_response::Result>,
}
/// Nested message and enum types in `BindServiceResponse`.
pub mod bind_service_response {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Result {
        #[prost(message, tag = "1")]
        Service(super::BoundService),
        #[prost(message, tag = "2")]
        Error(super::super::super::models::v1::Error),
    }
}
/// BoundService contains info about the newly bound service.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BoundService {
    #[prost(string, tag = "1")]
    pub service_id: ::prost::alloc::string::String,
    #[prost(string, optional, tag = "2")]
    pub service_name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(enumeration = "super::super::models::v1::ServiceType", repeated, tag = "3")]
    pub service_types: ::prost::alloc::vec::Vec<i32>,
}
/// ListOrganizationServicesRequest requests all services for an organization.
/// Organization ID is extracted from the NATS subject.
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct ListOrganizationServicesRequest {}
/// ListOrganizationServicesResponse returns the services or an error.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListOrganizationServicesResponse {
    #[prost(oneof = "list_organization_services_response::Result", tags = "1, 2")]
    pub result: ::core::option::Option<list_organization_services_response::Result>,
}
/// Nested message and enum types in `ListOrganizationServicesResponse`.
pub mod list_organization_services_response {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Result {
        #[prost(message, tag = "1")]
        Services(super::OrganizationServicesList),
        #[prost(message, tag = "2")]
        Error(super::super::super::models::v1::Error),
    }
}
/// OrganizationServicesList contains the list of services.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct OrganizationServicesList {
    #[prost(message, repeated, tag = "1")]
    pub services: ::prost::alloc::vec::Vec<super::super::models::v1::Service>,
}
/// ServiceBoundNotification is published when binding completes.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ServiceBoundNotification {
    #[prost(string, tag = "1")]
    pub organization_id: ::prost::alloc::string::String,
    #[prost(string, optional, tag = "2")]
    pub organization_name: ::core::option::Option<::prost::alloc::string::String>,
}
/// UpdateServiceRequest updates a service's metadata.
/// Service must be bound to the organization specified in the NATS subject.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UpdateServiceRequest {
    #[prost(string, tag = "1")]
    pub service_id: ::prost::alloc::string::String,
    #[prost(string, optional, tag = "2")]
    pub name: ::core::option::Option<::prost::alloc::string::String>,
}
/// UpdateServiceResponse returns the updated service or an error.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UpdateServiceResponse {
    #[prost(oneof = "update_service_response::Result", tags = "1, 2")]
    pub result: ::core::option::Option<update_service_response::Result>,
}
/// Nested message and enum types in `UpdateServiceResponse`.
pub mod update_service_response {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Result {
        #[prost(message, tag = "1")]
        Service(super::super::super::models::v1::Service),
        #[prost(message, tag = "2")]
        Error(super::super::super::models::v1::Error),
    }
}
/// UnbindServiceRequest removes a service from the organization.
/// Service must be bound to the organization specified in the NATS subject.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UnbindServiceRequest {
    #[prost(string, tag = "1")]
    pub service_id: ::prost::alloc::string::String,
}
/// UnbindServiceResponse returns success or an error.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UnbindServiceResponse {
    #[prost(oneof = "unbind_service_response::Result", tags = "1, 2")]
    pub result: ::core::option::Option<unbind_service_response::Result>,
}
/// Nested message and enum types in `UnbindServiceResponse`.
pub mod unbind_service_response {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Result {
        #[prost(bool, tag = "1")]
        Success(bool),
        #[prost(message, tag = "2")]
        Error(super::super::super::models::v1::Error),
    }
}
/// ServiceHeartbeatRequest updates the service's state to online.
/// Service ID is extracted from the NATS subject.
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct ServiceHeartbeatRequest {}
/// ServiceShutdownRequest indicates the service is going offline.
/// Service ID is extracted from the NATS subject.
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct ServiceShutdownRequest {}
/// IssueServiceIdentityRequest requests the issuance of a new service identity.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct IssueServiceIdentityRequest {
    /// List of service types (engine and/or realm).
    #[prost(enumeration = "super::super::models::v1::ServiceType", repeated, tag = "2")]
    pub service_types: ::prost::alloc::vec::Vec<i32>,
    /// Metadata about the service.
    #[prost(message, optional, tag = "3")]
    pub metadata: ::core::option::Option<super::super::models::v1::ServiceMetadata>,
}
/// IssueServiceIdentityResponse returns the credentials or an error.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct IssueServiceIdentityResponse {
    #[prost(oneof = "issue_service_identity_response::Result", tags = "1, 2")]
    pub result: ::core::option::Option<issue_service_identity_response::Result>,
}
/// Nested message and enum types in `IssueServiceIdentityResponse`.
pub mod issue_service_identity_response {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Result {
        #[prost(message, tag = "1")]
        Credentials(super::ServiceCredentials),
        #[prost(message, tag = "2")]
        Error(super::super::super::models::v1::Error),
    }
}
/// ServiceCredentials contains the authentication credentials for a service.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ServiceCredentials {
    /// Service identifier (SurrealDB record ID, which is the Authentik user ID).
    #[prost(string, tag = "1")]
    pub service_id: ::prost::alloc::string::String,
    /// Authentik username for the service.
    #[prost(string, tag = "2")]
    pub username: ::prost::alloc::string::String,
    /// Authentik authentication token.
    #[prost(string, tag = "3")]
    pub token: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct ListTagsRequest {}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListTagsResponse {
    #[prost(oneof = "list_tags_response::Result", tags = "1, 2")]
    pub result: ::core::option::Option<list_tags_response::Result>,
}
/// Nested message and enum types in `ListTagsResponse`.
pub mod list_tags_response {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Result {
        #[prost(message, tag = "1")]
        Tags(super::ListTags),
        #[prost(message, tag = "2")]
        Error(super::super::super::models::v1::Error),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListTags {
    #[prost(message, repeated, tag = "1")]
    pub tags: ::prost::alloc::vec::Vec<super::super::models::v1::Tag>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetTagRequest {
    #[prost(string, tag = "1")]
    pub tag_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetTagResponse {
    #[prost(oneof = "get_tag_response::Result", tags = "1, 2")]
    pub result: ::core::option::Option<get_tag_response::Result>,
}
/// Nested message and enum types in `GetTagResponse`.
pub mod get_tag_response {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Result {
        #[prost(message, tag = "1")]
        Tag(super::super::super::models::v1::Tag),
        #[prost(message, tag = "2")]
        Error(super::super::super::models::v1::Error),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CreateTagRequest {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "2")]
    pub color: ::core::option::Option<super::super::models::v1::Color>,
    #[prost(string, repeated, tag = "3")]
    pub parent_ids: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(message, optional, tag = "4")]
    pub placement: ::core::option::Option<super::super::models::v1::Placement>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CreateTagResponse {
    #[prost(oneof = "create_tag_response::Result", tags = "1, 2")]
    pub result: ::core::option::Option<create_tag_response::Result>,
}
/// Nested message and enum types in `CreateTagResponse`.
pub mod create_tag_response {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Result {
        #[prost(message, tag = "1")]
        Tag(super::super::super::models::v1::Tag),
        #[prost(message, tag = "2")]
        Error(super::super::super::models::v1::Error),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UpdateTagRequest {
    #[prost(message, optional, tag = "1")]
    pub tag: ::core::option::Option<super::super::models::v1::Tag>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UpdateTagResponse {
    #[prost(oneof = "update_tag_response::Result", tags = "1, 2")]
    pub result: ::core::option::Option<update_tag_response::Result>,
}
/// Nested message and enum types in `UpdateTagResponse`.
pub mod update_tag_response {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Result {
        #[prost(message, tag = "1")]
        Tag(super::super::super::models::v1::Tag),
        #[prost(message, tag = "2")]
        Error(super::super::super::models::v1::Error),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DeleteTagRequest {
    #[prost(string, tag = "1")]
    pub tag_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DeleteTagResponse {
    #[prost(oneof = "delete_tag_response::Result", tags = "1, 2")]
    pub result: ::core::option::Option<delete_tag_response::Result>,
}
/// Nested message and enum types in `DeleteTagResponse`.
pub mod delete_tag_response {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Result {
        #[prost(bool, tag = "1")]
        Success(bool),
        #[prost(message, tag = "2")]
        Error(super::super::super::models::v1::Error),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MoveTagRequest {
    #[prost(string, tag = "1")]
    pub tag_id: ::prost::alloc::string::String,
    #[prost(int32, optional, tag = "2")]
    pub x: ::core::option::Option<i32>,
    #[prost(int32, optional, tag = "3")]
    pub y: ::core::option::Option<i32>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MoveTagResponse {
    #[prost(oneof = "move_tag_response::Result", tags = "1, 2")]
    pub result: ::core::option::Option<move_tag_response::Result>,
}
/// Nested message and enum types in `MoveTagResponse`.
pub mod move_tag_response {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Result {
        #[prost(bool, tag = "1")]
        Success(bool),
        #[prost(message, tag = "2")]
        Error(super::super::super::models::v1::Error),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ResizeTagRequest {
    #[prost(string, tag = "1")]
    pub tag_id: ::prost::alloc::string::String,
    #[prost(int32, optional, tag = "2")]
    pub width: ::core::option::Option<i32>,
    #[prost(int32, optional, tag = "3")]
    pub height: ::core::option::Option<i32>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ResizeTagResponse {
    #[prost(oneof = "resize_tag_response::Result", tags = "1, 2")]
    pub result: ::core::option::Option<resize_tag_response::Result>,
}
/// Nested message and enum types in `ResizeTagResponse`.
pub mod resize_tag_response {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Result {
        #[prost(bool, tag = "1")]
        Success(bool),
        #[prost(message, tag = "2")]
        Error(super::super::super::models::v1::Error),
    }
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct ListOrganizationsRequest {}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListOrganizationsResponse {
    #[prost(oneof = "list_organizations_response::Result", tags = "1, 2")]
    pub result: ::core::option::Option<list_organizations_response::Result>,
}
/// Nested message and enum types in `ListOrganizationsResponse`.
pub mod list_organizations_response {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Result {
        #[prost(message, tag = "1")]
        Organizations(super::ListOrganizations),
        #[prost(message, tag = "2")]
        Error(super::super::super::models::v1::Error),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListOrganizations {
    #[prost(message, repeated, tag = "1")]
    pub organizations: ::prost::alloc::vec::Vec<
        super::super::models::v1::OrganizationData,
    >,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CreateOrganizationRequest {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, optional, tag = "2")]
    pub icon_url: ::core::option::Option<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CreateOrganizationResponse {
    #[prost(oneof = "create_organization_response::Result", tags = "1, 2")]
    pub result: ::core::option::Option<create_organization_response::Result>,
}
/// Nested message and enum types in `CreateOrganizationResponse`.
pub mod create_organization_response {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Result {
        #[prost(message, tag = "1")]
        Organization(super::super::super::models::v1::OrganizationData),
        #[prost(message, tag = "2")]
        Error(super::super::super::models::v1::Error),
    }
}
/// ListUserJoinRequestsRequest requests all pending join requests made by the user.
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct ListUserJoinRequestsRequest {}
/// ListUserJoinRequestsResponse contains all pending join requests made by the user.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListUserJoinRequestsResponse {
    #[prost(oneof = "list_user_join_requests_response::Result", tags = "1, 2")]
    pub result: ::core::option::Option<list_user_join_requests_response::Result>,
}
/// Nested message and enum types in `ListUserJoinRequestsResponse`.
pub mod list_user_join_requests_response {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Result {
        #[prost(message, tag = "1")]
        Requests(super::ListUserJoinRequests),
        #[prost(message, tag = "2")]
        Error(super::super::super::models::v1::Error),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListUserJoinRequests {
    #[prost(message, repeated, tag = "1")]
    pub requests: ::prost::alloc::vec::Vec<super::super::models::v1::UserJoinRequest>,
}
/// RequestToJoinRequest creates a join request using a code.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RequestToJoinRequest {
    /// The join code (e.g., "abc123")
    #[prost(string, optional, tag = "1")]
    pub code: ::core::option::Option<::prost::alloc::string::String>,
}
/// RequestToJoinResponse returns either a pending request, auto-accepted membership, or an error.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RequestToJoinResponse {
    #[prost(oneof = "request_to_join_response::Result", tags = "1, 2")]
    pub result: ::core::option::Option<request_to_join_response::Result>,
}
/// Nested message and enum types in `RequestToJoinResponse`.
pub mod request_to_join_response {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Result {
        #[prost(message, tag = "1")]
        Success(super::RequestToJoinResult),
        #[prost(message, tag = "2")]
        Error(super::super::super::models::v1::Error),
    }
}
/// RequestToJoinResult contains either a pending request or immediate membership.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RequestToJoinResult {
    #[prost(oneof = "request_to_join_result::Outcome", tags = "1, 2")]
    pub outcome: ::core::option::Option<request_to_join_result::Outcome>,
}
/// Nested message and enum types in `RequestToJoinResult`.
pub mod request_to_join_result {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Outcome {
        /// User has a pending request awaiting approval
        #[prost(message, tag = "1")]
        Request(super::super::super::models::v1::UserJoinRequest),
        /// User was auto-accepted and is now a member
        #[prost(message, tag = "2")]
        Member(super::AutoAcceptedMember),
    }
}
/// AutoAcceptedMember represents immediate membership after using an auto-accept code.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AutoAcceptedMember {
    /// Organization ID the user joined
    #[prost(string, tag = "1")]
    pub organization_id: ::prost::alloc::string::String,
    /// Organization name
    #[prost(string, optional, tag = "2")]
    pub organization_name: ::core::option::Option<::prost::alloc::string::String>,
    /// Organization icon URL
    #[prost(string, optional, tag = "3")]
    pub organization_icon_url: ::core::option::Option<::prost::alloc::string::String>,
    /// Roles assigned to the user
    #[prost(message, repeated, tag = "4")]
    pub roles: ::prost::alloc::vec::Vec<super::super::models::v1::Role>,
}
/// CancelJoinRequestRequest cancels a pending join request.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CancelJoinRequestRequest {
    /// Unique identifier of the join request to cancel
    #[prost(string, tag = "1")]
    pub request_id: ::prost::alloc::string::String,
}
/// CancelJoinRequestResponse indicates success or returns an error.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CancelJoinRequestResponse {
    #[prost(oneof = "cancel_join_request_response::Result", tags = "1, 2")]
    pub result: ::core::option::Option<cancel_join_request_response::Result>,
}
/// Nested message and enum types in `CancelJoinRequestResponse`.
pub mod cancel_join_request_response {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Result {
        #[prost(bool, tag = "1")]
        Success(bool),
        #[prost(message, tag = "2")]
        Error(super::super::super::models::v1::Error),
    }
}
