// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Permission {
    #[prost(string, repeated, tag = "1")]
    pub allow: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(string, repeated, tag = "2")]
    pub deny: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct ResponsePermission {
    #[prost(int32, tag = "1")]
    pub max_messages: i32,
    #[prost(message, optional, tag = "2")]
    pub ttl: ::core::option::Option<::prost_types::Duration>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Permissions {
    #[prost(message, optional, tag = "1")]
    pub publish: ::core::option::Option<Permission>,
    #[prost(message, optional, tag = "2")]
    pub subscribe: ::core::option::Option<Permission>,
    #[prost(message, optional, tag = "3")]
    pub resp: ::core::option::Option<ResponsePermission>,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct Color {
    #[prost(uint32, tag = "1")]
    pub value: u32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Error {
    #[prost(uint32, tag = "1")]
    pub code: u32,
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
    #[prost(string, repeated, tag = "3")]
    pub details: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Book {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub title: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub icon: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "4")]
    pub color: ::core::option::Option<Color>,
    #[prost(message, repeated, tag = "5")]
    pub tags: ::prost::alloc::vec::Vec<Tag>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Tag {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "3")]
    pub color: ::core::option::Option<Color>,
    #[prost(message, repeated, tag = "4")]
    pub parents: ::prost::alloc::vec::Vec<Tag>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Page {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub book_id: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub name: ::prost::alloc::string::String,
    #[prost(enumeration = "PageType", tag = "4")]
    pub r#type: i32,
    #[prost(string, tag = "5")]
    pub chapter: ::prost::alloc::string::String,
    #[prost(int32, tag = "6")]
    pub priority: i32,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum PageType {
    Sequence = 0,
    Static = 1,
    Scene = 2,
    Manifest = 3,
}
impl PageType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Sequence => "PAGE_TYPE_SEQUENCE",
            Self::Static => "PAGE_TYPE_STATIC",
            Self::Scene => "PAGE_TYPE_SCENE",
            Self::Manifest => "PAGE_TYPE_MANIFEST",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "PAGE_TYPE_SEQUENCE" => Some(Self::Sequence),
            "PAGE_TYPE_STATIC" => Some(Self::Static),
            "PAGE_TYPE_SCENE" => Some(Self::Scene),
            "PAGE_TYPE_MANIFEST" => Some(Self::Manifest),
            _ => None,
        }
    }
}
/// Role represents a role that can be assigned to organization members.
/// Roles define permissions and access levels within the organization.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Role {
    /// Unique identifier for the role
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    /// Display name of the role (e.g., "Admin", "Editor", "Viewer")
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
    /// Color for the role in ARGB format
    #[prost(message, optional, tag = "3")]
    pub color: ::core::option::Option<Color>,
    /// Whether this is the default role assigned to new members
    #[prost(bool, tag = "4")]
    pub default_role: bool,
    /// Whether this role can be assigned by administrators
    #[prost(bool, tag = "5")]
    pub assignable: bool,
    /// Whether this role can be deleted by administrators
    #[prost(bool, tag = "6")]
    pub deletable: bool,
}
/// OrganizationMember represents a user who is a member of an organization.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct OrganizationMember {
    /// Unique identifier for the member (the member_of relation ID)
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    /// Display name of the member
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
    /// Email address of the member
    #[prost(string, tag = "3")]
    pub email: ::prost::alloc::string::String,
    /// URL to the member's avatar image
    #[prost(string, tag = "4")]
    pub avatar_url: ::prost::alloc::string::String,
    /// Roles assigned to this member
    #[prost(message, repeated, tag = "5")]
    pub roles: ::prost::alloc::vec::Vec<Role>,
    /// Timestamp when the member joined the organization
    #[prost(message, optional, tag = "6")]
    pub joined_at: ::core::option::Option<::prost_types::Timestamp>,
}
/// JoinRequest represents a pending request from a user to join an organization.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct JoinRequest {
    /// Unique identifier for the join request (the requests_to_join relation ID)
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    /// Unique identifier of the requesting user
    #[prost(string, tag = "2")]
    pub user_id: ::prost::alloc::string::String,
    /// Display name of the requesting user
    #[prost(string, tag = "3")]
    pub user_name: ::prost::alloc::string::String,
    /// Email address of the requesting user
    #[prost(string, tag = "4")]
    pub user_email: ::prost::alloc::string::String,
    /// URL to the requesting user's avatar image
    #[prost(string, tag = "5")]
    pub user_avatar_url: ::prost::alloc::string::String,
    /// Timestamp when the request was created
    #[prost(message, optional, tag = "6")]
    pub requested_at: ::core::option::Option<::prost_types::Timestamp>,
    /// Timestamp when the request expires
    #[prost(message, optional, tag = "7")]
    pub expires_at: ::core::option::Option<::prost_types::Timestamp>,
}
/// UserJoinRequest represents a user's own pending request to join an organization.
/// This is from the user's perspective, showing which organizations they've requested to join.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UserJoinRequest {
    /// Unique identifier for the join request (the requests_to_join relation ID)
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    /// Organization ID the user is requesting to join
    #[prost(string, tag = "2")]
    pub organization_id: ::prost::alloc::string::String,
    /// Organization name
    #[prost(string, tag = "3")]
    pub organization_name: ::prost::alloc::string::String,
    /// Organization icon URL
    #[prost(string, tag = "4")]
    pub organization_icon_url: ::prost::alloc::string::String,
    /// Timestamp when the request was created
    #[prost(message, optional, tag = "5")]
    pub requested_at: ::core::option::Option<::prost_types::Timestamp>,
    /// Timestamp when the request expires
    #[prost(message, optional, tag = "6")]
    pub expires_at: ::core::option::Option<::prost_types::Timestamp>,
}
/// JoinCode represents a code that can be used to request to join an organization.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct JoinCode {
    /// The code string (e.g., "abc123")
    #[prost(string, tag = "2")]
    pub code: ::prost::alloc::string::String,
    /// Timestamp when the code was created
    #[prost(message, optional, tag = "3")]
    pub created_at: ::core::option::Option<::prost_types::Timestamp>,
    /// Timestamp when the code expires (not set = never expires)
    #[prost(message, optional, tag = "4")]
    pub expires_at: ::core::option::Option<::prost_types::Timestamp>,
    /// Whether this code can only be used once (deleted after use)
    #[prost(bool, tag = "5")]
    pub single_use: bool,
    /// Auto-accept configuration (not set = manual approval required)
    #[prost(message, optional, tag = "6")]
    pub auto_accept: ::core::option::Option<JoinCodeAutoAccept>,
}
/// JoinCodeAutoAccept contains the configuration for auto-accepting users.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct JoinCodeAutoAccept {
    /// Role IDs to assign to auto-accepted users
    #[prost(string, repeated, tag = "1")]
    pub role_ids: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
/// ServiceMetadata contains version and other metadata about a service.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ServiceMetadata {
    /// Version of the engine (if applicable).
    #[prost(string, optional, tag = "1")]
    pub engine_version: ::core::option::Option<::prost::alloc::string::String>,
    /// Version of the realm (if applicable).
    #[prost(string, optional, tag = "2")]
    pub realm_version: ::core::option::Option<::prost::alloc::string::String>,
}
/// Service represents a service identity stored in SurrealDB.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Service {
    /// Service identifier (authentik_user_id as record ID).
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    /// Name of the service.
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
    /// List of service types (engine and/or realm).
    #[prost(enumeration = "ServiceType", repeated, tag = "3")]
    pub service_types: ::prost::alloc::vec::Vec<i32>,
    /// Timestamp when the service was created.
    #[prost(message, optional, tag = "4")]
    pub created_at: ::core::option::Option<::prost_types::Timestamp>,
    /// Timestamp when the service was last seen (optional).
    #[prost(message, optional, tag = "5")]
    pub last_seen: ::core::option::Option<::prost_types::Timestamp>,
    /// Metadata about the service.
    #[prost(message, optional, tag = "6")]
    pub metadata: ::core::option::Option<ServiceMetadata>,
}
/// ServiceType represents the type of service (engine or realm).
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum ServiceType {
    /// Unspecified service type (default value).
    Unspecified = 0,
    /// Engine service type.
    Engine = 1,
    /// Realm service type.
    Realm = 2,
}
impl ServiceType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "SERVICE_TYPE_UNSPECIFIED",
            Self::Engine => "SERVICE_TYPE_ENGINE",
            Self::Realm => "SERVICE_TYPE_REALM",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "SERVICE_TYPE_UNSPECIFIED" => Some(Self::Unspecified),
            "SERVICE_TYPE_ENGINE" => Some(Self::Engine),
            "SERVICE_TYPE_REALM" => Some(Self::Realm),
            _ => None,
        }
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct OrganizationData {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub icon_url: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "4")]
    pub created_at: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(message, optional, tag = "5")]
    pub updated_at: ::core::option::Option<::prost_types::Timestamp>,
}
