package typewriter:user-organization@0.1.0;

world user-organization {
    import seamlezz:surrealdb/call@0.3.0;
    import wasmcloud:messaging/types@0.4.0;
    import wasmcloud:messaging/consumer@0.4.0;
    export wasmcloud:messaging/handler@0.4.0;
}