//  ______                        _               _  _  _
//  |  _  \                      | |             | |(_)| |
//  | | | |  ___    _ __    ___  | |_    ___   __| | _ | |_
//  | | | | / _ \  | '_ \  / _ \ | __|  / _ \ / _` || || __|
//  | |/ / | (_) | | | | || (_) || |_  |  __/| (_| || || |_
//  |___/   \___/  |_| |_| \___/  \__|  \___| \__,_||_| \__|
//
// Generated by skir-dart-gen
// Home: https://github.com/gepheum/skir-dart-gen
//
// To install the Skir client library:
//   dart pub add skir_client

import "dart:core" as _core;
import "package:skir_client/skir_client.dart" as _skir;

import "../../kernel/v1/errors.dart" as _lib_kernel_v1_errors;
import "../../kernel/v1/record_id.dart" as _lib_kernel_v1_record_id;
import "./service.dart" as _lib_service_v1_service;

// -----------------------------------------------------------------------------
// enum ServiceUpdateValidationError
// -----------------------------------------------------------------------------

/// To switch on the variants:
///   ```
///   switch (e) {
///     case ServiceUpdateValidationError_unknown(): { ... }
///     case ServiceUpdateValidationError.nameInvalid: { ... }
///   }
///   ```
///
/// Deeply immutable.
sealed class ServiceUpdateValidationError {
  /// Constant indicating an unknown `ServiceUpdateValidationError`.
  /// Default value for fields of type `ServiceUpdateValidationError`.
  static const ServiceUpdateValidationError unknown = ServiceUpdateValidationError_unknown._instance;

  static const nameInvalid = _ServiceUpdateValidationError_consts.nameInvalidConst;

  /// Returns the kind of variant held by this ServiceUpdateValidationError.
  ServiceUpdateValidationError_kind get kind;

  /// Serializer for `ServiceUpdateValidationError` instances.
  static _skir.EnumSerializer<ServiceUpdateValidationError> get serializer {
    if (_serializerBuilder.mustInitialize()) {
      _serializerBuilder.addConstantVariant(
        1,
        "name_invalid",
        "nameInvalid",
        "",
        nameInvalid,
      );
      _serializerBuilder.finalize();
    }
    return _serializerBuilder.serializer;
  }

  static final _serializerBuilder = _skir.internal__EnumSerializerBuilder.create(
    recordId: "service/v1/organization.skir:ServiceUpdateValidationError",
    doc: "",
    unknownInstance: ServiceUpdateValidationError_unknown._instance,
    enumInstance: ServiceUpdateValidationError.unknown,
    getOrdinal: (it) => it.kind._ordinal,
    wrapUnrecognized: ServiceUpdateValidationError_unknown._unrecognized,
    getUnrecognized: (it) => it._u,
  );
}

/// The kind of variant held by a `ServiceUpdateValidationError`.
enum ServiceUpdateValidationError_kind {
  unknown(0),
  nameInvalidConst(1);

  final _core.int _ordinal;

  const ServiceUpdateValidationError_kind(this._ordinal);
}

final class ServiceUpdateValidationError_unknown implements ServiceUpdateValidationError {
  static const _instance = ServiceUpdateValidationError_unknown._();

  final _skir.internal__UnrecognizedVariant? _u;

  const ServiceUpdateValidationError_unknown._() : _u = null;
  ServiceUpdateValidationError_unknown._unrecognized(this._u);

  @_core.override
  ServiceUpdateValidationError_kind get kind => ServiceUpdateValidationError_kind.unknown;
  @_core.override
  _core.bool operator ==(other) => other is ServiceUpdateValidationError_unknown;
  @_core.override
  _core.int get hashCode => 8118964;
  @_core.override
  _core.String toString() => _skir.internal__stringify(this, ServiceUpdateValidationError.serializer);
}

enum _ServiceUpdateValidationError_consts implements ServiceUpdateValidationError {
  nameInvalidConst(ServiceUpdateValidationError_kind.nameInvalidConst);

  @_core.override
  final ServiceUpdateValidationError_kind kind;

  const _ServiceUpdateValidationError_consts(this.kind);

  @_core.override
  _core.String toString() => _skir.internal__stringify(this, ServiceUpdateValidationError.serializer);
}

// -----------------------------------------------------------------------------
// struct WatchOrganizationServicesRequest
// -----------------------------------------------------------------------------

sealed class WatchOrganizationServicesRequest_orMutable {
  WatchOrganizationServicesRequest toFrozen();
}

/// Deeply immutable.
final class WatchOrganizationServicesRequest implements WatchOrganizationServicesRequest_orMutable {
  _skir.internal__UnrecognizedFields? _u;

  factory WatchOrganizationServicesRequest() => WatchOrganizationServicesRequest._();

  WatchOrganizationServicesRequest._();

  /// Default instance with all fields set to their default values.
  static final defaultInstance = WatchOrganizationServicesRequest._();

  /// Returns a new mutable instance.
  /// Fields are initialized to their default values.
  static WatchOrganizationServicesRequest_mutable mutable() => WatchOrganizationServicesRequest_mutable._();

  /// Returns this instance (no-op).
  @_core.Deprecated("This instance is already frozen.")
  @_core.override
  WatchOrganizationServicesRequest toFrozen() => this;

  /// Returns a mutable shallow copy of this instance.
  WatchOrganizationServicesRequest_mutable toMutable() => WatchOrganizationServicesRequest_mutable._();

  @_core.override
  _core.bool operator ==(other) {
    if (_core.identical(this, other)) return true;
    if (other is! WatchOrganizationServicesRequest) return false;
    return _skir.internal__listEquality.equals(_equality_proxy, other._equality_proxy);
  }

  @_core.override
  _core.int get hashCode => _skir.internal__listEquality.hash(_equality_proxy);

  _core.List get _equality_proxy => [];

  @_core.override
  _core.String toString() => _skir.internal__stringify(this, serializer);

  /// Serializer for `WatchOrganizationServicesRequest` instances.
  static _skir.StructSerializer<WatchOrganizationServicesRequest, WatchOrganizationServicesRequest_mutable> get serializer {
    if (_serializerBuilder.mustInitialize()) {
      _serializerBuilder.finalize();
    }
    return _serializerBuilder.serializer;
  }

  static final _serializerBuilder = _skir.internal__StructSerializerBuilder(
    recordId: "service/v1/organization.skir:WatchOrganizationServicesRequest",
    doc: "",
    defaultInstance: defaultInstance,
    newMutable: (it) => (it != null) ? it.toMutable() : mutable(),
    toFrozen: (WatchOrganizationServicesRequest_mutable it) => it.toFrozen(),
    getUnrecognizedFields: (it) => it._u,
    setUnrecognizedFields: (it, u) => it._u = u,
  );
}

/// Mutable version of [WatchOrganizationServicesRequest].
final class WatchOrganizationServicesRequest_mutable implements WatchOrganizationServicesRequest_orMutable {
  _skir.internal__UnrecognizedFields? _u;

  WatchOrganizationServicesRequest_mutable._();

  /// Returns a deeply immutable copy of this instance.
  @_core.override
  WatchOrganizationServicesRequest toFrozen() => WatchOrganizationServicesRequest().._u = this._u;
}

// -----------------------------------------------------------------------------
// enum WatchOrganizationServicesResponse
// -----------------------------------------------------------------------------

/// To switch on the variants:
///   ```
///   switch (e) {
///     case WatchOrganizationServicesResponse_unknown(): { ... }
///     case WatchOrganizationServicesResponse_internalError(:var value): { ... }
///     case WatchOrganizationServicesResponse_list(:var value): { ... }
///     case WatchOrganizationServicesResponse_add(:var value): { ... }
///     case WatchOrganizationServicesResponse_update(:var value): { ... }
///     case WatchOrganizationServicesResponse_remove(:var value): { ... }
///   }
///   ```
///
/// Deeply immutable.
sealed class WatchOrganizationServicesResponse {
  /// Constant indicating an unknown `WatchOrganizationServicesResponse`.
  /// Default value for fields of type `WatchOrganizationServicesResponse`.
  static const WatchOrganizationServicesResponse unknown = WatchOrganizationServicesResponse_unknown._instance;

  /// Create a 'internal_error' variant wrapping around the given value.
  factory WatchOrganizationServicesResponse.wrapInternalError(
    _lib_kernel_v1_errors.InternalError value
  ) => WatchOrganizationServicesResponse_internalErrorWrapper._(value);

  /// Same as `wrapInternalError(_lib_kernel_v1_errors.InternalError(...))`.
  factory WatchOrganizationServicesResponse.createInternalError() => WatchOrganizationServicesResponse.wrapInternalError(
    _lib_kernel_v1_errors.InternalError()
  );

  /// Create a 'list' variant wrapping around the given value.
  factory WatchOrganizationServicesResponse.wrapList(
    _core.Iterable<_lib_service_v1_service.Service> value
  ) => WatchOrganizationServicesResponse_listWrapper._(value);

  /// Create a 'add' variant wrapping around the given value.
  factory WatchOrganizationServicesResponse.wrapAdd(
    _lib_service_v1_service.Service value
  ) => WatchOrganizationServicesResponse_addWrapper._(value);

  /// Same as `wrapAdd(_lib_service_v1_service.Service(...))`.
  factory WatchOrganizationServicesResponse.createAdd({
    required _lib_kernel_v1_record_id.RecordId_orMutable serviceId,
    required _core.int revision,
    required _core.String name,
    required _lib_service_v1_service.ServiceRole role,
    required _core.DateTime createdAt,
    required _lib_kernel_v1_record_id.RecordId_orMutable? organization,
    required _lib_service_v1_service.ServiceRegistration_orMutable? registration,
    required _lib_service_v1_service.ServiceState_orMutable? state,
  }) => WatchOrganizationServicesResponse.wrapAdd(
    _lib_service_v1_service.Service(
      serviceId: serviceId,
      revision: revision,
      name: name,
      role: role,
      createdAt: createdAt,
      organization: organization,
      registration: registration,
      state: state,
    )
  );

  /// Create a 'update' variant wrapping around the given value.
  factory WatchOrganizationServicesResponse.wrapUpdate(
    _lib_service_v1_service.Service value
  ) => WatchOrganizationServicesResponse_updateWrapper._(value);

  /// Same as `wrapUpdate(_lib_service_v1_service.Service(...))`.
  factory WatchOrganizationServicesResponse.createUpdate({
    required _lib_kernel_v1_record_id.RecordId_orMutable serviceId,
    required _core.int revision,
    required _core.String name,
    required _lib_service_v1_service.ServiceRole role,
    required _core.DateTime createdAt,
    required _lib_kernel_v1_record_id.RecordId_orMutable? organization,
    required _lib_service_v1_service.ServiceRegistration_orMutable? registration,
    required _lib_service_v1_service.ServiceState_orMutable? state,
  }) => WatchOrganizationServicesResponse.wrapUpdate(
    _lib_service_v1_service.Service(
      serviceId: serviceId,
      revision: revision,
      name: name,
      role: role,
      createdAt: createdAt,
      organization: organization,
      registration: registration,
      state: state,
    )
  );

  /// Create a 'remove' variant wrapping around the given value.
  factory WatchOrganizationServicesResponse.wrapRemove(
    _lib_kernel_v1_record_id.RecordId value
  ) => WatchOrganizationServicesResponse_removeWrapper._(value);

  /// Same as `wrapRemove(_lib_kernel_v1_record_id.RecordId(...))`.
  factory WatchOrganizationServicesResponse.createRemove({
    required _core.String table,
    required _lib_kernel_v1_record_id.RecordIdKey key,
  }) => WatchOrganizationServicesResponse.wrapRemove(
    _lib_kernel_v1_record_id.RecordId(
      table: table,
      key: key,
    )
  );

  /// Returns the kind of variant held by this WatchOrganizationServicesResponse.
  WatchOrganizationServicesResponse_kind get kind;

  /// Serializer for `WatchOrganizationServicesResponse` instances.
  static _skir.EnumSerializer<WatchOrganizationServicesResponse> get serializer {
    if (_serializerBuilder.mustInitialize()) {
      _serializerBuilder.addWrapperVariant(
        1,
        "internal_error",
        "wrapInternalError",
        _lib_kernel_v1_errors.InternalError.serializer,
        "",
        WatchOrganizationServicesResponse_internalErrorWrapper._,
        (it) => it.value,
        ordinal: WatchOrganizationServicesResponse_kind.internalErrorWrapper._ordinal,
      );
      _serializerBuilder.addWrapperVariant(
        2,
        "list",
        "wrapList",
        _skir.Serializers.iterable(
          _lib_service_v1_service.Service.serializer,
        ),
        "",
        WatchOrganizationServicesResponse_listWrapper._,
        (it) => it.value,
        ordinal: WatchOrganizationServicesResponse_kind.listWrapper._ordinal,
      );
      _serializerBuilder.addWrapperVariant(
        3,
        "add",
        "wrapAdd",
        _lib_service_v1_service.Service.serializer,
        "",
        WatchOrganizationServicesResponse_addWrapper._,
        (it) => it.value,
        ordinal: WatchOrganizationServicesResponse_kind.addWrapper._ordinal,
      );
      _serializerBuilder.addWrapperVariant(
        4,
        "update",
        "wrapUpdate",
        _lib_service_v1_service.Service.serializer,
        "",
        WatchOrganizationServicesResponse_updateWrapper._,
        (it) => it.value,
        ordinal: WatchOrganizationServicesResponse_kind.updateWrapper._ordinal,
      );
      _serializerBuilder.addWrapperVariant(
        5,
        "remove",
        "wrapRemove",
        _lib_kernel_v1_record_id.RecordId.serializer,
        "",
        WatchOrganizationServicesResponse_removeWrapper._,
        (it) => it.value,
        ordinal: WatchOrganizationServicesResponse_kind.removeWrapper._ordinal,
      );
      _serializerBuilder.finalize();
    }
    return _serializerBuilder.serializer;
  }

  static final _serializerBuilder = _skir.internal__EnumSerializerBuilder.create(
    recordId: "service/v1/organization.skir:WatchOrganizationServicesResponse",
    doc: "",
    unknownInstance: WatchOrganizationServicesResponse_unknown._instance,
    enumInstance: WatchOrganizationServicesResponse.unknown,
    getOrdinal: (it) => it.kind._ordinal,
    wrapUnrecognized: WatchOrganizationServicesResponse_unknown._unrecognized,
    getUnrecognized: (it) => it._u,
  );
}

/// The kind of variant held by a `WatchOrganizationServicesResponse`.
enum WatchOrganizationServicesResponse_kind {
  unknown(0),
  internalErrorWrapper(1),
  listWrapper(2),
  addWrapper(3),
  updateWrapper(4),
  removeWrapper(5);

  final _core.int _ordinal;

  const WatchOrganizationServicesResponse_kind(this._ordinal);
}

final class WatchOrganizationServicesResponse_unknown implements WatchOrganizationServicesResponse {
  static const _instance = WatchOrganizationServicesResponse_unknown._();

  final _skir.internal__UnrecognizedVariant? _u;

  const WatchOrganizationServicesResponse_unknown._() : _u = null;
  WatchOrganizationServicesResponse_unknown._unrecognized(this._u);

  @_core.override
  WatchOrganizationServicesResponse_kind get kind => WatchOrganizationServicesResponse_kind.unknown;
  @_core.override
  _core.bool operator ==(other) => other is WatchOrganizationServicesResponse_unknown;
  @_core.override
  _core.int get hashCode => 8118964;
  @_core.override
  _core.String toString() => _skir.internal__stringify(this, WatchOrganizationServicesResponse.serializer);
}

sealed class _WatchOrganizationServicesResponse_wrapper implements WatchOrganizationServicesResponse {
  _core.dynamic get value;

  @_core.override
  _core.bool operator ==(other) {
    if (other is! _WatchOrganizationServicesResponse_wrapper) return false;
    return kind == other.kind && value == other.value;
  }

  @_core.override
  _core.int get hashCode => (kind._ordinal * 31) ^ value.hashCode;

  @_core.override
  _core.String toString() => _skir.internal__stringify(this, WatchOrganizationServicesResponse.serializer);
}

final class WatchOrganizationServicesResponse_internalErrorWrapper extends _WatchOrganizationServicesResponse_wrapper {
  final _lib_kernel_v1_errors.InternalError value;

  WatchOrganizationServicesResponse_internalErrorWrapper._(this.value);

  @_core.override
  WatchOrganizationServicesResponse_kind get kind => WatchOrganizationServicesResponse_kind.internalErrorWrapper;
}

final class WatchOrganizationServicesResponse_listWrapper extends _WatchOrganizationServicesResponse_wrapper {
  final _core.Iterable<_lib_service_v1_service.Service> value;

  WatchOrganizationServicesResponse_listWrapper._(this.value);

  @_core.override
  WatchOrganizationServicesResponse_kind get kind => WatchOrganizationServicesResponse_kind.listWrapper;
}

final class WatchOrganizationServicesResponse_addWrapper extends _WatchOrganizationServicesResponse_wrapper {
  final _lib_service_v1_service.Service value;

  WatchOrganizationServicesResponse_addWrapper._(this.value);

  @_core.override
  WatchOrganizationServicesResponse_kind get kind => WatchOrganizationServicesResponse_kind.addWrapper;
}

final class WatchOrganizationServicesResponse_updateWrapper extends _WatchOrganizationServicesResponse_wrapper {
  final _lib_service_v1_service.Service value;

  WatchOrganizationServicesResponse_updateWrapper._(this.value);

  @_core.override
  WatchOrganizationServicesResponse_kind get kind => WatchOrganizationServicesResponse_kind.updateWrapper;
}

final class WatchOrganizationServicesResponse_removeWrapper extends _WatchOrganizationServicesResponse_wrapper {
  final _lib_kernel_v1_record_id.RecordId value;

  WatchOrganizationServicesResponse_removeWrapper._(this.value);

  @_core.override
  WatchOrganizationServicesResponse_kind get kind => WatchOrganizationServicesResponse_kind.removeWrapper;
}

// -----------------------------------------------------------------------------
// struct UpdateOrganizationServiceRequest
// -----------------------------------------------------------------------------

sealed class UpdateOrganizationServiceRequest_orMutable {
  _lib_kernel_v1_record_id.RecordId_orMutable get serviceId;
  _core.int get expectedRevision;
  _core.String get name;

  UpdateOrganizationServiceRequest toFrozen();
}

/// Deeply immutable.
final class UpdateOrganizationServiceRequest implements UpdateOrganizationServiceRequest_orMutable {
  @_core.override
  final _lib_kernel_v1_record_id.RecordId serviceId;
  @_core.override
  final _core.int expectedRevision;
  @_core.override
  final _core.String name;
  _skir.internal__UnrecognizedFields? _u;

  factory UpdateOrganizationServiceRequest({
    required _lib_kernel_v1_record_id.RecordId_orMutable serviceId,
    required _core.int expectedRevision,
    required _core.String name,
  }) => UpdateOrganizationServiceRequest._(
    serviceId.toFrozen(),
    expectedRevision,
    name,
  );

  UpdateOrganizationServiceRequest._(
    this.serviceId,
    this.expectedRevision,
    this.name,
  );

  /// Default instance with all fields set to their default values.
  static final defaultInstance = UpdateOrganizationServiceRequest._(
    _lib_kernel_v1_record_id.RecordId.defaultInstance,
    0,
    "",
  );

  /// Returns a new mutable instance.
  /// Fields are initialized to their default values.
  static UpdateOrganizationServiceRequest_mutable mutable() => UpdateOrganizationServiceRequest_mutable._(
    _lib_kernel_v1_record_id.RecordId.defaultInstance,
    0,
    "",
  );

  /// Returns this instance (no-op).
  @_core.Deprecated("This instance is already frozen.")
  @_core.override
  UpdateOrganizationServiceRequest toFrozen() => this;

  /// Returns a mutable shallow copy of this instance.
  UpdateOrganizationServiceRequest_mutable toMutable() => UpdateOrganizationServiceRequest_mutable._(
    this.serviceId,
    this.expectedRevision,
    this.name,
  );

  @_core.override
  _core.bool operator ==(other) {
    if (_core.identical(this, other)) return true;
    if (other is! UpdateOrganizationServiceRequest) return false;
    return _skir.internal__listEquality.equals(_equality_proxy, other._equality_proxy);
  }

  @_core.override
  _core.int get hashCode => _skir.internal__listEquality.hash(_equality_proxy);

  _core.List get _equality_proxy => [
    this.serviceId,
    this.expectedRevision,
    this.name,
  ];

  @_core.override
  _core.String toString() => _skir.internal__stringify(this, serializer);

  /// Serializer for `UpdateOrganizationServiceRequest` instances.
  static _skir.StructSerializer<UpdateOrganizationServiceRequest, UpdateOrganizationServiceRequest_mutable> get serializer {
    if (_serializerBuilder.mustInitialize()) {
      _serializerBuilder.addField(
        "service_id",
        "serviceId",
        0,
        _lib_kernel_v1_record_id.RecordId.serializer,
        "",
        (it) => it.serviceId,
        (it, v) => it.serviceId = v,
      );
      _serializerBuilder.addField(
        "expected_revision",
        "expectedRevision",
        1,
        _skir.Serializers.int64,
        "",
        (it) => it.expectedRevision,
        (it, v) => it.expectedRevision = v,
      );
      _serializerBuilder.addField(
        "name",
        "name",
        2,
        _skir.Serializers.string,
        "",
        (it) => it.name,
        (it, v) => it.name = v,
      );
      _serializerBuilder.finalize();
    }
    return _serializerBuilder.serializer;
  }

  static final _serializerBuilder = _skir.internal__StructSerializerBuilder(
    recordId: "service/v1/organization.skir:UpdateOrganizationServiceRequest",
    doc: "",
    defaultInstance: defaultInstance,
    newMutable: (it) => (it != null) ? it.toMutable() : mutable(),
    toFrozen: (UpdateOrganizationServiceRequest_mutable it) => it.toFrozen(),
    getUnrecognizedFields: (it) => it._u,
    setUnrecognizedFields: (it, u) => it._u = u,
  );
}

/// Mutable version of [UpdateOrganizationServiceRequest].
final class UpdateOrganizationServiceRequest_mutable implements UpdateOrganizationServiceRequest_orMutable {
  _lib_kernel_v1_record_id.RecordId_orMutable serviceId;
  _core.int expectedRevision;
  _core.String name;
  _skir.internal__UnrecognizedFields? _u;

  UpdateOrganizationServiceRequest_mutable._(
    this.serviceId,
    this.expectedRevision,
    this.name,
  );

  /// If the value of [serviceId] is already mutable, returns it as-is.
  /// Otherwise, makes a mutable copy, assigns it back to [serviceId] and returns it.
  _lib_kernel_v1_record_id.RecordId_mutable get mutableServiceId {
    final value = this.serviceId;
    if (value is _lib_kernel_v1_record_id.RecordId_mutable) {
      return value;
    } else {
      return this.serviceId = (value as _lib_kernel_v1_record_id.RecordId).toMutable();
    }
  }

  /// Returns a deeply immutable copy of this instance.
  @_core.override
  UpdateOrganizationServiceRequest toFrozen() => UpdateOrganizationServiceRequest(
    serviceId: this.serviceId,
    expectedRevision: this.expectedRevision,
    name: this.name,
  ).._u = this._u;
}

// -----------------------------------------------------------------------------
// struct UpdateOrganizationServiceResponse.ConflictError
// -----------------------------------------------------------------------------

sealed class UpdateOrganizationServiceResponse_ConflictError_orMutable {
  _core.int get expectedRevision;
  _lib_service_v1_service.Service_orMutable get actual;

  UpdateOrganizationServiceResponse_ConflictError toFrozen();
}

/// Deeply immutable.
final class UpdateOrganizationServiceResponse_ConflictError implements UpdateOrganizationServiceResponse_ConflictError_orMutable {
  @_core.override
  final _core.int expectedRevision;
  @_core.override
  final _lib_service_v1_service.Service actual;
  _skir.internal__UnrecognizedFields? _u;

  factory UpdateOrganizationServiceResponse_ConflictError({
    required _core.int expectedRevision,
    required _lib_service_v1_service.Service_orMutable actual,
  }) => UpdateOrganizationServiceResponse_ConflictError._(
    expectedRevision,
    actual.toFrozen(),
  );

  UpdateOrganizationServiceResponse_ConflictError._(
    this.expectedRevision,
    this.actual,
  );

  /// Default instance with all fields set to their default values.
  static final defaultInstance = UpdateOrganizationServiceResponse_ConflictError._(
    0,
    _lib_service_v1_service.Service.defaultInstance,
  );

  /// Returns a new mutable instance.
  /// Fields are initialized to their default values.
  static UpdateOrganizationServiceResponse_ConflictError_mutable mutable() => UpdateOrganizationServiceResponse_ConflictError_mutable._(
    0,
    _lib_service_v1_service.Service.defaultInstance,
  );

  /// Returns this instance (no-op).
  @_core.Deprecated("This instance is already frozen.")
  @_core.override
  UpdateOrganizationServiceResponse_ConflictError toFrozen() => this;

  /// Returns a mutable shallow copy of this instance.
  UpdateOrganizationServiceResponse_ConflictError_mutable toMutable() => UpdateOrganizationServiceResponse_ConflictError_mutable._(
    this.expectedRevision,
    this.actual,
  );

  @_core.override
  _core.bool operator ==(other) {
    if (_core.identical(this, other)) return true;
    if (other is! UpdateOrganizationServiceResponse_ConflictError) return false;
    return _skir.internal__listEquality.equals(_equality_proxy, other._equality_proxy);
  }

  @_core.override
  _core.int get hashCode => _skir.internal__listEquality.hash(_equality_proxy);

  _core.List get _equality_proxy => [
    this.expectedRevision,
    this.actual,
  ];

  @_core.override
  _core.String toString() => _skir.internal__stringify(this, serializer);

  /// Serializer for `UpdateOrganizationServiceResponse_ConflictError` instances.
  static _skir.StructSerializer<UpdateOrganizationServiceResponse_ConflictError, UpdateOrganizationServiceResponse_ConflictError_mutable> get serializer {
    if (_serializerBuilder.mustInitialize()) {
      _serializerBuilder.addField(
        "expected_revision",
        "expectedRevision",
        0,
        _skir.Serializers.int64,
        "",
        (it) => it.expectedRevision,
        (it, v) => it.expectedRevision = v,
      );
      _serializerBuilder.addField(
        "actual",
        "actual",
        1,
        _lib_service_v1_service.Service.serializer,
        "",
        (it) => it.actual,
        (it, v) => it.actual = v,
      );
      _serializerBuilder.finalize();
    }
    return _serializerBuilder.serializer;
  }

  static final _serializerBuilder = _skir.internal__StructSerializerBuilder(
    recordId: "service/v1/organization.skir:UpdateOrganizationServiceResponse.ConflictError",
    doc: "",
    defaultInstance: defaultInstance,
    newMutable: (it) => (it != null) ? it.toMutable() : mutable(),
    toFrozen: (UpdateOrganizationServiceResponse_ConflictError_mutable it) => it.toFrozen(),
    getUnrecognizedFields: (it) => it._u,
    setUnrecognizedFields: (it, u) => it._u = u,
  );
}

/// Mutable version of [UpdateOrganizationServiceResponse_ConflictError].
final class UpdateOrganizationServiceResponse_ConflictError_mutable implements UpdateOrganizationServiceResponse_ConflictError_orMutable {
  _core.int expectedRevision;
  _lib_service_v1_service.Service_orMutable actual;
  _skir.internal__UnrecognizedFields? _u;

  UpdateOrganizationServiceResponse_ConflictError_mutable._(
    this.expectedRevision,
    this.actual,
  );

  /// If the value of [actual] is already mutable, returns it as-is.
  /// Otherwise, makes a mutable copy, assigns it back to [actual] and returns it.
  _lib_service_v1_service.Service_mutable get mutableActual {
    final value = this.actual;
    if (value is _lib_service_v1_service.Service_mutable) {
      return value;
    } else {
      return this.actual = (value as _lib_service_v1_service.Service).toMutable();
    }
  }

  /// Returns a deeply immutable copy of this instance.
  @_core.override
  UpdateOrganizationServiceResponse_ConflictError toFrozen() => UpdateOrganizationServiceResponse_ConflictError(
    expectedRevision: this.expectedRevision,
    actual: this.actual,
  ).._u = this._u;
}

// -----------------------------------------------------------------------------
// struct UpdateOrganizationServiceResponse.ServiceNotFoundError
// -----------------------------------------------------------------------------

sealed class UpdateOrganizationServiceResponse_ServiceNotFoundError_orMutable {
  UpdateOrganizationServiceResponse_ServiceNotFoundError toFrozen();
}

/// Deeply immutable.
final class UpdateOrganizationServiceResponse_ServiceNotFoundError implements UpdateOrganizationServiceResponse_ServiceNotFoundError_orMutable {
  _skir.internal__UnrecognizedFields? _u;

  factory UpdateOrganizationServiceResponse_ServiceNotFoundError() => UpdateOrganizationServiceResponse_ServiceNotFoundError._();

  UpdateOrganizationServiceResponse_ServiceNotFoundError._();

  /// Default instance with all fields set to their default values.
  static final defaultInstance = UpdateOrganizationServiceResponse_ServiceNotFoundError._();

  /// Returns a new mutable instance.
  /// Fields are initialized to their default values.
  static UpdateOrganizationServiceResponse_ServiceNotFoundError_mutable mutable() => UpdateOrganizationServiceResponse_ServiceNotFoundError_mutable._();

  /// Returns this instance (no-op).
  @_core.Deprecated("This instance is already frozen.")
  @_core.override
  UpdateOrganizationServiceResponse_ServiceNotFoundError toFrozen() => this;

  /// Returns a mutable shallow copy of this instance.
  UpdateOrganizationServiceResponse_ServiceNotFoundError_mutable toMutable() => UpdateOrganizationServiceResponse_ServiceNotFoundError_mutable._();

  @_core.override
  _core.bool operator ==(other) {
    if (_core.identical(this, other)) return true;
    if (other is! UpdateOrganizationServiceResponse_ServiceNotFoundError) return false;
    return _skir.internal__listEquality.equals(_equality_proxy, other._equality_proxy);
  }

  @_core.override
  _core.int get hashCode => _skir.internal__listEquality.hash(_equality_proxy);

  _core.List get _equality_proxy => [];

  @_core.override
  _core.String toString() => _skir.internal__stringify(this, serializer);

  /// Serializer for `UpdateOrganizationServiceResponse_ServiceNotFoundError` instances.
  static _skir.StructSerializer<UpdateOrganizationServiceResponse_ServiceNotFoundError, UpdateOrganizationServiceResponse_ServiceNotFoundError_mutable> get serializer {
    if (_serializerBuilder.mustInitialize()) {
      _serializerBuilder.finalize();
    }
    return _serializerBuilder.serializer;
  }

  static final _serializerBuilder = _skir.internal__StructSerializerBuilder(
    recordId: "service/v1/organization.skir:UpdateOrganizationServiceResponse.ServiceNotFoundError",
    doc: "",
    defaultInstance: defaultInstance,
    newMutable: (it) => (it != null) ? it.toMutable() : mutable(),
    toFrozen: (UpdateOrganizationServiceResponse_ServiceNotFoundError_mutable it) => it.toFrozen(),
    getUnrecognizedFields: (it) => it._u,
    setUnrecognizedFields: (it, u) => it._u = u,
  );
}

/// Mutable version of [UpdateOrganizationServiceResponse_ServiceNotFoundError].
final class UpdateOrganizationServiceResponse_ServiceNotFoundError_mutable implements UpdateOrganizationServiceResponse_ServiceNotFoundError_orMutable {
  _skir.internal__UnrecognizedFields? _u;

  UpdateOrganizationServiceResponse_ServiceNotFoundError_mutable._();

  /// Returns a deeply immutable copy of this instance.
  @_core.override
  UpdateOrganizationServiceResponse_ServiceNotFoundError toFrozen() => UpdateOrganizationServiceResponse_ServiceNotFoundError().._u = this._u;
}

// -----------------------------------------------------------------------------
// enum UpdateOrganizationServiceResponse
// -----------------------------------------------------------------------------

/// To switch on the variants:
///   ```
///   switch (e) {
///     case UpdateOrganizationServiceResponse_unknown(): { ... }
///     case UpdateOrganizationServiceResponse_internalError(:var value): { ... }
///     case UpdateOrganizationServiceResponse_success(:var value): { ... }
///     case UpdateOrganizationServiceResponse_conflictError(:var value): { ... }
///     case UpdateOrganizationServiceResponse_serviceNotFoundError(:var value): { ... }
///     case UpdateOrganizationServiceResponse_validationError(:var value): { ... }
///     case UpdateOrganizationServiceResponse_invalidRecordIdError(:var value): { ... }
///   }
///   ```
///
/// Deeply immutable.
sealed class UpdateOrganizationServiceResponse {
  /// Constant indicating an unknown `UpdateOrganizationServiceResponse`.
  /// Default value for fields of type `UpdateOrganizationServiceResponse`.
  static const UpdateOrganizationServiceResponse unknown = UpdateOrganizationServiceResponse_unknown._instance;

  /// Create a 'internal_error' variant wrapping around the given value.
  factory UpdateOrganizationServiceResponse.wrapInternalError(
    _lib_kernel_v1_errors.InternalError value
  ) => UpdateOrganizationServiceResponse_internalErrorWrapper._(value);

  /// Same as `wrapInternalError(_lib_kernel_v1_errors.InternalError(...))`.
  factory UpdateOrganizationServiceResponse.createInternalError() => UpdateOrganizationServiceResponse.wrapInternalError(
    _lib_kernel_v1_errors.InternalError()
  );

  /// Create a 'success' variant wrapping around the given value.
  factory UpdateOrganizationServiceResponse.wrapSuccess(
    _lib_service_v1_service.Service value
  ) => UpdateOrganizationServiceResponse_successWrapper._(value);

  /// Same as `wrapSuccess(_lib_service_v1_service.Service(...))`.
  factory UpdateOrganizationServiceResponse.createSuccess({
    required _lib_kernel_v1_record_id.RecordId_orMutable serviceId,
    required _core.int revision,
    required _core.String name,
    required _lib_service_v1_service.ServiceRole role,
    required _core.DateTime createdAt,
    required _lib_kernel_v1_record_id.RecordId_orMutable? organization,
    required _lib_service_v1_service.ServiceRegistration_orMutable? registration,
    required _lib_service_v1_service.ServiceState_orMutable? state,
  }) => UpdateOrganizationServiceResponse.wrapSuccess(
    _lib_service_v1_service.Service(
      serviceId: serviceId,
      revision: revision,
      name: name,
      role: role,
      createdAt: createdAt,
      organization: organization,
      registration: registration,
      state: state,
    )
  );

  /// Create a 'conflict_error' variant wrapping around the given value.
  factory UpdateOrganizationServiceResponse.wrapConflictError(
    UpdateOrganizationServiceResponse_ConflictError value
  ) => UpdateOrganizationServiceResponse_conflictErrorWrapper._(value);

  /// Same as `wrapConflictError(UpdateOrganizationServiceResponse_ConflictError(...))`.
  factory UpdateOrganizationServiceResponse.createConflictError({
    required _core.int expectedRevision,
    required _lib_service_v1_service.Service_orMutable actual,
  }) => UpdateOrganizationServiceResponse.wrapConflictError(
    UpdateOrganizationServiceResponse_ConflictError(
      expectedRevision: expectedRevision,
      actual: actual,
    )
  );

  /// Create a 'service_not_found_error' variant wrapping around the given value.
  factory UpdateOrganizationServiceResponse.wrapServiceNotFoundError(
    UpdateOrganizationServiceResponse_ServiceNotFoundError value
  ) => UpdateOrganizationServiceResponse_serviceNotFoundErrorWrapper._(value);

  /// Same as `wrapServiceNotFoundError(UpdateOrganizationServiceResponse_ServiceNotFoundError(...))`.
  factory UpdateOrganizationServiceResponse.createServiceNotFoundError() => UpdateOrganizationServiceResponse.wrapServiceNotFoundError(
    UpdateOrganizationServiceResponse_ServiceNotFoundError()
  );

  /// Create a 'validation_error' variant wrapping around the given value.
  factory UpdateOrganizationServiceResponse.wrapValidationError(
    ServiceUpdateValidationError value
  ) => UpdateOrganizationServiceResponse_validationErrorWrapper._(value);

  /// Create a 'invalid_record_id_error' variant wrapping around the given value.
  factory UpdateOrganizationServiceResponse.wrapInvalidRecordIdError(
    _lib_kernel_v1_errors.InvalidRecordIdError value
  ) => UpdateOrganizationServiceResponse_invalidRecordIdErrorWrapper._(value);

  /// Same as `wrapInvalidRecordIdError(_lib_kernel_v1_errors.InvalidRecordIdError(...))`.
  factory UpdateOrganizationServiceResponse.createInvalidRecordIdError({
    required _core.String expectedTable,
    required _core.Iterable<_core.String> givenTables,
  }) => UpdateOrganizationServiceResponse.wrapInvalidRecordIdError(
    _lib_kernel_v1_errors.InvalidRecordIdError(
      expectedTable: expectedTable,
      givenTables: givenTables,
    )
  );

  /// Returns the kind of variant held by this UpdateOrganizationServiceResponse.
  UpdateOrganizationServiceResponse_kind get kind;

  /// Serializer for `UpdateOrganizationServiceResponse` instances.
  static _skir.EnumSerializer<UpdateOrganizationServiceResponse> get serializer {
    if (_serializerBuilder.mustInitialize()) {
      _serializerBuilder.addWrapperVariant(
        1,
        "internal_error",
        "wrapInternalError",
        _lib_kernel_v1_errors.InternalError.serializer,
        "",
        UpdateOrganizationServiceResponse_internalErrorWrapper._,
        (it) => it.value,
        ordinal: UpdateOrganizationServiceResponse_kind.internalErrorWrapper._ordinal,
      );
      _serializerBuilder.addWrapperVariant(
        2,
        "success",
        "wrapSuccess",
        _lib_service_v1_service.Service.serializer,
        "",
        UpdateOrganizationServiceResponse_successWrapper._,
        (it) => it.value,
        ordinal: UpdateOrganizationServiceResponse_kind.successWrapper._ordinal,
      );
      _serializerBuilder.addWrapperVariant(
        3,
        "conflict_error",
        "wrapConflictError",
        UpdateOrganizationServiceResponse_ConflictError.serializer,
        "",
        UpdateOrganizationServiceResponse_conflictErrorWrapper._,
        (it) => it.value,
        ordinal: UpdateOrganizationServiceResponse_kind.conflictErrorWrapper._ordinal,
      );
      _serializerBuilder.addWrapperVariant(
        4,
        "service_not_found_error",
        "wrapServiceNotFoundError",
        UpdateOrganizationServiceResponse_ServiceNotFoundError.serializer,
        "",
        UpdateOrganizationServiceResponse_serviceNotFoundErrorWrapper._,
        (it) => it.value,
        ordinal: UpdateOrganizationServiceResponse_kind.serviceNotFoundErrorWrapper._ordinal,
      );
      _serializerBuilder.addWrapperVariant(
        5,
        "validation_error",
        "wrapValidationError",
        ServiceUpdateValidationError.serializer,
        "",
        UpdateOrganizationServiceResponse_validationErrorWrapper._,
        (it) => it.value,
        ordinal: UpdateOrganizationServiceResponse_kind.validationErrorWrapper._ordinal,
      );
      _serializerBuilder.addWrapperVariant(
        6,
        "invalid_record_id_error",
        "wrapInvalidRecordIdError",
        _lib_kernel_v1_errors.InvalidRecordIdError.serializer,
        "",
        UpdateOrganizationServiceResponse_invalidRecordIdErrorWrapper._,
        (it) => it.value,
        ordinal: UpdateOrganizationServiceResponse_kind.invalidRecordIdErrorWrapper._ordinal,
      );
      _serializerBuilder.finalize();
    }
    return _serializerBuilder.serializer;
  }

  static final _serializerBuilder = _skir.internal__EnumSerializerBuilder.create(
    recordId: "service/v1/organization.skir:UpdateOrganizationServiceResponse",
    doc: "",
    unknownInstance: UpdateOrganizationServiceResponse_unknown._instance,
    enumInstance: UpdateOrganizationServiceResponse.unknown,
    getOrdinal: (it) => it.kind._ordinal,
    wrapUnrecognized: UpdateOrganizationServiceResponse_unknown._unrecognized,
    getUnrecognized: (it) => it._u,
  );
}

/// The kind of variant held by a `UpdateOrganizationServiceResponse`.
enum UpdateOrganizationServiceResponse_kind {
  unknown(0),
  internalErrorWrapper(1),
  successWrapper(2),
  conflictErrorWrapper(3),
  serviceNotFoundErrorWrapper(4),
  validationErrorWrapper(5),
  invalidRecordIdErrorWrapper(6);

  final _core.int _ordinal;

  const UpdateOrganizationServiceResponse_kind(this._ordinal);
}

final class UpdateOrganizationServiceResponse_unknown implements UpdateOrganizationServiceResponse {
  static const _instance = UpdateOrganizationServiceResponse_unknown._();

  final _skir.internal__UnrecognizedVariant? _u;

  const UpdateOrganizationServiceResponse_unknown._() : _u = null;
  UpdateOrganizationServiceResponse_unknown._unrecognized(this._u);

  @_core.override
  UpdateOrganizationServiceResponse_kind get kind => UpdateOrganizationServiceResponse_kind.unknown;
  @_core.override
  _core.bool operator ==(other) => other is UpdateOrganizationServiceResponse_unknown;
  @_core.override
  _core.int get hashCode => 8118964;
  @_core.override
  _core.String toString() => _skir.internal__stringify(this, UpdateOrganizationServiceResponse.serializer);
}

sealed class _UpdateOrganizationServiceResponse_wrapper implements UpdateOrganizationServiceResponse {
  _core.dynamic get value;

  @_core.override
  _core.bool operator ==(other) {
    if (other is! _UpdateOrganizationServiceResponse_wrapper) return false;
    return kind == other.kind && value == other.value;
  }

  @_core.override
  _core.int get hashCode => (kind._ordinal * 31) ^ value.hashCode;

  @_core.override
  _core.String toString() => _skir.internal__stringify(this, UpdateOrganizationServiceResponse.serializer);
}

final class UpdateOrganizationServiceResponse_internalErrorWrapper extends _UpdateOrganizationServiceResponse_wrapper {
  final _lib_kernel_v1_errors.InternalError value;

  UpdateOrganizationServiceResponse_internalErrorWrapper._(this.value);

  @_core.override
  UpdateOrganizationServiceResponse_kind get kind => UpdateOrganizationServiceResponse_kind.internalErrorWrapper;
}

final class UpdateOrganizationServiceResponse_successWrapper extends _UpdateOrganizationServiceResponse_wrapper {
  final _lib_service_v1_service.Service value;

  UpdateOrganizationServiceResponse_successWrapper._(this.value);

  @_core.override
  UpdateOrganizationServiceResponse_kind get kind => UpdateOrganizationServiceResponse_kind.successWrapper;
}

final class UpdateOrganizationServiceResponse_conflictErrorWrapper extends _UpdateOrganizationServiceResponse_wrapper {
  final UpdateOrganizationServiceResponse_ConflictError value;

  UpdateOrganizationServiceResponse_conflictErrorWrapper._(this.value);

  @_core.override
  UpdateOrganizationServiceResponse_kind get kind => UpdateOrganizationServiceResponse_kind.conflictErrorWrapper;
}

final class UpdateOrganizationServiceResponse_serviceNotFoundErrorWrapper extends _UpdateOrganizationServiceResponse_wrapper {
  final UpdateOrganizationServiceResponse_ServiceNotFoundError value;

  UpdateOrganizationServiceResponse_serviceNotFoundErrorWrapper._(this.value);

  @_core.override
  UpdateOrganizationServiceResponse_kind get kind => UpdateOrganizationServiceResponse_kind.serviceNotFoundErrorWrapper;
}

final class UpdateOrganizationServiceResponse_validationErrorWrapper extends _UpdateOrganizationServiceResponse_wrapper {
  final ServiceUpdateValidationError value;

  UpdateOrganizationServiceResponse_validationErrorWrapper._(this.value);

  @_core.override
  UpdateOrganizationServiceResponse_kind get kind => UpdateOrganizationServiceResponse_kind.validationErrorWrapper;
}

final class UpdateOrganizationServiceResponse_invalidRecordIdErrorWrapper extends _UpdateOrganizationServiceResponse_wrapper {
  final _lib_kernel_v1_errors.InvalidRecordIdError value;

  UpdateOrganizationServiceResponse_invalidRecordIdErrorWrapper._(this.value);

  @_core.override
  UpdateOrganizationServiceResponse_kind get kind => UpdateOrganizationServiceResponse_kind.invalidRecordIdErrorWrapper;
}

final _skir.Method<
  WatchOrganizationServicesRequest,
  WatchOrganizationServicesResponse
> watchOrganizationServicesMethod =
  _skir.Method(
    "WatchOrganizationServices",
    820326,
    WatchOrganizationServicesRequest.serializer,
    WatchOrganizationServicesResponse.serializer,
    "",
  );

final _skir.Method<
  UpdateOrganizationServiceRequest,
  UpdateOrganizationServiceResponse
> updateOrganizationServiceMethod =
  _skir.Method(
    "UpdateOrganizationService",
    872501,
    UpdateOrganizationServiceRequest.serializer,
    UpdateOrganizationServiceResponse.serializer,
    "",
  );
