name: widgetbook_workspace
description: "Widgetbook workspace"
publish_to: "none"
version: 0.0.0+1

environment:
  sdk: ">=3.11.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  widgetbook:
  widgetbook_annotation:
  typewriter_panel:
    path: ../
  typewriter_testkit:
    path: ../testkit
  hooks_riverpod: 3.3.1
  flutter_animate:
  faker:
  flutter_hooks:
  iconify_flutter_plus:
  pub_semver:

dependency_overrides:
  riverpod: 3.2.1
  riverpod_annotation: 4.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:
  widgetbook_generator:
  build_runner:
  riverpod_lint:

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: JetBrainsMono
      fonts:
        - asset: assets/fonts/JetBrains_Mono/JetBrainsMono-VariableFont_wght.ttf
        - asset: assets/fonts/JetBrains_Mono/JetBrainsMono-Italic-VariableFont_wght.ttf
          style: italic
    - family: Lilex
      fonts:
        - asset: assets/fonts/Lilex/Lilex-VariableFont_wght.ttf
        - asset: assets/fonts/Lilex/Lilex-Italic-VariableFont_wght.ttf
          style: italic
