apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: api-typewritermc-com
  namespace: typewriter
spec:
  secretName: api-typewritermc-com-tls
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  dnsNames:
    - api.typewritermc.com
