apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: auth-sentinel
  namespace: typewriter
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - api.typewritermc.com
      secretName: api-typewritermc-com-tls
  rules:
    - host: api.typewritermc.com
      http:
        paths:
          - path: /auth/sentinel
            pathType: Exact
            backend:
              service:
                name: auth-sentinel
                port:
                  number: 80
