- op: replace
  path: /spec/target/template/data/ISSUERS
  value: |
    [
      {
        "id": "typewriter-panel",
        "issuer_url": "https://auth.tw.seamlezz.net/application/o/typewriter-panel/",
        "jwks_url": "https://auth.tw.seamlezz.net/application/o/typewriter-panel/jwks/",
        "nats_account_key": "{{ .typewriterAccountPublicKey }}"
      },
      {
        "id": "typewriter-services",
        "issuer_url": "https://auth.tw.seamlezz.net/application/o/typewriter-services/",
        "jwks_url": "https://auth.tw.seamlezz.net/application/o/typewriter-services/jwks/",
        "nats_account_key": "{{ .typewriterAccountPublicKey }}"
      }
    ]
