- op: add
  path: /spec/template/spec/components/0/image
  value: oci.local.seamlezz.net/typewriter/auth-callout:latest
- op: add
  path: /spec/template/spec/components/0/imagePullPolicy
  value: Always
