[versions]
kotlin = "2.4.10"
ksp = "2.3.10"
ktlint = "1.8.0"
ktlint-gradle = "14.2.0"
detekt = "2.0.0-alpha.5"
foojay = "1.0.0"
koin-bom = "4.2.2"
kotlin-logging = "8.0.4"
logback = "1.6.0"
mordant = "3.0.2"
opentelemetry = "1.64.0"
opentelemetry-semconv = "1.43.0"

skir = "1.0.16"
okio = "3.6.0"

nats = "0.9.1"
cryptography = "0.6.0"
surrealdb-server = "3.2.3"
surrealdb-embedded = "3.1.5"
surrealdb-java-sdk = "2.1.2"

kotlin-serialize = "1.11.0"
kotlin-coroutines = "1.11.0"
jline = "4.3.1"
clikt = "5.1.0"
gradle-buildconfig = "6.0.10"

test-balloon = "1.0.1-K2.4.0"
test-balloon-addons = "0.16.0"
kotest = "6.2.3"
mockk = "1.14.11"

[libraries]
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
foojay-resolver = { module = "org.gradle.toolchains:foojay-resolver", version.ref = "foojay" }
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
ksp-gradle-plugin = { module = "com.google.devtools.ksp:symbol-processing-gradle-plugin", version.ref = "ksp" }
ksp-api = { module = "com.google.devtools.ksp:symbol-processing-api", version.ref = "ksp" }
ktlint-gradle-plugin = { module = "org.jlleitschuh.gradle.ktlint:org.jlleitschuh.gradle.ktlint.gradle.plugin", version.ref = "ktlint-gradle" }
detekt-gradle-plugin = { module = "dev.detekt:detekt-gradle-plugin", version.ref = "detekt" }

jline = { module = "org.jline:jline", version.ref = "jline" }
clikt = { module = "com.github.ajalt.clikt:clikt", version.ref = "clikt" }
mordant = { module = "com.github.ajalt.mordant:mordant", version.ref = "mordant" }

kotlin-logging-jvm = { module = "io.github.oshai:kotlin-logging-jvm", version.ref = "kotlin-logging" }
logback = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }

koin-bom = { module = "io.insert-koin:koin-bom", version.ref = "koin-bom" }
koin-core = { module = "io.insert-koin:koin-core" }
koin-test = { module = "io.insert-koin:koin-test", version.ref = "koin-bom" }

test-balloon = { module = "de.infix.testBalloon:testBalloon-framework-core", version.ref = "test-balloon" }
test-balloon-gradle-plugin = { module = "de.infix.testBalloon:de.infix.testBalloon.gradle.plugin", version.ref = "test-balloon" }
test-balloon-kotest-assertions = {module = "de.infix.testBalloon:testBalloon-integration-kotest-assertions", version.ref = "test-balloon"}
test-balloon-data-test = { module = "at.asitplus.testballoon:datatest", version.ref = "test-balloon-addons"}
test-balloon-property-test = { module = "at.asitplus.testballoon:property", version.ref = "test-balloon-addons"}
kotest-assertions = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest" }
kotest-property = { module = "io.kotest:kotest-property", version.ref = "kotest" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }

skir-client = { module = "build.skir:skir-client", version.ref = "skir"}
okio = { module = "com.squareup.okio:okio-jvm", version.ref = "okio" }

nats-core = { module = "io.github.n-hass:natskt-core", version.ref = "nats" }
cryptography-provider-jdk = { module = "dev.whyoleg.cryptography:cryptography-provider-jdk", version.ref = "cryptography" }
surrealdb-java-sdk = { module = "com.surrealdb:surrealdb", version.ref = "surrealdb-java-sdk" }

kotlin-serialize-core = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version.ref = "kotlin-serialize" }
kotlin-serialize-cbor = { module = "org.jetbrains.kotlinx:kotlinx-serialization-cbor", version.ref = "kotlin-serialize" }
kotlin-serialize-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlin-serialize" }

kotlin-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlin-coroutines" }
kotlin-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlin-coroutines" }

opentelemetry-bom = { module = "io.opentelemetry:opentelemetry-bom", version.ref = "opentelemetry" }
opentelemetry-api = { module = "io.opentelemetry:opentelemetry-api" }
opentelemetry-sdk = { module = "io.opentelemetry:opentelemetry-sdk" }
opentelemetry-sdk-testing = { module = "io.opentelemetry:opentelemetry-sdk-testing" }
opentelemetry-kotlin = { module = "io.opentelemetry:opentelemetry-extension-kotlin" }
opentelemetry-exporter-otlp = { module = "io.opentelemetry:opentelemetry-exporter-otlp" }
opentelemetry-semconv = { module = "io.opentelemetry.semconv:opentelemetry-semconv", version.ref = "opentelemetry-semconv" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
foojay-resolver = { id = "org.gradle.toolchains.foojay-resolver-convention", version.ref = "foojay" }

kotlin-serialize = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }

gradle-buildconfig = { id = "com.github.gmazzo.buildconfig", version.ref = "gradle-buildconfig" }

test-balloon-plugin = { id = "de.infix.testBalloon", version.ref = "test-balloon"}


[bundles]
basic-test = ["test-balloon", "test-balloon-kotest-assertions", "kotest-assertions"]
