@file:Suppress("ktlint")

//  ______                        _               _  _  _
//  |  _  \                      | |             | |(_)| |
//  | | | |  ___    _ __    ___  | |_    ___   __| | _ | |_
//  | | | | / _ \  | '_ \  / _ \ | __|  / _ \ / _` || || __|
//  | |/ / | (_) | | | | || (_) || |_  |  __/| (_| || || |_
//  |___/   \___/  |_| |_| \___/  \__|  \___| \__,_||_| \__|
//
// Generated by skir-kotlin-gen
// Home: https://github.com/gepheum/skir-kotlin-gen
//
// To install the Skir client library, add:
//   implementation("build.skir:skir-client:latest.release")
// to your build.gradle.kts file

package skirout.service.v1.status;

import build.skir.internal.MustNameArguments as _MustNameArguments;
import build.skir.internal.UnrecognizedFields as _UnrecognizedFields;
import build.skir.internal.UnrecognizedVariant as _UnrecognizedVariant;

/** Deeply immutable. */
sealed class ServiceBinding private constructor() {
    /** The kind of variant held by a `ServiceBinding`. */
    enum class Kind {
        UNKNOWN,
        BOUND_WRAPPER,
        UNBOUND_WRAPPER,
    }

    class Unknown @kotlin.Deprecated("For internal use", kotlin.ReplaceWith("skirout.service.v1.status.ServiceBinding.UNKNOWN")) internal constructor(
        internal val _kind: Kind,
        internal override val _unrecognized: _UnrecognizedVariant<skirout.service.v1.status.ServiceBinding>?,
    ) : skirout.service.v1.status.ServiceBinding() {
        override val kind get() = _kind;

        override fun equals(other: kotlin.Any?): kotlin.Boolean {
            return other is skirout.service.v1.status.ServiceBinding && other.kind == kind;
        }

        override fun hashCode(): kotlin.Int {
            return kind.ordinal;
        }
    }

    class BoundWrapper private constructor (
        val value: skirout.service.v1.status.ServiceBinding.Bound,
    ) : skirout.service.v1.status.ServiceBinding() {
        constructor(
            value: skirout.service.v1.status.ServiceBinding.Bound_OrMutable,
        ): this(value.toFrozen()) {}

        override val kind get() = Kind.BOUND_WRAPPER;

        override fun equals(other: kotlin.Any?): kotlin.Boolean {
            return other is skirout.service.v1.status.ServiceBinding.BoundWrapper && value == other.value;
        }

        override fun hashCode(): kotlin.Int {
            return this.value.hashCode() + 93927806;
        }
    }

    class UnboundWrapper private constructor (
        val value: skirout.service.v1.status.ServiceBinding.Unbound,
    ) : skirout.service.v1.status.ServiceBinding() {
        constructor(
            value: skirout.service.v1.status.ServiceBinding.Unbound_OrMutable,
        ): this(value.toFrozen()) {}

        override val kind get() = Kind.UNBOUND_WRAPPER;

        override fun equals(other: kotlin.Any?): kotlin.Boolean {
            return other is skirout.service.v1.status.ServiceBinding.UnboundWrapper && value == other.value;
        }

        override fun hashCode(): kotlin.Int {
            return this.value.hashCode() + -293117307;
        }
    }

    internal open val _unrecognized: _UnrecognizedVariant<skirout.service.v1.status.ServiceBinding>? get() = null;

    abstract val kind: Kind;

    override fun toString(): kotlin.String {
        return build.skir.internal.toStringImpl(
            this,
            skirout.service.v1.status.ServiceBinding._serializerImpl,
        )
    }

    companion object {
        /**
         * Constant indicating an unknown [ServiceBinding].
         * Default value for fields of type [ServiceBinding].
         */
        val UNKNOWN = @kotlin.Suppress("DEPRECATION") Unknown(Kind.UNKNOWN, null);

        /** Shortcut for `BoundWrapper(skirout.service.v1.status.ServiceBinding.Bound(...))`. */
        @kotlin.Suppress("UNUSED_PARAMETER")
        fun createBound(
            _mustNameArguments: _MustNameArguments =
                _MustNameArguments,
            organizationId: kotlin.String,
            organizationName: kotlin.String?,
        ) = BoundWrapper(
            skirout.service.v1.status.ServiceBinding.Bound(
                organizationId = organizationId,
                organizationName = organizationName,
            )
        );

        /** Shortcut for `UnboundWrapper(skirout.service.v1.status.ServiceBinding.Unbound(...))`. */
        @kotlin.Suppress("UNUSED_PARAMETER")
        fun createUnbound(
            _mustNameArguments: _MustNameArguments =
                _MustNameArguments,
            registrationToken: kotlin.String?,
        ) = UnboundWrapper(
            skirout.service.v1.status.ServiceBinding.Unbound(
                registrationToken = registrationToken,
            )
        );

        private val _serializerImpl =
            build.skir.internal.EnumSerializer.create<skirout.service.v1.status.ServiceBinding, Unknown>(
                recordId = "service/v1/status.skir:ServiceBinding",
                doc = "",
                getKindOrdinal = { it.kind.ordinal },
                kindCount = Kind.values().size,
                unknownInstance = UNKNOWN,
                wrapUnrecognized = { @kotlin.Suppress("DEPRECATION") Unknown(Kind.UNKNOWN, it) },
                getUnrecognized = { it._unrecognized },
            );

        /** Serializer for [ServiceBinding] instances. */
        val serializer = build.skir.internal.makeSerializer(_serializerImpl);

        /** Describes the [ServiceBinding] type. Provides runtime introspection capabilities. */
        val typeDescriptor get() = _serializerImpl.typeDescriptor;

        init {
            _maybeFinalizeSerializer();
        }

        private var _finalizationCounter = 0;

        private fun _maybeFinalizeSerializer() {
            _finalizationCounter += 1;
            if (_finalizationCounter == 1) {
                _serializerImpl.addWrapperVariant(
                    1,
                    "bound",
                    Kind.BOUND_WRAPPER.ordinal,
                    skirout.service.v1.status.ServiceBinding.Bound.serializer,
                    "",
                    { BoundWrapper(it) },
                    { it.value },
                );
                _serializerImpl.addWrapperVariant(
                    2,
                    "unbound",
                    Kind.UNBOUND_WRAPPER.ordinal,
                    skirout.service.v1.status.ServiceBinding.Unbound.serializer,
                    "",
                    { UnboundWrapper(it) },
                    { it.value },
                );
                _serializerImpl.finalizeEnum();
            }
        }
    }

    sealed interface Bound_OrMutable {
        val organizationId: kotlin.String;
        val organizationName: kotlin.String?;

        fun toFrozen(): skirout.service.v1.status.ServiceBinding.Bound;
    }

    /** Deeply immutable. */
    @kotlin.Suppress("UNUSED_PARAMETER")
    class Bound private constructor(
        override val organizationId: kotlin.String,
        override val organizationName: kotlin.String?,
        private val _unrecognizedFields: _UnrecognizedFields<skirout.service.v1.status.ServiceBinding.Bound>? =
            null,
    ): skirout.service.v1.status.ServiceBinding.Bound_OrMutable {
        constructor(
            _mustNameArguments: _MustNameArguments =
                _MustNameArguments,
            organizationId: kotlin.String,
            organizationName: kotlin.String?,
            _unrecognizedFields: _UnrecognizedFields<skirout.service.v1.status.ServiceBinding.Bound>? =
                null,
        ): this(
            organizationId,
            organizationName,
            _unrecognizedFields,
        ) {}

        @kotlin.Deprecated("Already frozen", kotlin.ReplaceWith("this"))
        override fun toFrozen() = this;

        /** Returns a mutable shallow copy of this instance */
        fun toMutable() = Mutable(
            organizationId = this.organizationId,
            organizationName = this.organizationName,
        );

        /** Returns a shallow copy of this instance with the specified fields replaced. */
        fun copy(
            _mustNameArguments: _MustNameArguments =
                _MustNameArguments,
            organizationId: kotlin.String =
                this.organizationId,
            organizationName: kotlin.String? =
                this.organizationName,
        ) = skirout.service.v1.status.ServiceBinding.Bound(
            organizationId,
            organizationName,
            this._unrecognizedFields,
        );

        @kotlin.Deprecated("No point in creating an exact copy of an immutable object", kotlin.ReplaceWith("this"))
        fun copy() = this;

        override fun equals(other: kotlin.Any?): kotlin.Boolean {
            return this === other || (other is skirout.service.v1.status.ServiceBinding.Bound && this.organizationId == other.organizationId && this.organizationName == other.organizationName);
        }

        override fun hashCode(): kotlin.Int {
            return kotlin.collections.listOf<kotlin.Any?>(this.organizationId, this.organizationName).hashCode();
        }

        override fun toString(): kotlin.String {
            return build.skir.internal.toStringImpl(
                this,
                skirout.service.v1.status.ServiceBinding.Bound.serializerImpl,
            )
        }

        /** Mutable version of [Bound]. */
        class Mutable internal constructor(
            _mustNameArguments: _MustNameArguments =
                _MustNameArguments,
            override var organizationId: kotlin.String =
                "",
            override var organizationName: kotlin.String? =
                null,
            internal var _unrecognizedFields: _UnrecognizedFields<skirout.service.v1.status.ServiceBinding.Bound>? =
                null,
        ): skirout.service.v1.status.ServiceBinding.Bound_OrMutable {
            /** Returns a deeply immutable copy of this instance */
            override fun toFrozen() = skirout.service.v1.status.ServiceBinding.Bound(
                organizationId = this.organizationId,
                organizationName = this.organizationName,
                _unrecognizedFields = this._unrecognizedFields,
            );
        }

        companion object {
            private val default =
                skirout.service.v1.status.ServiceBinding.Bound(
                    "",
                    null,
                );

            /** Returns an instance with all fields set to their default values. */
            fun partial() = default;

            /**
             * Creates a new instance of [Bound].
             * Unlike the constructor, does not require all fields to be specified.
             * Missing fields will be set to their default values.
             */
            fun partial(
                _mustNameArguments: _MustNameArguments =
                    _MustNameArguments,
                organizationId: kotlin.String =
                    "",
                organizationName: kotlin.String? =
                    null,
            ) = skirout.service.v1.status.ServiceBinding.Bound(
                organizationId = organizationId,
                organizationName = organizationName,
                _unrecognizedFields = null,
            );

            private val serializerImpl = build.skir.internal.StructSerializer(
                recordId = "service/v1/status.skir:ServiceBinding.Bound",
                doc = "",
                defaultInstance = default,
                newMutableFn = { it?.toMutable() ?: Mutable() },
                toFrozenFn = { it.toFrozen() },
                getUnrecognizedFields = { it._unrecognizedFields },
                setUnrecognizedFields = { m, u -> m._unrecognizedFields = u },
            );

            /** Serializer for [Bound] instances. */
            val serializer = build.skir.internal.makeSerializer(serializerImpl);

            /** Describes the [Bound] type. Provides runtime introspection capabilities. */
            val typeDescriptor get() = serializerImpl.typeDescriptor;

            init {
                serializerImpl.addField(
                    "organization_id",
                    "organizationId",
                    0,
                    build.skir.Serializers.string,
                    "",
                    { it.organizationId },
                    { mut, v -> mut.organizationId = v },
                );
                serializerImpl.addField(
                    "organization_name",
                    "organizationName",
                    1,
                    build.skir.Serializers.optional(
                        build.skir.Serializers.string,
                    ),
                    "",
                    { it.organizationName },
                    { mut, v -> mut.organizationName = v },
                );
                serializerImpl.finalizeStruct();
            }
        }
    }

    sealed interface Unbound_OrMutable {
        val registrationToken: kotlin.String?;

        fun toFrozen(): skirout.service.v1.status.ServiceBinding.Unbound;
    }

    /** Deeply immutable. */
    @kotlin.Suppress("UNUSED_PARAMETER")
    class Unbound private constructor(
        override val registrationToken: kotlin.String?,
        private val _unrecognizedFields: _UnrecognizedFields<skirout.service.v1.status.ServiceBinding.Unbound>? =
            null,
    ): skirout.service.v1.status.ServiceBinding.Unbound_OrMutable {
        constructor(
            _mustNameArguments: _MustNameArguments =
                _MustNameArguments,
            registrationToken: kotlin.String?,
            _unrecognizedFields: _UnrecognizedFields<skirout.service.v1.status.ServiceBinding.Unbound>? =
                null,
        ): this(
            registrationToken,
            _unrecognizedFields,
        ) {}

        @kotlin.Deprecated("Already frozen", kotlin.ReplaceWith("this"))
        override fun toFrozen() = this;

        /** Returns a mutable shallow copy of this instance */
        fun toMutable() = Mutable(
            registrationToken = this.registrationToken,
        );

        /** Returns a shallow copy of this instance with the specified fields replaced. */
        fun copy(
            _mustNameArguments: _MustNameArguments =
                _MustNameArguments,
            registrationToken: kotlin.String? =
                this.registrationToken,
        ) = skirout.service.v1.status.ServiceBinding.Unbound(
            registrationToken,
            this._unrecognizedFields,
        );

        @kotlin.Deprecated("No point in creating an exact copy of an immutable object", kotlin.ReplaceWith("this"))
        fun copy() = this;

        override fun equals(other: kotlin.Any?): kotlin.Boolean {
            return this === other || (other is skirout.service.v1.status.ServiceBinding.Unbound && this.registrationToken == other.registrationToken);
        }

        override fun hashCode(): kotlin.Int {
            return kotlin.collections.listOf<kotlin.Any?>(this.registrationToken).hashCode();
        }

        override fun toString(): kotlin.String {
            return build.skir.internal.toStringImpl(
                this,
                skirout.service.v1.status.ServiceBinding.Unbound.serializerImpl,
            )
        }

        /** Mutable version of [Unbound]. */
        class Mutable internal constructor(
            _mustNameArguments: _MustNameArguments =
                _MustNameArguments,
            override var registrationToken: kotlin.String? =
                null,
            internal var _unrecognizedFields: _UnrecognizedFields<skirout.service.v1.status.ServiceBinding.Unbound>? =
                null,
        ): skirout.service.v1.status.ServiceBinding.Unbound_OrMutable {
            /** Returns a deeply immutable copy of this instance */
            override fun toFrozen() = skirout.service.v1.status.ServiceBinding.Unbound(
                registrationToken = this.registrationToken,
                _unrecognizedFields = this._unrecognizedFields,
            );
        }

        companion object {
            private val default =
                skirout.service.v1.status.ServiceBinding.Unbound(
                    null,
                );

            /** Returns an instance with all fields set to their default values. */
            fun partial() = default;

            /**
             * Creates a new instance of [Unbound].
             * Unlike the constructor, does not require all fields to be specified.
             * Missing fields will be set to their default values.
             */
            fun partial(
                _mustNameArguments: _MustNameArguments =
                    _MustNameArguments,
                registrationToken: kotlin.String? =
                    null,
            ) = skirout.service.v1.status.ServiceBinding.Unbound(
                registrationToken = registrationToken,
                _unrecognizedFields = null,
            );

            private val serializerImpl = build.skir.internal.StructSerializer(
                recordId = "service/v1/status.skir:ServiceBinding.Unbound",
                doc = "",
                defaultInstance = default,
                newMutableFn = { it?.toMutable() ?: Mutable() },
                toFrozenFn = { it.toFrozen() },
                getUnrecognizedFields = { it._unrecognizedFields },
                setUnrecognizedFields = { m, u -> m._unrecognizedFields = u },
            );

            /** Serializer for [Unbound] instances. */
            val serializer = build.skir.internal.makeSerializer(serializerImpl);

            /** Describes the [Unbound] type. Provides runtime introspection capabilities. */
            val typeDescriptor get() = serializerImpl.typeDescriptor;

            init {
                serializerImpl.addField(
                    "registration_token",
                    "registrationToken",
                    0,
                    build.skir.Serializers.optional(
                        build.skir.Serializers.string,
                    ),
                    "",
                    { it.registrationToken },
                    { mut, v -> mut.registrationToken = v },
                );
                serializerImpl.finalizeStruct();
            }
        }
    }
}

sealed interface GetServiceStatusRequest_OrMutable {
    fun toFrozen(): skirout.service.v1.status.GetServiceStatusRequest;
}

/** Deeply immutable. */
@kotlin.Suppress("UNUSED_PARAMETER")
class GetServiceStatusRequest private constructor(
    private val _unrecognizedFields: _UnrecognizedFields<skirout.service.v1.status.GetServiceStatusRequest>? =
        null,
): skirout.service.v1.status.GetServiceStatusRequest_OrMutable {
    constructor(
        _mustNameArguments: _MustNameArguments =
            _MustNameArguments,
        _unrecognizedFields: _UnrecognizedFields<skirout.service.v1.status.GetServiceStatusRequest>? =
            null,
    ): this(
        _unrecognizedFields,
    ) {}

    @kotlin.Deprecated("Already frozen", kotlin.ReplaceWith("this"))
    override fun toFrozen() = this;

    /** Returns a mutable shallow copy of this instance */
    fun toMutable() = Mutable();

    override fun equals(other: kotlin.Any?): kotlin.Boolean {
        return this === other || (other is skirout.service.v1.status.GetServiceStatusRequest);
    }

    override fun hashCode(): kotlin.Int {
        return kotlin.collections.listOf<kotlin.Any?>().hashCode();
    }

    override fun toString(): kotlin.String {
        return build.skir.internal.toStringImpl(
            this,
            skirout.service.v1.status.GetServiceStatusRequest.serializerImpl,
        )
    }

    /** Mutable version of [GetServiceStatusRequest]. */
    class Mutable internal constructor(
        _mustNameArguments: _MustNameArguments =
            _MustNameArguments,
        internal var _unrecognizedFields: _UnrecognizedFields<skirout.service.v1.status.GetServiceStatusRequest>? =
            null,
    ): skirout.service.v1.status.GetServiceStatusRequest_OrMutable {
        /** Returns a deeply immutable copy of this instance */
        override fun toFrozen() = skirout.service.v1.status.GetServiceStatusRequest(
            _unrecognizedFields = this._unrecognizedFields,
        );
    }

    companion object {
        private val default =
            skirout.service.v1.status.GetServiceStatusRequest();

        /** Returns an instance with all fields set to their default values. */
        fun partial() = default;

        /**
         * Creates a new instance of [GetServiceStatusRequest].
         * Unlike the constructor, does not require all fields to be specified.
         * Missing fields will be set to their default values.
         */
        fun partial(
            _mustNameArguments: _MustNameArguments =
                _MustNameArguments,
        ) = skirout.service.v1.status.GetServiceStatusRequest(
            _unrecognizedFields = null,
        );

        private val serializerImpl = build.skir.internal.StructSerializer(
            recordId = "service/v1/status.skir:GetServiceStatusRequest",
            doc = "",
            defaultInstance = default,
            newMutableFn = { it?.toMutable() ?: Mutable() },
            toFrozenFn = { it.toFrozen() },
            getUnrecognizedFields = { it._unrecognizedFields },
            setUnrecognizedFields = { m, u -> m._unrecognizedFields = u },
        );

        /** Serializer for [GetServiceStatusRequest] instances. */
        val serializer = build.skir.internal.makeSerializer(serializerImpl);

        /** Describes the [GetServiceStatusRequest] type. Provides runtime introspection capabilities. */
        val typeDescriptor get() = serializerImpl.typeDescriptor;

        init {
            serializerImpl.finalizeStruct();
        }
    }
}

/** Deeply immutable. */
sealed class GetServiceStatusResponse private constructor() {
    /** The kind of variant held by a `GetServiceStatusResponse`. */
    enum class Kind {
        UNKNOWN,
        INTERNAL_ERROR_WRAPPER,
        SERVICE_NOT_FOUND_ERROR_WRAPPER,
        STATUS_WRAPPER,
    }

    class Unknown @kotlin.Deprecated("For internal use", kotlin.ReplaceWith("skirout.service.v1.status.GetServiceStatusResponse.UNKNOWN")) internal constructor(
        internal val _kind: Kind,
        internal override val _unrecognized: _UnrecognizedVariant<skirout.service.v1.status.GetServiceStatusResponse>?,
    ) : skirout.service.v1.status.GetServiceStatusResponse() {
        override val kind get() = _kind;

        override fun equals(other: kotlin.Any?): kotlin.Boolean {
            return other is skirout.service.v1.status.GetServiceStatusResponse && other.kind == kind;
        }

        override fun hashCode(): kotlin.Int {
            return kind.ordinal;
        }
    }

    class InternalErrorWrapper private constructor (
        val value: skirout.kernel.v1.errors.InternalError,
    ) : skirout.service.v1.status.GetServiceStatusResponse() {
        constructor(
            value: skirout.kernel.v1.errors.InternalError_OrMutable,
        ): this(value.toFrozen()) {}

        override val kind get() = Kind.INTERNAL_ERROR_WRAPPER;

        override fun equals(other: kotlin.Any?): kotlin.Boolean {
            return other is skirout.service.v1.status.GetServiceStatusResponse.InternalErrorWrapper && value == other.value;
        }

        override fun hashCode(): kotlin.Int {
            return this.value.hashCode() + 778975750;
        }
    }

    class ServiceNotFoundErrorWrapper private constructor (
        val value: skirout.service.v1.status.GetServiceStatusResponse.ServiceNotFoundError,
    ) : skirout.service.v1.status.GetServiceStatusResponse() {
        constructor(
            value: skirout.service.v1.status.GetServiceStatusResponse.ServiceNotFoundError_OrMutable,
        ): this(value.toFrozen()) {}

        override val kind get() = Kind.SERVICE_NOT_FOUND_ERROR_WRAPPER;

        override fun equals(other: kotlin.Any?): kotlin.Boolean {
            return other is skirout.service.v1.status.GetServiceStatusResponse.ServiceNotFoundErrorWrapper && value == other.value;
        }

        override fun hashCode(): kotlin.Int {
            return this.value.hashCode() + 532683285;
        }
    }

    class StatusWrapper private constructor (
        val value: skirout.service.v1.status.GetServiceStatusResponse.Status,
    ) : skirout.service.v1.status.GetServiceStatusResponse() {
        constructor(
            value: skirout.service.v1.status.GetServiceStatusResponse.Status_OrMutable,
        ): this(value.toFrozen()) {}

        override val kind get() = Kind.STATUS_WRAPPER;

        override fun equals(other: kotlin.Any?): kotlin.Boolean {
            return other is skirout.service.v1.status.GetServiceStatusResponse.StatusWrapper && value == other.value;
        }

        override fun hashCode(): kotlin.Int {
            return this.value.hashCode() + -892481550;
        }
    }

    internal open val _unrecognized: _UnrecognizedVariant<skirout.service.v1.status.GetServiceStatusResponse>? get() = null;

    abstract val kind: Kind;

    override fun toString(): kotlin.String {
        return build.skir.internal.toStringImpl(
            this,
            skirout.service.v1.status.GetServiceStatusResponse._serializerImpl,
        )
    }

    companion object {
        /**
         * Constant indicating an unknown [GetServiceStatusResponse].
         * Default value for fields of type [GetServiceStatusResponse].
         */
        val UNKNOWN = @kotlin.Suppress("DEPRECATION") Unknown(Kind.UNKNOWN, null);

        /** Shortcut for `InternalErrorWrapper(skirout.kernel.v1.errors.InternalError(...))`. */
        @kotlin.Suppress("UNUSED_PARAMETER")
        fun createInternalError(
            _mustNameArguments: _MustNameArguments =
                _MustNameArguments,
        ) = InternalErrorWrapper(
            skirout.kernel.v1.errors.InternalError()
        );

        /** Shortcut for `ServiceNotFoundErrorWrapper(skirout.service.v1.status.GetServiceStatusResponse.ServiceNotFoundError(...))`. */
        @kotlin.Suppress("UNUSED_PARAMETER")
        fun createServiceNotFoundError(
            _mustNameArguments: _MustNameArguments =
                _MustNameArguments,
        ) = ServiceNotFoundErrorWrapper(
            skirout.service.v1.status.GetServiceStatusResponse.ServiceNotFoundError()
        );

        /** Shortcut for `StatusWrapper(skirout.service.v1.status.GetServiceStatusResponse.Status(...))`. */
        @kotlin.Suppress("UNUSED_PARAMETER")
        fun createStatus(
            _mustNameArguments: _MustNameArguments =
                _MustNameArguments,
            binding: skirout.service.v1.status.ServiceBinding,
        ) = StatusWrapper(
            skirout.service.v1.status.GetServiceStatusResponse.Status(
                binding = binding,
            )
        );

        private val _serializerImpl =
            build.skir.internal.EnumSerializer.create<skirout.service.v1.status.GetServiceStatusResponse, Unknown>(
                recordId = "service/v1/status.skir:GetServiceStatusResponse",
                doc = "",
                getKindOrdinal = { it.kind.ordinal },
                kindCount = Kind.values().size,
                unknownInstance = UNKNOWN,
                wrapUnrecognized = { @kotlin.Suppress("DEPRECATION") Unknown(Kind.UNKNOWN, it) },
                getUnrecognized = { it._unrecognized },
            );

        /** Serializer for [GetServiceStatusResponse] instances. */
        val serializer = build.skir.internal.makeSerializer(_serializerImpl);

        /** Describes the [GetServiceStatusResponse] type. Provides runtime introspection capabilities. */
        val typeDescriptor get() = _serializerImpl.typeDescriptor;

        init {
            _maybeFinalizeSerializer();
        }

        private var _finalizationCounter = 0;

        private fun _maybeFinalizeSerializer() {
            _finalizationCounter += 1;
            if (_finalizationCounter == 1) {
                _serializerImpl.addWrapperVariant(
                    1,
                    "internal_error",
                    Kind.INTERNAL_ERROR_WRAPPER.ordinal,
                    skirout.kernel.v1.errors.InternalError.serializer,
                    "",
                    { InternalErrorWrapper(it) },
                    { it.value },
                );
                _serializerImpl.addWrapperVariant(
                    2,
                    "service_not_found_error",
                    Kind.SERVICE_NOT_FOUND_ERROR_WRAPPER.ordinal,
                    skirout.service.v1.status.GetServiceStatusResponse.ServiceNotFoundError.serializer,
                    "",
                    { ServiceNotFoundErrorWrapper(it) },
                    { it.value },
                );
                _serializerImpl.addWrapperVariant(
                    3,
                    "status",
                    Kind.STATUS_WRAPPER.ordinal,
                    skirout.service.v1.status.GetServiceStatusResponse.Status.serializer,
                    "",
                    { StatusWrapper(it) },
                    { it.value },
                );
                _serializerImpl.finalizeEnum();
            }
        }
    }

    sealed interface ServiceNotFoundError_OrMutable {
        fun toFrozen(): skirout.service.v1.status.GetServiceStatusResponse.ServiceNotFoundError;
    }

    /** Deeply immutable. */
    @kotlin.Suppress("UNUSED_PARAMETER")
    class ServiceNotFoundError private constructor(
        private val _unrecognizedFields: _UnrecognizedFields<skirout.service.v1.status.GetServiceStatusResponse.ServiceNotFoundError>? =
            null,
    ): skirout.service.v1.status.GetServiceStatusResponse.ServiceNotFoundError_OrMutable {
        constructor(
            _mustNameArguments: _MustNameArguments =
                _MustNameArguments,
            _unrecognizedFields: _UnrecognizedFields<skirout.service.v1.status.GetServiceStatusResponse.ServiceNotFoundError>? =
                null,
        ): this(
            _unrecognizedFields,
        ) {}

        @kotlin.Deprecated("Already frozen", kotlin.ReplaceWith("this"))
        override fun toFrozen() = this;

        /** Returns a mutable shallow copy of this instance */
        fun toMutable() = Mutable();

        override fun equals(other: kotlin.Any?): kotlin.Boolean {
            return this === other || (other is skirout.service.v1.status.GetServiceStatusResponse.ServiceNotFoundError);
        }

        override fun hashCode(): kotlin.Int {
            return kotlin.collections.listOf<kotlin.Any?>().hashCode();
        }

        override fun toString(): kotlin.String {
            return build.skir.internal.toStringImpl(
                this,
                skirout.service.v1.status.GetServiceStatusResponse.ServiceNotFoundError.serializerImpl,
            )
        }

        /** Mutable version of [ServiceNotFoundError]. */
        class Mutable internal constructor(
            _mustNameArguments: _MustNameArguments =
                _MustNameArguments,
            internal var _unrecognizedFields: _UnrecognizedFields<skirout.service.v1.status.GetServiceStatusResponse.ServiceNotFoundError>? =
                null,
        ): skirout.service.v1.status.GetServiceStatusResponse.ServiceNotFoundError_OrMutable {
            /** Returns a deeply immutable copy of this instance */
            override fun toFrozen() = skirout.service.v1.status.GetServiceStatusResponse.ServiceNotFoundError(
                _unrecognizedFields = this._unrecognizedFields,
            );
        }

        companion object {
            private val default =
                skirout.service.v1.status.GetServiceStatusResponse.ServiceNotFoundError();

            /** Returns an instance with all fields set to their default values. */
            fun partial() = default;

            /**
             * Creates a new instance of [ServiceNotFoundError].
             * Unlike the constructor, does not require all fields to be specified.
             * Missing fields will be set to their default values.
             */
            fun partial(
                _mustNameArguments: _MustNameArguments =
                    _MustNameArguments,
            ) = skirout.service.v1.status.GetServiceStatusResponse.ServiceNotFoundError(
                _unrecognizedFields = null,
            );

            private val serializerImpl = build.skir.internal.StructSerializer(
                recordId = "service/v1/status.skir:GetServiceStatusResponse.ServiceNotFoundError",
                doc = "",
                defaultInstance = default,
                newMutableFn = { it?.toMutable() ?: Mutable() },
                toFrozenFn = { it.toFrozen() },
                getUnrecognizedFields = { it._unrecognizedFields },
                setUnrecognizedFields = { m, u -> m._unrecognizedFields = u },
            );

            /** Serializer for [ServiceNotFoundError] instances. */
            val serializer = build.skir.internal.makeSerializer(serializerImpl);

            /** Describes the [ServiceNotFoundError] type. Provides runtime introspection capabilities. */
            val typeDescriptor get() = serializerImpl.typeDescriptor;

            init {
                serializerImpl.finalizeStruct();
            }
        }
    }

    sealed interface Status_OrMutable {
        val binding: skirout.service.v1.status.ServiceBinding;

        fun toFrozen(): skirout.service.v1.status.GetServiceStatusResponse.Status;
    }

    /** Deeply immutable. */
    @kotlin.Suppress("UNUSED_PARAMETER")
    class Status private constructor(
        override val binding: skirout.service.v1.status.ServiceBinding,
        private val _unrecognizedFields: _UnrecognizedFields<skirout.service.v1.status.GetServiceStatusResponse.Status>? =
            null,
    ): skirout.service.v1.status.GetServiceStatusResponse.Status_OrMutable {
        constructor(
            _mustNameArguments: _MustNameArguments =
                _MustNameArguments,
            binding: skirout.service.v1.status.ServiceBinding,
            _unrecognizedFields: _UnrecognizedFields<skirout.service.v1.status.GetServiceStatusResponse.Status>? =
                null,
        ): this(
            binding,
            _unrecognizedFields,
        ) {}

        @kotlin.Deprecated("Already frozen", kotlin.ReplaceWith("this"))
        override fun toFrozen() = this;

        /** Returns a mutable shallow copy of this instance */
        fun toMutable() = Mutable(
            binding = this.binding,
        );

        /** Returns a shallow copy of this instance with the specified fields replaced. */
        fun copy(
            _mustNameArguments: _MustNameArguments =
                _MustNameArguments,
            binding: skirout.service.v1.status.ServiceBinding =
                this.binding,
        ) = skirout.service.v1.status.GetServiceStatusResponse.Status(
            binding,
            this._unrecognizedFields,
        );

        @kotlin.Deprecated("No point in creating an exact copy of an immutable object", kotlin.ReplaceWith("this"))
        fun copy() = this;

        override fun equals(other: kotlin.Any?): kotlin.Boolean {
            return this === other || (other is skirout.service.v1.status.GetServiceStatusResponse.Status && this.binding == other.binding);
        }

        override fun hashCode(): kotlin.Int {
            return kotlin.collections.listOf<kotlin.Any?>(this.binding).hashCode();
        }

        override fun toString(): kotlin.String {
            return build.skir.internal.toStringImpl(
                this,
                skirout.service.v1.status.GetServiceStatusResponse.Status.serializerImpl,
            )
        }

        /** Mutable version of [Status]. */
        class Mutable internal constructor(
            _mustNameArguments: _MustNameArguments =
                _MustNameArguments,
            override var binding: skirout.service.v1.status.ServiceBinding =
                skirout.service.v1.status.ServiceBinding.UNKNOWN,
            internal var _unrecognizedFields: _UnrecognizedFields<skirout.service.v1.status.GetServiceStatusResponse.Status>? =
                null,
        ): skirout.service.v1.status.GetServiceStatusResponse.Status_OrMutable {
            /** Returns a deeply immutable copy of this instance */
            override fun toFrozen() = skirout.service.v1.status.GetServiceStatusResponse.Status(
                binding = this.binding,
                _unrecognizedFields = this._unrecognizedFields,
            );
        }

        companion object {
            private val default =
                skirout.service.v1.status.GetServiceStatusResponse.Status(
                    skirout.service.v1.status.ServiceBinding.UNKNOWN,
                );

            /** Returns an instance with all fields set to their default values. */
            fun partial() = default;

            /**
             * Creates a new instance of [Status].
             * Unlike the constructor, does not require all fields to be specified.
             * Missing fields will be set to their default values.
             */
            fun partial(
                _mustNameArguments: _MustNameArguments =
                    _MustNameArguments,
                binding: skirout.service.v1.status.ServiceBinding =
                    skirout.service.v1.status.ServiceBinding.UNKNOWN,
            ) = skirout.service.v1.status.GetServiceStatusResponse.Status(
                binding = binding,
                _unrecognizedFields = null,
            );

            private val serializerImpl = build.skir.internal.StructSerializer(
                recordId = "service/v1/status.skir:GetServiceStatusResponse.Status",
                doc = "",
                defaultInstance = default,
                newMutableFn = { it?.toMutable() ?: Mutable() },
                toFrozenFn = { it.toFrozen() },
                getUnrecognizedFields = { it._unrecognizedFields },
                setUnrecognizedFields = { m, u -> m._unrecognizedFields = u },
            );

            /** Serializer for [Status] instances. */
            val serializer = build.skir.internal.makeSerializer(serializerImpl);

            /** Describes the [Status] type. Provides runtime introspection capabilities. */
            val typeDescriptor get() = serializerImpl.typeDescriptor;

            init {
                serializerImpl.addField(
                    "binding",
                    "binding",
                    0,
                    skirout.service.v1.status.ServiceBinding.serializer,
                    "",
                    { it.binding },
                    { mut, v -> mut.binding = v },
                );
                serializerImpl.finalizeStruct();
            }
        }
    }
}

val GetServiceStatus: build.skir.service.Method<
    skirout.service.v1.status.GetServiceStatusRequest,
    skirout.service.v1.status.GetServiceStatusResponse,
> by kotlin.lazy {
    build.skir.service.Method(
        "GetServiceStatus",
        955610,
        skirout.service.v1.status.GetServiceStatusRequest.serializer,
        skirout.service.v1.status.GetServiceStatusResponse.serializer,
        "",
    )
}
