name: typewriter_testkit
description: "Shared testing utilities and mocks for Typewriter Panel editors and Widgetbook"
publish_to: "none"
version: 0.0.0

environment:
  sdk: ">=3.11.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  typewriter_panel:
    path: ../
  hooks_riverpod: 3.3.1
  riverpod_annotation: 4.0.2
  flutter_animate:
  faker:
  pub_semver:
  collection:
  iconify_flutter_plus: ^1.0.4
  riverpod: 3.2.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  flutter_lints:
  riverpod_generator:
  riverpod_lint:

flutter:
  uses-material-design: true
