apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
  - ingress.yaml
  - middleware-cors.yaml
patches:
  - path: workloaddeployment-patch.yaml
    target:
      kind: WorkloadDeployment
      name: auth-sentinel
