name: typewriter-panel
title: Typewriter
version: 1000.0.0
summary: Configure and manage Typewriter
description: Configure interactive stories, quests, and experiences with Typewriter.

confinement: strict
base: core22
grade: stable

slots:
  dbus-typewriter:
    interface: dbus
    bus: session
    name: com.typewritermc.panel

apps:
  typewriter-panel:
    command: typewriter_panel
    extensions: [gnome]
    plugs:
    - network
    slots:
      - dbus-typewriter
parts:
  typewriter-panel:
    source: .
    plugin: flutter
    flutter-target: lib/main.dart
