apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: service-identity-secrets
  namespace: typewriter
spec:
  refreshPolicy: Periodic
  refreshInterval: 30m
  secretStoreRef:
    name: openbao-backend
    kind: ClusterSecretStore
  target:
    name: service-identity-secrets
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        AUTHENTIK_URL: "{{ .url }}"
        AUTHENTIK_TOKEN: "{{ .token }}"
  data:
    - secretKey: url
      remoteRef:
        key: authentik/service-identity
        property: url
    - secretKey: token
      remoteRef:
        key: authentik/service-identity
        property: token
