apiVersion: runtime.wasmcloud.dev/v1alpha1
kind: WorkloadDeployment
metadata:
  name: service-registration
  namespace: typewriter
spec:
  replicas: 1
  template:
    spec:
      environment: wasmcloud
      hostSelector:
        hostgroup: default
      components:
        - name: service-registration
      hostInterfaces:
        - namespace: wasi
          package: otel
          version: "0.2.0-rc.2"
          interfaces:
            - tracing
        - namespace: wasmcloud
          package: nats
          version: "0.1.0"
          interfaces:
            - core-handler
            - core
            - jetstream
          config:
            core-subscriptions: service.*.status:typewriter.service-registration,service.*.messaging.scope:typewriter.service-registration,typewriter.from.service.*.status:typewriter.service-registration,typewriter.from.service.*.messaging.scope:typewriter.service-registration,typewriter.from.service.*.heartbeat:typewriter.service-registration,typewriter.from.service.*.shutdown:typewriter.service-registration,typewriter.from.user.*.organization.*.services.*:typewriter.service-registration,typewriter.from.user.*.organization.*.topology.*:typewriter.service-registration,typewriter.from.service.*.execution.*:typewriter.service-registration
        - namespace: seamlezz
          package: surrealdb
          version: "0.4.0"
          interfaces:
            - call
          secretFrom:
            - name: surrealdb-credentials-service-registration
