apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: auth-sentinel-secrets
  namespace: typewriter
spec:
  refreshPolicy: Periodic
  refreshInterval: 720h
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao-nats-backend
  target:
    name: auth-sentinel-secrets
    creationPolicy: Owner
  data:
    - secretKey: NATS_SENTINEL_CREDS
      remoteRef:
        key: nats/ephemeral-creds/operator/WASMCLOUD/sentinel/auth
        property: creds
