apiVersion: runtime.wasmcloud.dev/v1alpha1
kind: WorkloadDeployment
metadata:
  name: auth-sentinel
  namespace: typewriter
spec:
  replicas: 1
  template:
    spec:
      environment: wasmcloud
      hostSelector:
        hostgroup: default
      kubernetes:
        service:
          name: auth-sentinel
      components:
        - name: auth-sentinel
          localResources:
            environment:
              secretFrom:
                - name: auth-sentinel-secrets
      hostInterfaces:
        - namespace: wasi
          package: otel
          version: "0.2.0-rc.2"
          interfaces:
            - tracing
        - namespace: wasi
          package: http
          interfaces:
            - incoming-handler
          config:
            host: PLACEHOLDER_API_HOST
