syntax = "proto3";

package typewriter.api.v1;

import "models/book.proto";
import "models/common.proto";

message ListBooksRequest {}

message ListBooksResponse {
  oneof result {
    ListBooks books = 1;
    typewriter.models.v1.Error error = 2;
  }
}

message ListBooks {
  repeated typewriter.models.v1.Book books = 1;
}

message GetBookRequest {
  string book_id = 1;
}

message GetBookResponse {
  oneof result {
    typewriter.models.v1.Book book = 1;
    typewriter.models.v1.Error error = 2;
  }
}

message UpdateBookRequest {
  typewriter.models.v1.Book book = 1;
}

message UpdateBookResponse {
  oneof result {
    typewriter.models.v1.Book book = 1;
    typewriter.models.v1.Error error = 2;
  }
}

message CreatePageRequest {
  string book_id = 1;
  optional string name = 2;
  typewriter.models.v1.PageType type = 3;
  optional string chapter = 4;
  optional int32 priority = 5;
}

message CreatePageResponse {
  oneof result {
    string page_id = 1;
    typewriter.models.v1.Error error = 2;
  }
}

message DeletePageRequest {
  string page_id = 1;
}

message DeletePageResponse {
  oneof result {
    bool success = 1;
    typewriter.models.v1.Error error = 2;
  }
}

message ChangePagesChaptersRequest {
  string book_id = 1;
  string old_chapter = 2;
  string new_chapter = 3;
}

message ChangePagesChaptersResponse {
  oneof result {
    bool success = 1;
    typewriter.models.v1.Error error = 2;
  }
}

message CreateBookRequest {
  optional string title = 1;
  optional string icon = 2;
  typewriter.models.v1.Color color = 3;
  repeated string tag_ids = 4;
}

message CreateBookResponse {
  oneof result {
    typewriter.models.v1.Book book = 1;
    typewriter.models.v1.Error error = 2;
  }
}
