syntax = "proto3";

package typewriter.api.v1;

import "models/organization.proto";
import "models/common.proto";


message ListOrganizationsRequest {}

message ListOrganizationsResponse {
  repeated typewriter.models.v1.OrganizationData organizations = 1;
}

message CreateOrganizationRequest {
  string name = 1;
  string icon_url = 2;
}

message CreateOrganizationResponse {
  oneof result {
    typewriter.models.v1.OrganizationData organization = 1;
    typewriter.models.v1.Error error = 2;
  }
}

