syntax = "proto3";

package typewriter.api.v1;

import "models/book.proto";
import "models/common.proto";

message ListTagsRequest {}

message ListTagsResponse {
  oneof result {
    ListTags tags = 1;
    typewriter.models.v1.Error error = 2;
  }
}

message ListTags {
  repeated typewriter.models.v1.Tag tags = 1;
}

message GetTagRequest {
  string id = 1;
}

message GetTagResponse {
  oneof result {
    typewriter.models.v1.Tag tag = 1;
    typewriter.models.v1.Error error = 2;
  }
}

message CreateTagRequest {
  string name = 1;
  typewriter.models.v1.Color color = 2;
  repeated string parent_ids = 3;
  typewriter.models.v1.Placement placement = 4;
}

message CreateTagResponse {
  oneof result {
    typewriter.models.v1.Tag tag = 1;
    typewriter.models.v1.Error error = 2;
  }
}

message UpdateTagRequest {
  typewriter.models.v1.Tag tag = 1;
}

message UpdateTagResponse {
  oneof result {
    typewriter.models.v1.Tag tag = 1;
    typewriter.models.v1.Error error = 2;
  }
}

message DeleteTagRequest {
  string id = 1;
}

message DeleteTagResponse {
  oneof result {
    bool success = 1;
    typewriter.models.v1.Error error = 2;
  }
}

message MoveTagRequest {
  string id = 1;
  int32 x = 2;
  int32 y = 3;
}

message MoveTagResponse {
  oneof result {
    bool success = 1;
    typewriter.models.v1.Error error = 2;
  }
}

message ResizeTagRequest {
  string id = 1;
  int32 width = 2;
  int32 height = 3;
}

message ResizeTagResponse {
  oneof result {
    bool success = 1;
    typewriter.models.v1.Error error = 2;
  }
}
