apiVersion: runtime.wasmcloud.dev/v1alpha1
kind: WorkloadDeployment
metadata:
  name: providers-surrealdb-component
  namespace: wasmcloud
spec:
  replicas: 1
  template:
    spec:
      hostSelector:
        hostgroup: default
      components:
        - name: providers-surrealdb-component
          image: oci.seamlezz.test/wasmcloud/providers-surrealdb-component:0.1.0
          imagePullSecret:
            name: harbor-registry-credentials
      hostInterfaces:
        - namespace: wasi
          package: http
          interfaces:
            - incoming-handler
          config:
            host: api.seamlezz.test
        - namespace: seamlezz
          package: surrealdb
          interfaces:
            - call
