[package]
name = "organizations-component"
edition = "2021"
version = "0.1.0"

[workspace]

[lib]
crate-type = ["cdylib"]

[dependencies]
wit-bindgen = "0.41"
serde_cbor = "0.11"
serde = { version = "1", features = ["derive"] }
surrealdb-component = { path = "../../providers/surrealdb/surrealdb-component" }
wasmcloud-component = "0.2"
wasmcloud-utils = { path = "../../wasmcloud-utils" }
prost = "0.13"
prost-types = "0.13"
chrono = { version = "0.4", features = ["serde"] }
uuid = { version = "1.0", features = ["v4"] }

[build-dependencies]
prost-build = "0.13"
