package seamlezz:auth-callout@0.1.0;

world auth-callout {
  import wasi:http/outgoing-handler@0.2.2;
  import wasmcloud:nats/core@0.1.0;
  import wasmcloud:nats/jetstream@0.1.0;

  export wasmcloud:nats/core-handler@0.1.0;
}