syntax = "proto3";

package typewriter.models.v1;

import "models/common.proto";

message Book {
  string book_id = 1;
  optional string title = 2;
  optional string icon = 3;
  Color color = 4;
  repeated string tagIds = 5;
}

message Tag {
  string tag_id = 1;
  optional string name = 2;
  Color color = 3;
  repeated string parentIds = 4;
  Placement placement = 5;
}

message Placement {
  optional int32 x = 1;
  optional int32 y = 2;
  optional int32 width = 3;
  optional int32 height = 4;
}

message Page {
  string page_id = 1;
  string book_id = 2;
  optional string name = 3;
  PageType type = 4;
  optional string chapter = 5;
  optional int32 priority = 6;
}

enum PageType {
  PAGE_TYPE_SEQUENCE = 0;
  PAGE_TYPE_STATIC = 1;
  PAGE_TYPE_SCENE = 2;
  PAGE_TYPE_MANIFEST = 3;
}
