apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - secrets/artifact-keeper-pull-secret.enc.yaml
  - ../../access/auth-callout/deploy/local
  - ../../access/auth-typewriter-permissions/deploy/local
