apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../access/auth-callout/deploy/local
  - ../../access/auth-sentinel/deploy/local
  - ../../access/auth-typewriter-permissions/deploy/local
  - ../../organization/user-organization/deploy/local
  - ../../organization/organization-members/deploy/local
  - ../../organization/organization-roles/deploy/local
  - ../../service/identity/deploy/local
  - ../../service/registration/deploy/local
