apiVersion: surrealdb.seamlezz.com/v1alpha1
kind: SurrealDBCredential
metadata:
  name: realm-runtime
  namespace: typewriter
spec:
  policyRef:
    name: typewriter
  level: Database
  database: realm
  roles:
    - OWNER
  targetSecret:
    name: surrealdb-credentials-realm-runtime
