name: Build Paper Engine
description: "Builds the plugin and runs tests"

runs:
  using: "composite"
  steps:
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "beta"
      - name: Get Flutter dependencies
        run: flutter pub get
        shell: bash
        working-directory: ./app
      - name: Run Lint
        run: flutter analyze
        shell: bash
        working-directory: ./app
      - name: Run tests
        run: flutter test
        shell: bash
        working-directory: ./app
      - name: Build web app
        run: flutter build web --release
        shell: bash
        working-directory: ./app
      - name: Test Paper Engine
        uses: gradle/gradle-build-action@v2
        with:
          arguments: engine-paper:test --scan
          build-root-directory: ./engine
      - name: Build Plugin
        uses: gradle/gradle-build-action@v2
        with:
          arguments: engine-paper:buildRelease --scan
          build-root-directory: ./engine

