#![allow(nonstandard_style)]

//  ______                        _               _  _  _
//  |  _  \                      | |             | |(_)| |
//  | | | |  ___    _ __    ___  | |_    ___   __| | _ | |_
//  | | | | / _ \  | '_ \  / _ \ | __|  / _ \ / _` || || __|
//  | |/ / | (_) | | | | || (_) || |_  |  __/| (_| || || |_
//  |___/   \___/  |_| |_| \___/  \__|  \___| \__,_||_| \__|
//
// Generated by skir-rust-gen
// Home: https://github.com/gepheum/skir-rust-gen
//
// To install the Skir client library, run:
//   cargo add skir-client

// ==============================================================================
// struct CompilationProjectionId
// ==============================================================================

#[derive(Clone, Debug, PartialEq, Default)]
pub struct CompilationProjectionId {
    pub value: String,
    /// Set this to None when you're creating a struct.
    pub _unrecognized: Option<crate::skir_client::UnrecognizedFields<CompilationProjectionId>>,
}

impl CompilationProjectionId {
    pub fn default_ref() -> &'static CompilationProjectionId {
        static D: std::sync::LazyLock<CompilationProjectionId> = std::sync::LazyLock::new(CompilationProjectionId::default);
        &D
    }
}

impl CompilationProjectionId {
    fn _adapter() -> &'static crate::skir_client::internal::StructAdapter<CompilationProjectionId> {
        static ADAPTER: std::sync::LazyLock<crate::skir_client::internal::StructAdapter<CompilationProjectionId>> =
            std::sync::LazyLock::new(|| {
                crate::skir_client::internal::StructAdapter::new(
                    "editor/v1/compiled_content.skir",
                    "CompilationProjectionId",
                    "",
                    |x: &CompilationProjectionId| &x._unrecognized,
                    |x: &mut CompilationProjectionId, u| x._unrecognized = u,
                )
            });
        &*ADAPTER
    }
    pub fn serializer() -> crate::skir_client::Serializer<CompilationProjectionId> {
        initialize_module_serializers();
        crate::skir_client::internal::struct_serializer_from_static(CompilationProjectionId::_adapter())
    }
}

// ==============================================================================
// struct CompilationRoot
// ==============================================================================

#[derive(Clone, Debug, PartialEq, Default)]
pub struct CompilationRoot {
    pub projection: CompilationProjectionId,
    pub resource: crate::skirout::base::editor::v1::type_catalog::ResourceId,
    /// Set this to None when you're creating a struct.
    pub _unrecognized: Option<crate::skir_client::UnrecognizedFields<CompilationRoot>>,
}

impl CompilationRoot {
    pub fn default_ref() -> &'static CompilationRoot {
        static D: std::sync::LazyLock<CompilationRoot> = std::sync::LazyLock::new(CompilationRoot::default);
        &D
    }
}

impl CompilationRoot {
    fn _adapter() -> &'static crate::skir_client::internal::StructAdapter<CompilationRoot> {
        static ADAPTER: std::sync::LazyLock<crate::skir_client::internal::StructAdapter<CompilationRoot>> =
            std::sync::LazyLock::new(|| {
                crate::skir_client::internal::StructAdapter::new(
                    "editor/v1/compiled_content.skir",
                    "CompilationRoot",
                    "",
                    |x: &CompilationRoot| &x._unrecognized,
                    |x: &mut CompilationRoot, u| x._unrecognized = u,
                )
            });
        &*ADAPTER
    }
    pub fn serializer() -> crate::skir_client::Serializer<CompilationRoot> {
        initialize_module_serializers();
        crate::skir_client::internal::struct_serializer_from_static(CompilationRoot::_adapter())
    }
}

// ==============================================================================
// struct CompiledBlobPointer
// ==============================================================================

#[derive(Clone, Debug, PartialEq, Default)]
pub struct CompiledBlobPointer {
    pub digest: String,
    pub size: i64,
    /// Set this to None when you're creating a struct.
    pub _unrecognized: Option<crate::skir_client::UnrecognizedFields<CompiledBlobPointer>>,
}

impl CompiledBlobPointer {
    pub fn default_ref() -> &'static CompiledBlobPointer {
        static D: std::sync::LazyLock<CompiledBlobPointer> = std::sync::LazyLock::new(CompiledBlobPointer::default);
        &D
    }
}

impl CompiledBlobPointer {
    fn _adapter() -> &'static crate::skir_client::internal::StructAdapter<CompiledBlobPointer> {
        static ADAPTER: std::sync::LazyLock<crate::skir_client::internal::StructAdapter<CompiledBlobPointer>> =
            std::sync::LazyLock::new(|| {
                crate::skir_client::internal::StructAdapter::new(
                    "editor/v1/compiled_content.skir",
                    "CompiledBlobPointer",
                    "",
                    |x: &CompiledBlobPointer| &x._unrecognized,
                    |x: &mut CompiledBlobPointer, u| x._unrecognized = u,
                )
            });
        &*ADAPTER
    }
    pub fn serializer() -> crate::skir_client::Serializer<CompiledBlobPointer> {
        initialize_module_serializers();
        crate::skir_client::internal::struct_serializer_from_static(CompiledBlobPointer::_adapter())
    }
}

// ==============================================================================
// struct CompiledArtifactPointer
// ==============================================================================

#[derive(Clone, Debug, PartialEq, Default)]
pub struct CompiledArtifactPointer {
    pub semantic_digest: String,
    pub blob: CompiledBlobPointer,
    /// Set this to None when you're creating a struct.
    pub _unrecognized: Option<crate::skir_client::UnrecognizedFields<CompiledArtifactPointer>>,
}

impl CompiledArtifactPointer {
    pub fn default_ref() -> &'static CompiledArtifactPointer {
        static D: std::sync::LazyLock<CompiledArtifactPointer> = std::sync::LazyLock::new(CompiledArtifactPointer::default);
        &D
    }
}

impl CompiledArtifactPointer {
    fn _adapter() -> &'static crate::skir_client::internal::StructAdapter<CompiledArtifactPointer> {
        static ADAPTER: std::sync::LazyLock<crate::skir_client::internal::StructAdapter<CompiledArtifactPointer>> =
            std::sync::LazyLock::new(|| {
                crate::skir_client::internal::StructAdapter::new(
                    "editor/v1/compiled_content.skir",
                    "CompiledArtifactPointer",
                    "",
                    |x: &CompiledArtifactPointer| &x._unrecognized,
                    |x: &mut CompiledArtifactPointer, u| x._unrecognized = u,
                )
            });
        &*ADAPTER
    }
    pub fn serializer() -> crate::skir_client::Serializer<CompiledArtifactPointer> {
        initialize_module_serializers();
        crate::skir_client::internal::struct_serializer_from_static(CompiledArtifactPointer::_adapter())
    }
}

// ==============================================================================
// struct CompiledContentActivation
// ==============================================================================

#[derive(Clone, Debug, PartialEq, Default)]
pub struct CompiledContentActivation {
    pub activation_revision: i64,
    pub manifest_digest: String,
    pub manifest: CompiledBlobPointer,
    pub artifacts: Vec<CompiledArtifactPointer>,
    /// Set this to None when you're creating a struct.
    pub _unrecognized: Option<crate::skir_client::UnrecognizedFields<CompiledContentActivation>>,
}

impl CompiledContentActivation {
    pub fn default_ref() -> &'static CompiledContentActivation {
        static D: std::sync::LazyLock<CompiledContentActivation> = std::sync::LazyLock::new(CompiledContentActivation::default);
        &D
    }
}

impl CompiledContentActivation {
    fn _adapter() -> &'static crate::skir_client::internal::StructAdapter<CompiledContentActivation> {
        static ADAPTER: std::sync::LazyLock<crate::skir_client::internal::StructAdapter<CompiledContentActivation>> =
            std::sync::LazyLock::new(|| {
                crate::skir_client::internal::StructAdapter::new(
                    "editor/v1/compiled_content.skir",
                    "CompiledContentActivation",
                    "",
                    |x: &CompiledContentActivation| &x._unrecognized,
                    |x: &mut CompiledContentActivation, u| x._unrecognized = u,
                )
            });
        &*ADAPTER
    }
    pub fn serializer() -> crate::skir_client::Serializer<CompiledContentActivation> {
        initialize_module_serializers();
        crate::skir_client::internal::struct_serializer_from_static(CompiledContentActivation::_adapter())
    }
}

// ==============================================================================
// struct CompiledResourceState.Active
// ==============================================================================

#[derive(Clone, Debug, PartialEq, Default)]
pub struct CompiledResourceState_Active {
    pub manifest_id: String,
    /// Set this to None when you're creating a struct.
    pub _unrecognized: Option<crate::skir_client::UnrecognizedFields<CompiledResourceState_Active>>,
}

impl CompiledResourceState_Active {
    pub fn default_ref() -> &'static CompiledResourceState_Active {
        static D: std::sync::LazyLock<CompiledResourceState_Active> = std::sync::LazyLock::new(CompiledResourceState_Active::default);
        &D
    }
}

impl CompiledResourceState_Active {
    fn _adapter() -> &'static crate::skir_client::internal::StructAdapter<CompiledResourceState_Active> {
        static ADAPTER: std::sync::LazyLock<crate::skir_client::internal::StructAdapter<CompiledResourceState_Active>> =
            std::sync::LazyLock::new(|| {
                crate::skir_client::internal::StructAdapter::new(
                    "editor/v1/compiled_content.skir",
                    "CompiledResourceState.Active",
                    "",
                    |x: &CompiledResourceState_Active| &x._unrecognized,
                    |x: &mut CompiledResourceState_Active, u| x._unrecognized = u,
                )
            });
        &*ADAPTER
    }
    pub fn serializer() -> crate::skir_client::Serializer<CompiledResourceState_Active> {
        initialize_module_serializers();
        crate::skir_client::internal::struct_serializer_from_static(CompiledResourceState_Active::_adapter())
    }
}

// ==============================================================================
// struct CompiledResourceState.Blocked
// ==============================================================================

#[derive(Clone, Debug, PartialEq, Default)]
pub struct CompiledResourceState_Blocked {
    pub last_active_manifest_id: Option<String>,
    pub diagnostic_count: i32,
    /// Set this to None when you're creating a struct.
    pub _unrecognized: Option<crate::skir_client::UnrecognizedFields<CompiledResourceState_Blocked>>,
}

impl CompiledResourceState_Blocked {
    pub fn default_ref() -> &'static CompiledResourceState_Blocked {
        static D: std::sync::LazyLock<CompiledResourceState_Blocked> = std::sync::LazyLock::new(CompiledResourceState_Blocked::default);
        &D
    }
}

impl CompiledResourceState_Blocked {
    fn _adapter() -> &'static crate::skir_client::internal::StructAdapter<CompiledResourceState_Blocked> {
        static ADAPTER: std::sync::LazyLock<crate::skir_client::internal::StructAdapter<CompiledResourceState_Blocked>> =
            std::sync::LazyLock::new(|| {
                crate::skir_client::internal::StructAdapter::new(
                    "editor/v1/compiled_content.skir",
                    "CompiledResourceState.Blocked",
                    "",
                    |x: &CompiledResourceState_Blocked| &x._unrecognized,
                    |x: &mut CompiledResourceState_Blocked, u| x._unrecognized = u,
                )
            });
        &*ADAPTER
    }
    pub fn serializer() -> crate::skir_client::Serializer<CompiledResourceState_Blocked> {
        initialize_module_serializers();
        crate::skir_client::internal::struct_serializer_from_static(CompiledResourceState_Blocked::_adapter())
    }
}

// ==============================================================================
// enum CompiledResourceState
// ==============================================================================

#[derive(Debug, Clone, PartialEq)]
pub enum CompiledResourceState {
    Unknown(Option<crate::skir_client::UnrecognizedVariant<CompiledResourceState>>),
    NotCompiled,
    Active(Box<CompiledResourceState_Active>),
    Blocked(Box<CompiledResourceState_Blocked>),
}

impl Default for CompiledResourceState {
    fn default() -> Self {
        CompiledResourceState::Unknown(None)
    }
}

impl CompiledResourceState {
    fn _adapter() -> &'static crate::skir_client::internal::EnumAdapter<CompiledResourceState> {
        static ADAPTER: std::sync::LazyLock<crate::skir_client::internal::EnumAdapter<CompiledResourceState>> =
            std::sync::LazyLock::new(|| {
                crate::skir_client::internal::EnumAdapter::new(
                    |x: &CompiledResourceState| match x {
                        CompiledResourceState::Unknown(_) => 0,
                        CompiledResourceState::NotCompiled => 1,
                        CompiledResourceState::Active(_) => 2,
                        CompiledResourceState::Blocked(_) => 3,
                    },
                    |u| CompiledResourceState::Unknown(Some(u)),
                    |x: &CompiledResourceState| match x { CompiledResourceState::Unknown(Some(u)) => Some(u.as_ref()), _ => None },
                    "editor/v1/compiled_content.skir",
                    "CompiledResourceState",
                    "",
                )
            });
        &*ADAPTER
    }
    pub fn serializer() -> crate::skir_client::Serializer<CompiledResourceState> {
        initialize_module_serializers();
        crate::skir_client::internal::enum_serializer_from_static(CompiledResourceState::_adapter())
    }
}

// ==============================================================================
// struct CompiledResourceStatus
// ==============================================================================

#[derive(Clone, Debug, PartialEq, Default)]
pub struct CompiledResourceStatus {
    pub root: CompilationRoot,
    pub state: CompiledResourceState,
    /// Set this to None when you're creating a struct.
    pub _unrecognized: Option<crate::skir_client::UnrecognizedFields<CompiledResourceStatus>>,
}

impl CompiledResourceStatus {
    pub fn default_ref() -> &'static CompiledResourceStatus {
        static D: std::sync::LazyLock<CompiledResourceStatus> = std::sync::LazyLock::new(CompiledResourceStatus::default);
        &D
    }
}

impl CompiledResourceStatus {
    fn _adapter() -> &'static crate::skir_client::internal::StructAdapter<CompiledResourceStatus> {
        static ADAPTER: std::sync::LazyLock<crate::skir_client::internal::StructAdapter<CompiledResourceStatus>> =
            std::sync::LazyLock::new(|| {
                crate::skir_client::internal::StructAdapter::new(
                    "editor/v1/compiled_content.skir",
                    "CompiledResourceStatus",
                    "",
                    |x: &CompiledResourceStatus| &x._unrecognized,
                    |x: &mut CompiledResourceStatus, u| x._unrecognized = u,
                )
            });
        &*ADAPTER
    }
    pub fn serializer() -> crate::skir_client::Serializer<CompiledResourceStatus> {
        initialize_module_serializers();
        crate::skir_client::internal::struct_serializer_from_static(CompiledResourceStatus::_adapter())
    }
}

// ==============================================================================
// struct CompiledResourceStateChange.Upsert
// ==============================================================================

#[derive(Clone, Debug, PartialEq, Default)]
pub struct CompiledResourceStateChange_Upsert {
    pub root: CompilationRoot,
    pub state: CompiledResourceState,
    /// Set this to None when you're creating a struct.
    pub _unrecognized: Option<crate::skir_client::UnrecognizedFields<CompiledResourceStateChange_Upsert>>,
}

impl CompiledResourceStateChange_Upsert {
    pub fn default_ref() -> &'static CompiledResourceStateChange_Upsert {
        static D: std::sync::LazyLock<CompiledResourceStateChange_Upsert> = std::sync::LazyLock::new(CompiledResourceStateChange_Upsert::default);
        &D
    }
}

impl CompiledResourceStateChange_Upsert {
    fn _adapter() -> &'static crate::skir_client::internal::StructAdapter<CompiledResourceStateChange_Upsert> {
        static ADAPTER: std::sync::LazyLock<crate::skir_client::internal::StructAdapter<CompiledResourceStateChange_Upsert>> =
            std::sync::LazyLock::new(|| {
                crate::skir_client::internal::StructAdapter::new(
                    "editor/v1/compiled_content.skir",
                    "CompiledResourceStateChange.Upsert",
                    "",
                    |x: &CompiledResourceStateChange_Upsert| &x._unrecognized,
                    |x: &mut CompiledResourceStateChange_Upsert, u| x._unrecognized = u,
                )
            });
        &*ADAPTER
    }
    pub fn serializer() -> crate::skir_client::Serializer<CompiledResourceStateChange_Upsert> {
        initialize_module_serializers();
        crate::skir_client::internal::struct_serializer_from_static(CompiledResourceStateChange_Upsert::_adapter())
    }
}

// ==============================================================================
// enum CompiledResourceStateChange
// ==============================================================================

#[derive(Debug, Clone, PartialEq)]
pub enum CompiledResourceStateChange {
    Unknown(Option<crate::skir_client::UnrecognizedVariant<CompiledResourceStateChange>>),
    Upsert(Box<CompiledResourceStateChange_Upsert>),
    Remove(Box<CompilationRoot>),
}

impl Default for CompiledResourceStateChange {
    fn default() -> Self {
        CompiledResourceStateChange::Unknown(None)
    }
}

impl CompiledResourceStateChange {
    fn _adapter() -> &'static crate::skir_client::internal::EnumAdapter<CompiledResourceStateChange> {
        static ADAPTER: std::sync::LazyLock<crate::skir_client::internal::EnumAdapter<CompiledResourceStateChange>> =
            std::sync::LazyLock::new(|| {
                crate::skir_client::internal::EnumAdapter::new(
                    |x: &CompiledResourceStateChange| match x {
                        CompiledResourceStateChange::Unknown(_) => 0,
                        CompiledResourceStateChange::Upsert(_) => 1,
                        CompiledResourceStateChange::Remove(_) => 2,
                    },
                    |u| CompiledResourceStateChange::Unknown(Some(u)),
                    |x: &CompiledResourceStateChange| match x { CompiledResourceStateChange::Unknown(Some(u)) => Some(u.as_ref()), _ => None },
                    "editor/v1/compiled_content.skir",
                    "CompiledResourceStateChange",
                    "",
                )
            });
        &*ADAPTER
    }
    pub fn serializer() -> crate::skir_client::Serializer<CompiledResourceStateChange> {
        initialize_module_serializers();
        crate::skir_client::internal::enum_serializer_from_static(CompiledResourceStateChange::_adapter())
    }
}

// ==============================================================================
// struct CompiledContentChanged
// ==============================================================================

#[derive(Clone, Debug, PartialEq, Default)]
pub struct CompiledContentChanged {
    pub generation: crate::skirout::base::editor::v1::type_catalog::CatalogGeneration,
    pub source_sequence: i64,
    pub states: Vec<CompiledResourceStateChange>,
    /// Set this to None when you're creating a struct.
    pub _unrecognized: Option<crate::skir_client::UnrecognizedFields<CompiledContentChanged>>,
}

impl CompiledContentChanged {
    pub fn default_ref() -> &'static CompiledContentChanged {
        static D: std::sync::LazyLock<CompiledContentChanged> = std::sync::LazyLock::new(CompiledContentChanged::default);
        &D
    }
}

impl CompiledContentChanged {
    fn _adapter() -> &'static crate::skir_client::internal::StructAdapter<CompiledContentChanged> {
        static ADAPTER: std::sync::LazyLock<crate::skir_client::internal::StructAdapter<CompiledContentChanged>> =
            std::sync::LazyLock::new(|| {
                crate::skir_client::internal::StructAdapter::new(
                    "editor/v1/compiled_content.skir",
                    "CompiledContentChanged",
                    "",
                    |x: &CompiledContentChanged| &x._unrecognized,
                    |x: &mut CompiledContentChanged, u| x._unrecognized = u,
                )
            });
        &*ADAPTER
    }
    pub fn serializer() -> crate::skir_client::Serializer<CompiledContentChanged> {
        initialize_module_serializers();
        crate::skir_client::internal::struct_serializer_from_static(CompiledContentChanged::_adapter())
    }
}

// ==============================================================================
// struct WatchCompiledContentRequest
// ==============================================================================

#[derive(Clone, Debug, PartialEq, Default)]
pub struct WatchCompiledContentRequest {
    /// Set this to None when you're creating a struct.
    pub _unrecognized: Option<crate::skir_client::UnrecognizedFields<WatchCompiledContentRequest>>,
}

impl WatchCompiledContentRequest {
    pub fn default_ref() -> &'static WatchCompiledContentRequest {
        static D: std::sync::LazyLock<WatchCompiledContentRequest> = std::sync::LazyLock::new(WatchCompiledContentRequest::default);
        &D
    }
}

impl WatchCompiledContentRequest {
    fn _adapter() -> &'static crate::skir_client::internal::StructAdapter<WatchCompiledContentRequest> {
        static ADAPTER: std::sync::LazyLock<crate::skir_client::internal::StructAdapter<WatchCompiledContentRequest>> =
            std::sync::LazyLock::new(|| {
                crate::skir_client::internal::StructAdapter::new(
                    "editor/v1/compiled_content.skir",
                    "WatchCompiledContentRequest",
                    "",
                    |x: &WatchCompiledContentRequest| &x._unrecognized,
                    |x: &mut WatchCompiledContentRequest, u| x._unrecognized = u,
                )
            });
        &*ADAPTER
    }
    pub fn serializer() -> crate::skir_client::Serializer<WatchCompiledContentRequest> {
        initialize_module_serializers();
        crate::skir_client::internal::struct_serializer_from_static(WatchCompiledContentRequest::_adapter())
    }
}

// ==============================================================================
// struct WatchCompiledContentResponse.Initial
// ==============================================================================

#[derive(Clone, Debug, PartialEq, Default)]
pub struct WatchCompiledContentResponse_Initial {
    pub activation: Option<CompiledContentActivation>,
    /// Set this to None when you're creating a struct.
    pub _unrecognized: Option<crate::skir_client::UnrecognizedFields<WatchCompiledContentResponse_Initial>>,
}

impl WatchCompiledContentResponse_Initial {
    pub fn default_ref() -> &'static WatchCompiledContentResponse_Initial {
        static D: std::sync::LazyLock<WatchCompiledContentResponse_Initial> = std::sync::LazyLock::new(WatchCompiledContentResponse_Initial::default);
        &D
    }
}

impl WatchCompiledContentResponse_Initial {
    fn _adapter() -> &'static crate::skir_client::internal::StructAdapter<WatchCompiledContentResponse_Initial> {
        static ADAPTER: std::sync::LazyLock<crate::skir_client::internal::StructAdapter<WatchCompiledContentResponse_Initial>> =
            std::sync::LazyLock::new(|| {
                crate::skir_client::internal::StructAdapter::new(
                    "editor/v1/compiled_content.skir",
                    "WatchCompiledContentResponse.Initial",
                    "",
                    |x: &WatchCompiledContentResponse_Initial| &x._unrecognized,
                    |x: &mut WatchCompiledContentResponse_Initial, u| x._unrecognized = u,
                )
            });
        &*ADAPTER
    }
    pub fn serializer() -> crate::skir_client::Serializer<WatchCompiledContentResponse_Initial> {
        initialize_module_serializers();
        crate::skir_client::internal::struct_serializer_from_static(WatchCompiledContentResponse_Initial::_adapter())
    }
}

// ==============================================================================
// struct WatchCompiledContentResponse.Blocked
// ==============================================================================

#[derive(Clone, Debug, PartialEq, Default)]
pub struct WatchCompiledContentResponse_Blocked {
    /// Set this to None when you're creating a struct.
    pub _unrecognized: Option<crate::skir_client::UnrecognizedFields<WatchCompiledContentResponse_Blocked>>,
}

impl WatchCompiledContentResponse_Blocked {
    pub fn default_ref() -> &'static WatchCompiledContentResponse_Blocked {
        static D: std::sync::LazyLock<WatchCompiledContentResponse_Blocked> = std::sync::LazyLock::new(WatchCompiledContentResponse_Blocked::default);
        &D
    }
}

impl WatchCompiledContentResponse_Blocked {
    fn _adapter() -> &'static crate::skir_client::internal::StructAdapter<WatchCompiledContentResponse_Blocked> {
        static ADAPTER: std::sync::LazyLock<crate::skir_client::internal::StructAdapter<WatchCompiledContentResponse_Blocked>> =
            std::sync::LazyLock::new(|| {
                crate::skir_client::internal::StructAdapter::new(
                    "editor/v1/compiled_content.skir",
                    "WatchCompiledContentResponse.Blocked",
                    "",
                    |x: &WatchCompiledContentResponse_Blocked| &x._unrecognized,
                    |x: &mut WatchCompiledContentResponse_Blocked, u| x._unrecognized = u,
                )
            });
        &*ADAPTER
    }
    pub fn serializer() -> crate::skir_client::Serializer<WatchCompiledContentResponse_Blocked> {
        initialize_module_serializers();
        crate::skir_client::internal::struct_serializer_from_static(WatchCompiledContentResponse_Blocked::_adapter())
    }
}

// ==============================================================================
// enum WatchCompiledContentResponse
// ==============================================================================

#[derive(Debug, Clone, PartialEq)]
pub enum WatchCompiledContentResponse {
    Unknown(Option<crate::skir_client::UnrecognizedVariant<WatchCompiledContentResponse>>),
    Initial(Box<WatchCompiledContentResponse_Initial>),
    Activated(Box<CompiledContentActivation>),
    Blocked(Box<WatchCompiledContentResponse_Blocked>),
    InternalError(Box<crate::skirout::base::kernel::v1::errors::InternalError>),
}

impl Default for WatchCompiledContentResponse {
    fn default() -> Self {
        WatchCompiledContentResponse::Unknown(None)
    }
}

impl WatchCompiledContentResponse {
    fn _adapter() -> &'static crate::skir_client::internal::EnumAdapter<WatchCompiledContentResponse> {
        static ADAPTER: std::sync::LazyLock<crate::skir_client::internal::EnumAdapter<WatchCompiledContentResponse>> =
            std::sync::LazyLock::new(|| {
                crate::skir_client::internal::EnumAdapter::new(
                    |x: &WatchCompiledContentResponse| match x {
                        WatchCompiledContentResponse::Unknown(_) => 0,
                        WatchCompiledContentResponse::Initial(_) => 1,
                        WatchCompiledContentResponse::Activated(_) => 2,
                        WatchCompiledContentResponse::Blocked(_) => 3,
                        WatchCompiledContentResponse::InternalError(_) => 4,
                    },
                    |u| WatchCompiledContentResponse::Unknown(Some(u)),
                    |x: &WatchCompiledContentResponse| match x { WatchCompiledContentResponse::Unknown(Some(u)) => Some(u.as_ref()), _ => None },
                    "editor/v1/compiled_content.skir",
                    "WatchCompiledContentResponse",
                    "",
                )
            });
        &*ADAPTER
    }
    pub fn serializer() -> crate::skir_client::Serializer<WatchCompiledContentResponse> {
        initialize_module_serializers();
        crate::skir_client::internal::enum_serializer_from_static(WatchCompiledContentResponse::_adapter())
    }
}

// ==============================================================================
// struct QueryCompiledResourceStatusRequest
// ==============================================================================

#[derive(Clone, Debug, PartialEq, Default)]
pub struct QueryCompiledResourceStatusRequest {
    pub roots: Vec<CompilationRoot>,
    /// Set this to None when you're creating a struct.
    pub _unrecognized: Option<crate::skir_client::UnrecognizedFields<QueryCompiledResourceStatusRequest>>,
}

impl QueryCompiledResourceStatusRequest {
    pub fn default_ref() -> &'static QueryCompiledResourceStatusRequest {
        static D: std::sync::LazyLock<QueryCompiledResourceStatusRequest> = std::sync::LazyLock::new(QueryCompiledResourceStatusRequest::default);
        &D
    }
}

impl QueryCompiledResourceStatusRequest {
    fn _adapter() -> &'static crate::skir_client::internal::StructAdapter<QueryCompiledResourceStatusRequest> {
        static ADAPTER: std::sync::LazyLock<crate::skir_client::internal::StructAdapter<QueryCompiledResourceStatusRequest>> =
            std::sync::LazyLock::new(|| {
                crate::skir_client::internal::StructAdapter::new(
                    "editor/v1/compiled_content.skir",
                    "QueryCompiledResourceStatusRequest",
                    "",
                    |x: &QueryCompiledResourceStatusRequest| &x._unrecognized,
                    |x: &mut QueryCompiledResourceStatusRequest, u| x._unrecognized = u,
                )
            });
        &*ADAPTER
    }
    pub fn serializer() -> crate::skir_client::Serializer<QueryCompiledResourceStatusRequest> {
        initialize_module_serializers();
        crate::skir_client::internal::struct_serializer_from_static(QueryCompiledResourceStatusRequest::_adapter())
    }
}

// ==============================================================================
// struct QueryCompiledResourceStatusResponse.Success
// ==============================================================================

#[derive(Clone, Debug, PartialEq, Default)]
pub struct QueryCompiledResourceStatusResponse_Success {
    pub statuses: Vec<CompiledResourceStatus>,
    /// Set this to None when you're creating a struct.
    pub _unrecognized: Option<crate::skir_client::UnrecognizedFields<QueryCompiledResourceStatusResponse_Success>>,
}

impl QueryCompiledResourceStatusResponse_Success {
    pub fn default_ref() -> &'static QueryCompiledResourceStatusResponse_Success {
        static D: std::sync::LazyLock<QueryCompiledResourceStatusResponse_Success> = std::sync::LazyLock::new(QueryCompiledResourceStatusResponse_Success::default);
        &D
    }
}

impl QueryCompiledResourceStatusResponse_Success {
    fn _adapter() -> &'static crate::skir_client::internal::StructAdapter<QueryCompiledResourceStatusResponse_Success> {
        static ADAPTER: std::sync::LazyLock<crate::skir_client::internal::StructAdapter<QueryCompiledResourceStatusResponse_Success>> =
            std::sync::LazyLock::new(|| {
                crate::skir_client::internal::StructAdapter::new(
                    "editor/v1/compiled_content.skir",
                    "QueryCompiledResourceStatusResponse.Success",
                    "",
                    |x: &QueryCompiledResourceStatusResponse_Success| &x._unrecognized,
                    |x: &mut QueryCompiledResourceStatusResponse_Success, u| x._unrecognized = u,
                )
            });
        &*ADAPTER
    }
    pub fn serializer() -> crate::skir_client::Serializer<QueryCompiledResourceStatusResponse_Success> {
        initialize_module_serializers();
        crate::skir_client::internal::struct_serializer_from_static(QueryCompiledResourceStatusResponse_Success::_adapter())
    }
}

// ==============================================================================
// enum QueryCompiledResourceStatusResponse
// ==============================================================================

#[derive(Debug, Clone, PartialEq)]
pub enum QueryCompiledResourceStatusResponse {
    Unknown(Option<crate::skir_client::UnrecognizedVariant<QueryCompiledResourceStatusResponse>>),
    Success(Box<QueryCompiledResourceStatusResponse_Success>),
    InternalError(Box<crate::skirout::base::kernel::v1::errors::InternalError>),
}

impl Default for QueryCompiledResourceStatusResponse {
    fn default() -> Self {
        QueryCompiledResourceStatusResponse::Unknown(None)
    }
}

impl QueryCompiledResourceStatusResponse {
    fn _adapter() -> &'static crate::skir_client::internal::EnumAdapter<QueryCompiledResourceStatusResponse> {
        static ADAPTER: std::sync::LazyLock<crate::skir_client::internal::EnumAdapter<QueryCompiledResourceStatusResponse>> =
            std::sync::LazyLock::new(|| {
                crate::skir_client::internal::EnumAdapter::new(
                    |x: &QueryCompiledResourceStatusResponse| match x {
                        QueryCompiledResourceStatusResponse::Unknown(_) => 0,
                        QueryCompiledResourceStatusResponse::Success(_) => 1,
                        QueryCompiledResourceStatusResponse::InternalError(_) => 2,
                    },
                    |u| QueryCompiledResourceStatusResponse::Unknown(Some(u)),
                    |x: &QueryCompiledResourceStatusResponse| match x { QueryCompiledResourceStatusResponse::Unknown(Some(u)) => Some(u.as_ref()), _ => None },
                    "editor/v1/compiled_content.skir",
                    "QueryCompiledResourceStatusResponse",
                    "",
                )
            });
        &*ADAPTER
    }
    pub fn serializer() -> crate::skir_client::Serializer<QueryCompiledResourceStatusResponse> {
        initialize_module_serializers();
        crate::skir_client::internal::enum_serializer_from_static(QueryCompiledResourceStatusResponse::_adapter())
    }
}

// ==============================================================================
// initialize_module_serializers()
// ==============================================================================

fn initialize_module_serializers() {
    static INIT: std::sync::LazyLock<()> =
        std::sync::LazyLock::new(|| {
            unsafe {
                let a: *mut crate::skir_client::internal::StructAdapter<CompilationProjectionId> = CompilationProjectionId::_adapter() as *const _ as *mut _;
                (*a).add_field("value", 0, crate::skir_client::Serializer::string(), "", |x: &CompilationProjectionId| &x.value, |x: &mut CompilationProjectionId, v| x.value = v);
                (*a).finalize();
            }
            unsafe {
                let a: *mut crate::skir_client::internal::StructAdapter<CompilationRoot> = CompilationRoot::_adapter() as *const _ as *mut _;
                (*a).add_field("projection", 0, crate::skir_client::internal::struct_serializer_from_static(CompilationProjectionId::_adapter()), "", |x: &CompilationRoot| &x.projection, |x: &mut CompilationRoot, v| x.projection = v);
                (*a).add_field("resource", 1, crate::skirout::base::editor::v1::type_catalog::ResourceId::serializer(), "", |x: &CompilationRoot| &x.resource, |x: &mut CompilationRoot, v| x.resource = v);
                (*a).finalize();
            }
            unsafe {
                let a: *mut crate::skir_client::internal::StructAdapter<CompiledBlobPointer> = CompiledBlobPointer::_adapter() as *const _ as *mut _;
                (*a).add_field("digest", 0, crate::skir_client::Serializer::string(), "", |x: &CompiledBlobPointer| &x.digest, |x: &mut CompiledBlobPointer, v| x.digest = v);
                (*a).add_field("size", 1, crate::skir_client::Serializer::int64(), "", |x: &CompiledBlobPointer| &x.size, |x: &mut CompiledBlobPointer, v| x.size = v);
                (*a).finalize();
            }
            unsafe {
                let a: *mut crate::skir_client::internal::StructAdapter<CompiledArtifactPointer> = CompiledArtifactPointer::_adapter() as *const _ as *mut _;
                (*a).add_field("semantic_digest", 0, crate::skir_client::Serializer::string(), "", |x: &CompiledArtifactPointer| &x.semantic_digest, |x: &mut CompiledArtifactPointer, v| x.semantic_digest = v);
                (*a).add_field("blob", 1, crate::skir_client::internal::struct_serializer_from_static(CompiledBlobPointer::_adapter()), "", |x: &CompiledArtifactPointer| &x.blob, |x: &mut CompiledArtifactPointer, v| x.blob = v);
                (*a).finalize();
            }
            unsafe {
                let a: *mut crate::skir_client::internal::StructAdapter<CompiledContentActivation> = CompiledContentActivation::_adapter() as *const _ as *mut _;
                (*a).add_field("activation_revision", 0, crate::skir_client::Serializer::int64(), "", |x: &CompiledContentActivation| &x.activation_revision, |x: &mut CompiledContentActivation, v| x.activation_revision = v);
                (*a).add_field("manifest_digest", 1, crate::skir_client::Serializer::string(), "", |x: &CompiledContentActivation| &x.manifest_digest, |x: &mut CompiledContentActivation, v| x.manifest_digest = v);
                (*a).add_field("manifest", 2, crate::skir_client::internal::struct_serializer_from_static(CompiledBlobPointer::_adapter()), "", |x: &CompiledContentActivation| &x.manifest, |x: &mut CompiledContentActivation, v| x.manifest = v);
                (*a).add_field("artifacts", 3, crate::skir_client::Serializer::array(crate::skir_client::internal::struct_serializer_from_static(CompiledArtifactPointer::_adapter())), "", |x: &CompiledContentActivation| &x.artifacts, |x: &mut CompiledContentActivation, v| x.artifacts = v);
                (*a).finalize();
            }
            unsafe {
                let a: *mut crate::skir_client::internal::StructAdapter<CompiledResourceState_Active> = CompiledResourceState_Active::_adapter() as *const _ as *mut _;
                (*a).add_field("manifest_id", 0, crate::skir_client::Serializer::string(), "", |x: &CompiledResourceState_Active| &x.manifest_id, |x: &mut CompiledResourceState_Active, v| x.manifest_id = v);
                (*a).finalize();
            }
            unsafe {
                let a: *mut crate::skir_client::internal::StructAdapter<CompiledResourceState_Blocked> = CompiledResourceState_Blocked::_adapter() as *const _ as *mut _;
                (*a).add_field("last_active_manifest_id", 0, crate::skir_client::Serializer::optional(crate::skir_client::Serializer::string()), "", |x: &CompiledResourceState_Blocked| &x.last_active_manifest_id, |x: &mut CompiledResourceState_Blocked, v| x.last_active_manifest_id = v);
                (*a).add_field("diagnostic_count", 1, crate::skir_client::Serializer::int32(), "", |x: &CompiledResourceState_Blocked| &x.diagnostic_count, |x: &mut CompiledResourceState_Blocked, v| x.diagnostic_count = v);
                (*a).finalize();
            }
            unsafe {
                let a: *mut crate::skir_client::internal::EnumAdapter<CompiledResourceState> = CompiledResourceState::_adapter() as *const _ as *mut _;
                (*a).add_constant_variant("not_compiled", 1, 1, "", CompiledResourceState::NotCompiled);
                (*a).add_wrapper_variant("active", 2, 2, crate::skir_client::internal::struct_serializer_from_static(CompiledResourceState_Active::_adapter()), "", |v| CompiledResourceState::Active(Box::new(v)), |x| match x { CompiledResourceState::Active(b) => b.as_ref(), _ => unreachable!() });
                (*a).add_wrapper_variant("blocked", 3, 3, crate::skir_client::internal::struct_serializer_from_static(CompiledResourceState_Blocked::_adapter()), "", |v| CompiledResourceState::Blocked(Box::new(v)), |x| match x { CompiledResourceState::Blocked(b) => b.as_ref(), _ => unreachable!() });
                (*a).finalize();
            }
            unsafe {
                let a: *mut crate::skir_client::internal::StructAdapter<CompiledResourceStatus> = CompiledResourceStatus::_adapter() as *const _ as *mut _;
                (*a).add_field("root", 0, crate::skir_client::internal::struct_serializer_from_static(CompilationRoot::_adapter()), "", |x: &CompiledResourceStatus| &x.root, |x: &mut CompiledResourceStatus, v| x.root = v);
                (*a).add_field("state", 1, crate::skir_client::internal::enum_serializer_from_static(CompiledResourceState::_adapter()), "", |x: &CompiledResourceStatus| &x.state, |x: &mut CompiledResourceStatus, v| x.state = v);
                (*a).finalize();
            }
            unsafe {
                let a: *mut crate::skir_client::internal::StructAdapter<CompiledResourceStateChange_Upsert> = CompiledResourceStateChange_Upsert::_adapter() as *const _ as *mut _;
                (*a).add_field("root", 0, crate::skir_client::internal::struct_serializer_from_static(CompilationRoot::_adapter()), "", |x: &CompiledResourceStateChange_Upsert| &x.root, |x: &mut CompiledResourceStateChange_Upsert, v| x.root = v);
                (*a).add_field("state", 1, crate::skir_client::internal::enum_serializer_from_static(CompiledResourceState::_adapter()), "", |x: &CompiledResourceStateChange_Upsert| &x.state, |x: &mut CompiledResourceStateChange_Upsert, v| x.state = v);
                (*a).finalize();
            }
            unsafe {
                let a: *mut crate::skir_client::internal::EnumAdapter<CompiledResourceStateChange> = CompiledResourceStateChange::_adapter() as *const _ as *mut _;
                (*a).add_wrapper_variant("upsert", 1, 1, crate::skir_client::internal::struct_serializer_from_static(CompiledResourceStateChange_Upsert::_adapter()), "", |v| CompiledResourceStateChange::Upsert(Box::new(v)), |x| match x { CompiledResourceStateChange::Upsert(b) => b.as_ref(), _ => unreachable!() });
                (*a).add_wrapper_variant("remove", 2, 2, crate::skir_client::internal::struct_serializer_from_static(CompilationRoot::_adapter()), "", |v| CompiledResourceStateChange::Remove(Box::new(v)), |x| match x { CompiledResourceStateChange::Remove(b) => b.as_ref(), _ => unreachable!() });
                (*a).finalize();
            }
            unsafe {
                let a: *mut crate::skir_client::internal::StructAdapter<CompiledContentChanged> = CompiledContentChanged::_adapter() as *const _ as *mut _;
                (*a).add_field("generation", 0, crate::skirout::base::editor::v1::type_catalog::CatalogGeneration::serializer(), "", |x: &CompiledContentChanged| &x.generation, |x: &mut CompiledContentChanged, v| x.generation = v);
                (*a).add_field("source_sequence", 1, crate::skir_client::Serializer::int64(), "", |x: &CompiledContentChanged| &x.source_sequence, |x: &mut CompiledContentChanged, v| x.source_sequence = v);
                (*a).add_field("states", 2, crate::skir_client::Serializer::array(crate::skir_client::internal::enum_serializer_from_static(CompiledResourceStateChange::_adapter())), "", |x: &CompiledContentChanged| &x.states, |x: &mut CompiledContentChanged, v| x.states = v);
                (*a).finalize();
            }
            unsafe {
                let a: *mut crate::skir_client::internal::StructAdapter<WatchCompiledContentRequest> = WatchCompiledContentRequest::_adapter() as *const _ as *mut _;
                (*a).finalize();
            }
            unsafe {
                let a: *mut crate::skir_client::internal::StructAdapter<WatchCompiledContentResponse_Initial> = WatchCompiledContentResponse_Initial::_adapter() as *const _ as *mut _;
                (*a).add_field("activation", 0, crate::skir_client::Serializer::optional(crate::skir_client::internal::struct_serializer_from_static(CompiledContentActivation::_adapter())), "", |x: &WatchCompiledContentResponse_Initial| &x.activation, |x: &mut WatchCompiledContentResponse_Initial, v| x.activation = v);
                (*a).finalize();
            }
            unsafe {
                let a: *mut crate::skir_client::internal::StructAdapter<WatchCompiledContentResponse_Blocked> = WatchCompiledContentResponse_Blocked::_adapter() as *const _ as *mut _;
                (*a).finalize();
            }
            unsafe {
                let a: *mut crate::skir_client::internal::EnumAdapter<WatchCompiledContentResponse> = WatchCompiledContentResponse::_adapter() as *const _ as *mut _;
                (*a).add_wrapper_variant("initial", 1, 1, crate::skir_client::internal::struct_serializer_from_static(WatchCompiledContentResponse_Initial::_adapter()), "", |v| WatchCompiledContentResponse::Initial(Box::new(v)), |x| match x { WatchCompiledContentResponse::Initial(b) => b.as_ref(), _ => unreachable!() });
                (*a).add_wrapper_variant("activated", 2, 2, crate::skir_client::internal::struct_serializer_from_static(CompiledContentActivation::_adapter()), "", |v| WatchCompiledContentResponse::Activated(Box::new(v)), |x| match x { WatchCompiledContentResponse::Activated(b) => b.as_ref(), _ => unreachable!() });
                (*a).add_wrapper_variant("blocked", 3, 3, crate::skir_client::internal::struct_serializer_from_static(WatchCompiledContentResponse_Blocked::_adapter()), "", |v| WatchCompiledContentResponse::Blocked(Box::new(v)), |x| match x { WatchCompiledContentResponse::Blocked(b) => b.as_ref(), _ => unreachable!() });
                (*a).add_wrapper_variant("internal_error", 4, 4, crate::skirout::base::kernel::v1::errors::InternalError::serializer(), "", |v| WatchCompiledContentResponse::InternalError(Box::new(v)), |x| match x { WatchCompiledContentResponse::InternalError(b) => b.as_ref(), _ => unreachable!() });
                (*a).finalize();
            }
            unsafe {
                let a: *mut crate::skir_client::internal::StructAdapter<QueryCompiledResourceStatusRequest> = QueryCompiledResourceStatusRequest::_adapter() as *const _ as *mut _;
                (*a).add_field("roots", 0, crate::skir_client::Serializer::array(crate::skir_client::internal::struct_serializer_from_static(CompilationRoot::_adapter())), "", |x: &QueryCompiledResourceStatusRequest| &x.roots, |x: &mut QueryCompiledResourceStatusRequest, v| x.roots = v);
                (*a).finalize();
            }
            unsafe {
                let a: *mut crate::skir_client::internal::StructAdapter<QueryCompiledResourceStatusResponse_Success> = QueryCompiledResourceStatusResponse_Success::_adapter() as *const _ as *mut _;
                (*a).add_field("statuses", 0, crate::skir_client::Serializer::array(crate::skir_client::internal::struct_serializer_from_static(CompiledResourceStatus::_adapter())), "", |x: &QueryCompiledResourceStatusResponse_Success| &x.statuses, |x: &mut QueryCompiledResourceStatusResponse_Success, v| x.statuses = v);
                (*a).finalize();
            }
            unsafe {
                let a: *mut crate::skir_client::internal::EnumAdapter<QueryCompiledResourceStatusResponse> = QueryCompiledResourceStatusResponse::_adapter() as *const _ as *mut _;
                (*a).add_wrapper_variant("success", 1, 1, crate::skir_client::internal::struct_serializer_from_static(QueryCompiledResourceStatusResponse_Success::_adapter()), "", |v| QueryCompiledResourceStatusResponse::Success(Box::new(v)), |x| match x { QueryCompiledResourceStatusResponse::Success(b) => b.as_ref(), _ => unreachable!() });
                (*a).add_wrapper_variant("internal_error", 2, 2, crate::skirout::base::kernel::v1::errors::InternalError::serializer(), "", |v| QueryCompiledResourceStatusResponse::InternalError(Box::new(v)), |x| match x { QueryCompiledResourceStatusResponse::InternalError(b) => b.as_ref(), _ => unreachable!() });
                (*a).finalize();
            }
        });
    let _ = *INIT;
}

// ==============================================================================
// Methods
// ==============================================================================

pub fn watch_compiled_content_method() -> &'static crate::skir_client::Method<WatchCompiledContentRequest, WatchCompiledContentResponse> {
    static METHOD: std::sync::LazyLock<crate::skir_client::Method<WatchCompiledContentRequest, WatchCompiledContentResponse>> = std::sync::LazyLock::new(|| {
        crate::skir_client::Method {
            name: "WatchCompiledContent".to_string(),
            number: 920004_i64,
            request_serializer: WatchCompiledContentRequest::serializer(),
            response_serializer: WatchCompiledContentResponse::serializer(),
            doc: "".to_string(),
        }
    });
    &*METHOD
}

pub fn query_compiled_resource_status_method() -> &'static crate::skir_client::Method<QueryCompiledResourceStatusRequest, QueryCompiledResourceStatusResponse> {
    static METHOD: std::sync::LazyLock<crate::skir_client::Method<QueryCompiledResourceStatusRequest, QueryCompiledResourceStatusResponse>> = std::sync::LazyLock::new(|| {
        crate::skir_client::Method {
            name: "QueryCompiledResourceStatus".to_string(),
            number: 920005_i64,
            request_serializer: QueryCompiledResourceStatusRequest::serializer(),
            response_serializer: QueryCompiledResourceStatusResponse::serializer(),
            doc: "".to_string(),
        }
    });
    &*METHOD
}
