#![allow(nonstandard_style)]

//  ______                        _               _  _  _
//  |  _  \                      | |             | |(_)| |
//  | | | |  ___    _ __    ___  | |_    ___   __| | _ | |_
//  | | | | / _ \  | '_ \  / _ \ | __|  / _ \ / _` || || __|
//  | |/ / | (_) | | | | || (_) || |_  |  __/| (_| || || |_
//  |___/   \___/  |_| |_| \___/  \__|  \___| \__,_||_| \__|
//
// Generated by skir-rust-gen
// Home: https://github.com/gepheum/skir-rust-gen
//
// To install the Skir client library, run:
//   cargo add skir-client

// ==============================================================================
// struct FieldPathSegment
// ==============================================================================

#[derive(Clone, Debug, PartialEq, Default)]
pub struct FieldPathSegment {
    pub field_name: String,
    /// Set this to None when you're creating a struct.
    pub _unrecognized: Option<crate::skir_client::UnrecognizedFields<FieldPathSegment>>,
}

impl FieldPathSegment {
    pub fn default_ref() -> &'static FieldPathSegment {
        static D: std::sync::LazyLock<FieldPathSegment> = std::sync::LazyLock::new(FieldPathSegment::default);
        &D
    }
}

impl FieldPathSegment {
    fn _adapter() -> &'static crate::skir_client::internal::StructAdapter<FieldPathSegment> {
        static ADAPTER: std::sync::LazyLock<crate::skir_client::internal::StructAdapter<FieldPathSegment>> =
            std::sync::LazyLock::new(|| {
                crate::skir_client::internal::StructAdapter::new(
                    "editor/v1/path.skir",
                    "FieldPathSegment",
                    "",
                    |x: &FieldPathSegment| &x._unrecognized,
                    |x: &mut FieldPathSegment, u| x._unrecognized = u,
                )
            });
        &*ADAPTER
    }
    pub fn serializer() -> crate::skir_client::Serializer<FieldPathSegment> {
        initialize_module_serializers();
        crate::skir_client::internal::struct_serializer_from_static(FieldPathSegment::_adapter())
    }
}

// ==============================================================================
// struct IndexPathSegment
// ==============================================================================

#[derive(Clone, Debug, PartialEq, Default)]
pub struct IndexPathSegment {
    pub index: i32,
    /// Set this to None when you're creating a struct.
    pub _unrecognized: Option<crate::skir_client::UnrecognizedFields<IndexPathSegment>>,
}

impl IndexPathSegment {
    pub fn default_ref() -> &'static IndexPathSegment {
        static D: std::sync::LazyLock<IndexPathSegment> = std::sync::LazyLock::new(IndexPathSegment::default);
        &D
    }
}

impl IndexPathSegment {
    fn _adapter() -> &'static crate::skir_client::internal::StructAdapter<IndexPathSegment> {
        static ADAPTER: std::sync::LazyLock<crate::skir_client::internal::StructAdapter<IndexPathSegment>> =
            std::sync::LazyLock::new(|| {
                crate::skir_client::internal::StructAdapter::new(
                    "editor/v1/path.skir",
                    "IndexPathSegment",
                    "",
                    |x: &IndexPathSegment| &x._unrecognized,
                    |x: &mut IndexPathSegment, u| x._unrecognized = u,
                )
            });
        &*ADAPTER
    }
    pub fn serializer() -> crate::skir_client::Serializer<IndexPathSegment> {
        initialize_module_serializers();
        crate::skir_client::internal::struct_serializer_from_static(IndexPathSegment::_adapter())
    }
}

// ==============================================================================
// struct MapKeyPathSegment
// ==============================================================================

#[derive(Clone, Debug, PartialEq, Default)]
pub struct MapKeyPathSegment {
    pub key: crate::skirout::base::editor::v1::type_catalog::TypedValue,
    /// Set this to None when you're creating a struct.
    pub _unrecognized: Option<crate::skir_client::UnrecognizedFields<MapKeyPathSegment>>,
}

impl MapKeyPathSegment {
    pub fn default_ref() -> &'static MapKeyPathSegment {
        static D: std::sync::LazyLock<MapKeyPathSegment> = std::sync::LazyLock::new(MapKeyPathSegment::default);
        &D
    }
}

impl MapKeyPathSegment {
    fn _adapter() -> &'static crate::skir_client::internal::StructAdapter<MapKeyPathSegment> {
        static ADAPTER: std::sync::LazyLock<crate::skir_client::internal::StructAdapter<MapKeyPathSegment>> =
            std::sync::LazyLock::new(|| {
                crate::skir_client::internal::StructAdapter::new(
                    "editor/v1/path.skir",
                    "MapKeyPathSegment",
                    "",
                    |x: &MapKeyPathSegment| &x._unrecognized,
                    |x: &mut MapKeyPathSegment, u| x._unrecognized = u,
                )
            });
        &*ADAPTER
    }
    pub fn serializer() -> crate::skir_client::Serializer<MapKeyPathSegment> {
        initialize_module_serializers();
        crate::skir_client::internal::struct_serializer_from_static(MapKeyPathSegment::_adapter())
    }
}

// ==============================================================================
// enum DataPathSegment
// ==============================================================================

#[derive(Debug, Clone, PartialEq)]
pub enum DataPathSegment {
    Unknown(Option<crate::skir_client::UnrecognizedVariant<DataPathSegment>>),
    Field(Box<FieldPathSegment>),
    Index(Box<IndexPathSegment>),
    MapKey(Box<MapKeyPathSegment>),
}

impl Default for DataPathSegment {
    fn default() -> Self {
        DataPathSegment::Unknown(None)
    }
}

impl DataPathSegment {
    fn _adapter() -> &'static crate::skir_client::internal::EnumAdapter<DataPathSegment> {
        static ADAPTER: std::sync::LazyLock<crate::skir_client::internal::EnumAdapter<DataPathSegment>> =
            std::sync::LazyLock::new(|| {
                crate::skir_client::internal::EnumAdapter::new(
                    |x: &DataPathSegment| match x {
                        DataPathSegment::Unknown(_) => 0,
                        DataPathSegment::Field(_) => 1,
                        DataPathSegment::Index(_) => 2,
                        DataPathSegment::MapKey(_) => 3,
                    },
                    |u| DataPathSegment::Unknown(Some(u)),
                    |x: &DataPathSegment| match x { DataPathSegment::Unknown(Some(u)) => Some(u.as_ref()), _ => None },
                    "editor/v1/path.skir",
                    "DataPathSegment",
                    "",
                )
            });
        &*ADAPTER
    }
    pub fn serializer() -> crate::skir_client::Serializer<DataPathSegment> {
        initialize_module_serializers();
        crate::skir_client::internal::enum_serializer_from_static(DataPathSegment::_adapter())
    }
}

// ==============================================================================
// struct DataPath
// ==============================================================================

#[derive(Clone, Debug, PartialEq, Default)]
pub struct DataPath {
    pub segments: Vec<DataPathSegment>,
    /// Set this to None when you're creating a struct.
    pub _unrecognized: Option<crate::skir_client::UnrecognizedFields<DataPath>>,
}

impl DataPath {
    pub fn default_ref() -> &'static DataPath {
        static D: std::sync::LazyLock<DataPath> = std::sync::LazyLock::new(DataPath::default);
        &D
    }
}

impl DataPath {
    fn _adapter() -> &'static crate::skir_client::internal::StructAdapter<DataPath> {
        static ADAPTER: std::sync::LazyLock<crate::skir_client::internal::StructAdapter<DataPath>> =
            std::sync::LazyLock::new(|| {
                crate::skir_client::internal::StructAdapter::new(
                    "editor/v1/path.skir",
                    "DataPath",
                    "",
                    |x: &DataPath| &x._unrecognized,
                    |x: &mut DataPath, u| x._unrecognized = u,
                )
            });
        &*ADAPTER
    }
    pub fn serializer() -> crate::skir_client::Serializer<DataPath> {
        initialize_module_serializers();
        crate::skir_client::internal::struct_serializer_from_static(DataPath::_adapter())
    }
}

// ==============================================================================
// initialize_module_serializers()
// ==============================================================================

fn initialize_module_serializers() {
    static INIT: std::sync::LazyLock<()> =
        std::sync::LazyLock::new(|| {
            unsafe {
                let a: *mut crate::skir_client::internal::StructAdapter<FieldPathSegment> = FieldPathSegment::_adapter() as *const _ as *mut _;
                (*a).add_field("field_name", 0, crate::skir_client::Serializer::string(), "", |x: &FieldPathSegment| &x.field_name, |x: &mut FieldPathSegment, v| x.field_name = v);
                (*a).finalize();
            }
            unsafe {
                let a: *mut crate::skir_client::internal::StructAdapter<IndexPathSegment> = IndexPathSegment::_adapter() as *const _ as *mut _;
                (*a).add_field("index", 0, crate::skir_client::Serializer::int32(), "", |x: &IndexPathSegment| &x.index, |x: &mut IndexPathSegment, v| x.index = v);
                (*a).finalize();
            }
            unsafe {
                let a: *mut crate::skir_client::internal::StructAdapter<MapKeyPathSegment> = MapKeyPathSegment::_adapter() as *const _ as *mut _;
                (*a).add_field("key", 0, crate::skirout::base::editor::v1::type_catalog::TypedValue::serializer(), "", |x: &MapKeyPathSegment| &x.key, |x: &mut MapKeyPathSegment, v| x.key = v);
                (*a).finalize();
            }
            unsafe {
                let a: *mut crate::skir_client::internal::EnumAdapter<DataPathSegment> = DataPathSegment::_adapter() as *const _ as *mut _;
                (*a).add_wrapper_variant("field", 1, 1, crate::skir_client::internal::struct_serializer_from_static(FieldPathSegment::_adapter()), "", |v| DataPathSegment::Field(Box::new(v)), |x| match x { DataPathSegment::Field(b) => b.as_ref(), _ => unreachable!() });
                (*a).add_wrapper_variant("index", 2, 2, crate::skir_client::internal::struct_serializer_from_static(IndexPathSegment::_adapter()), "", |v| DataPathSegment::Index(Box::new(v)), |x| match x { DataPathSegment::Index(b) => b.as_ref(), _ => unreachable!() });
                (*a).add_wrapper_variant("map_key", 3, 3, crate::skir_client::internal::struct_serializer_from_static(MapKeyPathSegment::_adapter()), "", |v| DataPathSegment::MapKey(Box::new(v)), |x| match x { DataPathSegment::MapKey(b) => b.as_ref(), _ => unreachable!() });
                (*a).finalize();
            }
            unsafe {
                let a: *mut crate::skir_client::internal::StructAdapter<DataPath> = DataPath::_adapter() as *const _ as *mut _;
                (*a).add_field("segments", 0, crate::skir_client::Serializer::array(crate::skir_client::internal::enum_serializer_from_static(DataPathSegment::_adapter())), "", |x: &DataPath| &x.segments, |x: &mut DataPath, v| x.segments = v);
                (*a).finalize();
            }
        });
    let _ = *INIT;
}
