targets:
  $default:
    builders:
      json_serializable:
        options:
          explicit_to_json: true
      auto_route_generator:auto_route_generator:
        generate_for:
          - lib/features/**/presentation/**.dart
      auto_route_generator:auto_router_generator:
        generate_for:
          - lib/app/application/router/app_router.dart
global_options:
  freezed:
    runs_before:
      - riverpod_generator
  json_serializable:
    runs_before:
      - riverpod_generator
