name: typewriter_panel
description: "The panel to configure all of Typewriter"
publish_to: "none"
version: 1000.0.0+1

environment:
  sdk: ">=3.11.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  auto_route: ^11.0.0
  auto_size_text: ^3.0.0
  collection:
  cupertino_icons: ^1.0.8
  dart_casing: ^3.0.1
  nats_core:
    git:
      url: https://github.com/gabber235/nats.dart.git
      ref: 5c695ca2f0e46440dbd9e2afe618a20980673036
      path: packages/nats_core
  dartastic_opentelemetry: 1.1.0-beta.7
  dotted_border: ^3.1.0
  duration: ^4.0.3
  expandable_page_view: ^1.2.0
  fixnum: ^1.1.0
  flutter_animate: ^4.5.2
  flutter_hooks: ^0.21.2
  flutter_reorderable_grid_view: ^5.7.0
  freezed_annotation:
  riverpod: 3.2.1
  hooks_riverpod: 3.3.1
  http: ^1.2.0
  iconify_flutter_plus: ^1.0.4
  intl: ^0.20.2
  json_annotation: ^4.11.0
  json_path: ^0.9.0
  jovial_svg: ^1.1.30
  localstorage: ^6.0.0
  material_color_utilities:
  oidc: ^2.0.0
  oidc_core: ^2.0.0
  oidc_default_store: ^1.1.0
  okcolor: ^1.1.0
  petitparser: ^7.0.2
  pub_semver: ^2.2.0
  responsive_framework: ^1.5.1
  rive: ^0.14.0
  riverpod_annotation: 4.0.2
  skir_client:
    git:
      url: https://github.com/gabber235/skir-dart-client.git
      ref: 6d2e035dbcb060002a7a9f8f32d8e6598c76befd
  url_launcher: ^6.3.1
  uuid: ^4.5.1
  vector_math: ^2.2.0
  flutter_markdown_plus: ^1.0.12

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator:
  build_runner:
  flutter_lints:
  freezed:
  icons_launcher:
  json_serializable:
  riverpod_generator:
  riverpod_lint:
  test_screenshot:
  typewriter_testkit:
    path: testkit

dependency_overrides:
  json_annotation: 4.11.0

icons_launcher:
  image_path: "assets/typewriter_app_icon.png"
  platforms:
    android:
      enable: true
    ios:
      enable: true
    macos:
      enable: true
    windows:
      enable: true
    linux:
      enable: true
    web:
      enable: true

flutter:
  uses-material-design: true
  assets:
    - assets/cute_robot.riv
    - assets/game_character.riv
    - assets/robot_island.riv
    - assets/tour.riv
  fonts:
    - family: JetBrainsMono
      fonts:
        - asset: assets/fonts/JetBrains_Mono/JetBrainsMono-VariableFont_wght.ttf
        - asset: assets/fonts/JetBrains_Mono/JetBrainsMono-Italic-VariableFont_wght.ttf
          style: italic
    - family: Lilex
      fonts:
        - asset: assets/fonts/Lilex/Lilex-VariableFont_wght.ttf
        - asset: assets/fonts/Lilex/Lilex-Italic-VariableFont_wght.ttf
          style: italic
