apiVersion: runtime.wasmcloud.dev/v1alpha1
kind: WorkloadDeployment
metadata:
  name: auth-auth-callout
  namespace: wasmcloud
spec:
  replicas: 1
  template:
    spec:
      hostSelector:
        hostgroup: default
      components:
        - name: auth-auth-callout
          image: oci.seamlezz.test/wasmcloud/auth-auth-callout:0.1.0
          imagePullSecret:
            name: harbor-registry-credentials
          localResources:
            environment:
              configFrom:
                - name: auth-callout-config
              secretFrom:
                - name: auth-callout-secrets
      hostInterfaces:
        - namespace: wasmcloud
          package: messaging
          interfaces:
            - handler
            - consumer
          config:
            subscriptions: $SYS.REQ.USER.AUTH
        - namespace: wasi
          package: http
          interfaces:
            - outgoing-handler
        - namespace: wasi
          package: logging
          interfaces:
            - logging
