//  ______                        _               _  _  _
//  |  _  \                      | |             | |(_)| |
//  | | | |  ___    _ __    ___  | |_    ___   __| | _ | |_
//  | | | | / _ \  | '_ \  / _ \ | __|  / _ \ / _` || || __|
//  | |/ / | (_) | | | | || (_) || |_  |  __/| (_| || || |_
//  |___/   \___/  |_| |_| \___/  \__|  \___| \__,_||_| \__|
//
// Generated by skir-dart-gen
// Home: https://github.com/gepheum/skir-dart-gen
//
// To install the Skir client library:
//   dart pub add skir_client

import "dart:core" as _core;
import "package:skir_client/skir_client.dart" as _skir;
import "./type_catalog.dart" as _lib_editor_v1_type_catalog;

// -----------------------------------------------------------------------------
// struct FieldPathSegment
// -----------------------------------------------------------------------------

sealed class FieldPathSegment_orMutable {
  _core.String get fieldName;

  FieldPathSegment toFrozen();
}

/// Deeply immutable.
final class FieldPathSegment implements FieldPathSegment_orMutable {
  @_core.override
  final _core.String fieldName;
  _skir.internal__UnrecognizedFields? _u;

  factory FieldPathSegment({required _core.String fieldName}) =>
      FieldPathSegment._(fieldName);

  FieldPathSegment._(this.fieldName);

  /// Default instance with all fields set to their default values.
  static final defaultInstance = FieldPathSegment._("");

  /// Returns a new mutable instance.
  /// Fields are initialized to their default values.
  static FieldPathSegment_mutable mutable() => FieldPathSegment_mutable._("");

  /// Returns this instance (no-op).
  @_core.Deprecated("This instance is already frozen.")
  @_core.override
  FieldPathSegment toFrozen() => this;

  /// Returns a mutable shallow copy of this instance.
  FieldPathSegment_mutable toMutable() =>
      FieldPathSegment_mutable._(this.fieldName);

  @_core.override
  _core.bool operator ==(other) {
    if (_core.identical(this, other)) return true;
    if (other is! FieldPathSegment) return false;
    return _skir.internal__listEquality.equals(
      _equality_proxy,
      other._equality_proxy,
    );
  }

  @_core.override
  _core.int get hashCode => _skir.internal__listEquality.hash(_equality_proxy);

  _core.List get _equality_proxy => [this.fieldName];

  @_core.override
  _core.String toString() => _skir.internal__stringify(this, serializer);

  /// Serializer for `FieldPathSegment` instances.
  static _skir.StructSerializer<FieldPathSegment, FieldPathSegment_mutable>
  get serializer {
    if (_serializerBuilder.mustInitialize()) {
      _serializerBuilder.addField(
        "field_name",
        "fieldName",
        0,
        _skir.Serializers.string,
        "",
        (it) => it.fieldName,
        (it, v) => it.fieldName = v,
      );
      _serializerBuilder.finalize();
    }
    return _serializerBuilder.serializer;
  }

  static final _serializerBuilder = _skir.internal__StructSerializerBuilder(
    recordId: "editor/v1/path.skir:FieldPathSegment",
    doc: "",
    defaultInstance: defaultInstance,
    newMutable: (it) => (it != null) ? it.toMutable() : mutable(),
    toFrozen: (FieldPathSegment_mutable it) => it.toFrozen(),
    getUnrecognizedFields: (it) => it._u,
    setUnrecognizedFields: (it, u) => it._u = u,
  );
}

/// Mutable version of [FieldPathSegment].
final class FieldPathSegment_mutable implements FieldPathSegment_orMutable {
  _core.String fieldName;
  _skir.internal__UnrecognizedFields? _u;

  FieldPathSegment_mutable._(this.fieldName);

  /// Returns a deeply immutable copy of this instance.
  @_core.override
  FieldPathSegment toFrozen() =>
      FieldPathSegment(fieldName: this.fieldName).._u = this._u;
}

// -----------------------------------------------------------------------------
// struct IndexPathSegment
// -----------------------------------------------------------------------------

sealed class IndexPathSegment_orMutable {
  _core.int get index;

  IndexPathSegment toFrozen();
}

/// Deeply immutable.
final class IndexPathSegment implements IndexPathSegment_orMutable {
  @_core.override
  final _core.int index;
  _skir.internal__UnrecognizedFields? _u;

  factory IndexPathSegment({required _core.int index}) =>
      IndexPathSegment._(index);

  IndexPathSegment._(this.index);

  /// Default instance with all fields set to their default values.
  static final defaultInstance = IndexPathSegment._(0);

  /// Returns a new mutable instance.
  /// Fields are initialized to their default values.
  static IndexPathSegment_mutable mutable() => IndexPathSegment_mutable._(0);

  /// Returns this instance (no-op).
  @_core.Deprecated("This instance is already frozen.")
  @_core.override
  IndexPathSegment toFrozen() => this;

  /// Returns a mutable shallow copy of this instance.
  IndexPathSegment_mutable toMutable() =>
      IndexPathSegment_mutable._(this.index);

  @_core.override
  _core.bool operator ==(other) {
    if (_core.identical(this, other)) return true;
    if (other is! IndexPathSegment) return false;
    return _skir.internal__listEquality.equals(
      _equality_proxy,
      other._equality_proxy,
    );
  }

  @_core.override
  _core.int get hashCode => _skir.internal__listEquality.hash(_equality_proxy);

  _core.List get _equality_proxy => [this.index];

  @_core.override
  _core.String toString() => _skir.internal__stringify(this, serializer);

  /// Serializer for `IndexPathSegment` instances.
  static _skir.StructSerializer<IndexPathSegment, IndexPathSegment_mutable>
  get serializer {
    if (_serializerBuilder.mustInitialize()) {
      _serializerBuilder.addField(
        "index",
        "index",
        0,
        _skir.Serializers.int32,
        "",
        (it) => it.index,
        (it, v) => it.index = v,
      );
      _serializerBuilder.finalize();
    }
    return _serializerBuilder.serializer;
  }

  static final _serializerBuilder = _skir.internal__StructSerializerBuilder(
    recordId: "editor/v1/path.skir:IndexPathSegment",
    doc: "",
    defaultInstance: defaultInstance,
    newMutable: (it) => (it != null) ? it.toMutable() : mutable(),
    toFrozen: (IndexPathSegment_mutable it) => it.toFrozen(),
    getUnrecognizedFields: (it) => it._u,
    setUnrecognizedFields: (it, u) => it._u = u,
  );
}

/// Mutable version of [IndexPathSegment].
final class IndexPathSegment_mutable implements IndexPathSegment_orMutable {
  _core.int index;
  _skir.internal__UnrecognizedFields? _u;

  IndexPathSegment_mutable._(this.index);

  /// Returns a deeply immutable copy of this instance.
  @_core.override
  IndexPathSegment toFrozen() =>
      IndexPathSegment(index: this.index).._u = this._u;
}

// -----------------------------------------------------------------------------
// struct MapKeyPathSegment
// -----------------------------------------------------------------------------

sealed class MapKeyPathSegment_orMutable {
  _lib_editor_v1_type_catalog.TypedValue get key;

  MapKeyPathSegment toFrozen();
}

/// Deeply immutable.
final class MapKeyPathSegment implements MapKeyPathSegment_orMutable {
  @_core.override
  final _lib_editor_v1_type_catalog.TypedValue key;
  _skir.internal__UnrecognizedFields? _u;

  factory MapKeyPathSegment({
    required _lib_editor_v1_type_catalog.TypedValue key,
  }) => MapKeyPathSegment._(key);

  MapKeyPathSegment._(this.key);

  /// Default instance with all fields set to their default values.
  static final defaultInstance = MapKeyPathSegment._(
    _lib_editor_v1_type_catalog.TypedValue.unknown,
  );

  /// Returns a new mutable instance.
  /// Fields are initialized to their default values.
  static MapKeyPathSegment_mutable mutable() => MapKeyPathSegment_mutable._(
    _lib_editor_v1_type_catalog.TypedValue.unknown,
  );

  /// Returns this instance (no-op).
  @_core.Deprecated("This instance is already frozen.")
  @_core.override
  MapKeyPathSegment toFrozen() => this;

  /// Returns a mutable shallow copy of this instance.
  MapKeyPathSegment_mutable toMutable() =>
      MapKeyPathSegment_mutable._(this.key);

  @_core.override
  _core.bool operator ==(other) {
    if (_core.identical(this, other)) return true;
    if (other is! MapKeyPathSegment) return false;
    return _skir.internal__listEquality.equals(
      _equality_proxy,
      other._equality_proxy,
    );
  }

  @_core.override
  _core.int get hashCode => _skir.internal__listEquality.hash(_equality_proxy);

  _core.List get _equality_proxy => [this.key];

  @_core.override
  _core.String toString() => _skir.internal__stringify(this, serializer);

  /// Serializer for `MapKeyPathSegment` instances.
  static _skir.StructSerializer<MapKeyPathSegment, MapKeyPathSegment_mutable>
  get serializer {
    if (_serializerBuilder.mustInitialize()) {
      _serializerBuilder.addField(
        "key",
        "key",
        0,
        _lib_editor_v1_type_catalog.TypedValue.serializer,
        "",
        (it) => it.key,
        (it, v) => it.key = v,
      );
      _serializerBuilder.finalize();
    }
    return _serializerBuilder.serializer;
  }

  static final _serializerBuilder = _skir.internal__StructSerializerBuilder(
    recordId: "editor/v1/path.skir:MapKeyPathSegment",
    doc: "",
    defaultInstance: defaultInstance,
    newMutable: (it) => (it != null) ? it.toMutable() : mutable(),
    toFrozen: (MapKeyPathSegment_mutable it) => it.toFrozen(),
    getUnrecognizedFields: (it) => it._u,
    setUnrecognizedFields: (it, u) => it._u = u,
  );
}

/// Mutable version of [MapKeyPathSegment].
final class MapKeyPathSegment_mutable implements MapKeyPathSegment_orMutable {
  _lib_editor_v1_type_catalog.TypedValue key;
  _skir.internal__UnrecognizedFields? _u;

  MapKeyPathSegment_mutable._(this.key);

  /// Returns a deeply immutable copy of this instance.
  @_core.override
  MapKeyPathSegment toFrozen() =>
      MapKeyPathSegment(key: this.key).._u = this._u;
}

// -----------------------------------------------------------------------------
// enum DataPathSegment
// -----------------------------------------------------------------------------

/// To switch on the variants:
///   ```
///   switch (e) {
///     case DataPathSegment_unknown(): { ... }
///     case DataPathSegment_field(:var value): { ... }
///     case DataPathSegment_index(:var value): { ... }
///     case DataPathSegment_mapKey(:var value): { ... }
///   }
///   ```
///
/// Deeply immutable.
sealed class DataPathSegment {
  /// Constant indicating an unknown `DataPathSegment`.
  /// Default value for fields of type `DataPathSegment`.
  static const DataPathSegment unknown = DataPathSegment_unknown._instance;

  /// Create a 'field' variant wrapping around the given value.
  factory DataPathSegment.wrapField(FieldPathSegment value) =>
      DataPathSegment_fieldWrapper._(value);

  /// Same as `wrapField(FieldPathSegment(...))`.
  factory DataPathSegment.createField({required _core.String fieldName}) =>
      DataPathSegment.wrapField(FieldPathSegment(fieldName: fieldName));

  /// Create a 'index' variant wrapping around the given value.
  factory DataPathSegment.wrapIndex(IndexPathSegment value) =>
      DataPathSegment_indexWrapper._(value);

  /// Same as `wrapIndex(IndexPathSegment(...))`.
  factory DataPathSegment.createIndex({required _core.int index}) =>
      DataPathSegment.wrapIndex(IndexPathSegment(index: index));

  /// Create a 'map_key' variant wrapping around the given value.
  factory DataPathSegment.wrapMapKey(MapKeyPathSegment value) =>
      DataPathSegment_mapKeyWrapper._(value);

  /// Same as `wrapMapKey(MapKeyPathSegment(...))`.
  factory DataPathSegment.createMapKey({
    required _lib_editor_v1_type_catalog.TypedValue key,
  }) => DataPathSegment.wrapMapKey(MapKeyPathSegment(key: key));

  /// Returns the kind of variant held by this DataPathSegment.
  DataPathSegment_kind get kind;

  /// Serializer for `DataPathSegment` instances.
  static _skir.EnumSerializer<DataPathSegment> get serializer {
    if (_serializerBuilder.mustInitialize()) {
      _serializerBuilder.addWrapperVariant(
        1,
        "field",
        "wrapField",
        FieldPathSegment.serializer,
        "",
        DataPathSegment_fieldWrapper._,
        (it) => it.value,
        ordinal: DataPathSegment_kind.fieldWrapper._ordinal,
      );
      _serializerBuilder.addWrapperVariant(
        2,
        "index",
        "wrapIndex",
        IndexPathSegment.serializer,
        "",
        DataPathSegment_indexWrapper._,
        (it) => it.value,
        ordinal: DataPathSegment_kind.indexWrapper._ordinal,
      );
      _serializerBuilder.addWrapperVariant(
        3,
        "map_key",
        "wrapMapKey",
        MapKeyPathSegment.serializer,
        "",
        DataPathSegment_mapKeyWrapper._,
        (it) => it.value,
        ordinal: DataPathSegment_kind.mapKeyWrapper._ordinal,
      );
      _serializerBuilder.finalize();
    }
    return _serializerBuilder.serializer;
  }

  static final _serializerBuilder = _skir.internal__EnumSerializerBuilder
      .create(
        recordId: "editor/v1/path.skir:DataPathSegment",
        doc: "",
        unknownInstance: DataPathSegment_unknown._instance,
        enumInstance: DataPathSegment.unknown,
        getOrdinal: (it) => it.kind._ordinal,
        wrapUnrecognized: DataPathSegment_unknown._unrecognized,
        getUnrecognized: (it) => it._u,
      );
}

/// The kind of variant held by a `DataPathSegment`.
enum DataPathSegment_kind {
  unknown(0),
  fieldWrapper(1),
  indexWrapper(2),
  mapKeyWrapper(3);

  final _core.int _ordinal;

  const DataPathSegment_kind(this._ordinal);
}

final class DataPathSegment_unknown implements DataPathSegment {
  static const _instance = DataPathSegment_unknown._();

  final _skir.internal__UnrecognizedVariant? _u;

  const DataPathSegment_unknown._() : _u = null;
  DataPathSegment_unknown._unrecognized(this._u);

  @_core.override
  DataPathSegment_kind get kind => DataPathSegment_kind.unknown;
  @_core.override
  _core.bool operator ==(other) => other is DataPathSegment_unknown;
  @_core.override
  _core.int get hashCode => 8118964;
  @_core.override
  _core.String toString() =>
      _skir.internal__stringify(this, DataPathSegment.serializer);
}

sealed class _DataPathSegment_wrapper implements DataPathSegment {
  _core.dynamic get value;

  @_core.override
  _core.bool operator ==(other) {
    if (other is! _DataPathSegment_wrapper) return false;
    return kind == other.kind && value == other.value;
  }

  @_core.override
  _core.int get hashCode => (kind._ordinal * 31) ^ value.hashCode;

  @_core.override
  _core.String toString() =>
      _skir.internal__stringify(this, DataPathSegment.serializer);
}

final class DataPathSegment_fieldWrapper extends _DataPathSegment_wrapper {
  final FieldPathSegment value;

  DataPathSegment_fieldWrapper._(this.value);

  @_core.override
  DataPathSegment_kind get kind => DataPathSegment_kind.fieldWrapper;
}

final class DataPathSegment_indexWrapper extends _DataPathSegment_wrapper {
  final IndexPathSegment value;

  DataPathSegment_indexWrapper._(this.value);

  @_core.override
  DataPathSegment_kind get kind => DataPathSegment_kind.indexWrapper;
}

final class DataPathSegment_mapKeyWrapper extends _DataPathSegment_wrapper {
  final MapKeyPathSegment value;

  DataPathSegment_mapKeyWrapper._(this.value);

  @_core.override
  DataPathSegment_kind get kind => DataPathSegment_kind.mapKeyWrapper;
}

// -----------------------------------------------------------------------------
// struct DataPath
// -----------------------------------------------------------------------------

sealed class DataPath_orMutable {
  _core.Iterable<DataPathSegment> get segments;

  DataPath toFrozen();
}

/// Deeply immutable.
final class DataPath implements DataPath_orMutable {
  @_core.override
  final _core.Iterable<DataPathSegment> segments;
  _skir.internal__UnrecognizedFields? _u;

  factory DataPath({required _core.Iterable<DataPathSegment> segments}) =>
      DataPath._(_skir.internal__frozenCopy(segments));

  DataPath._(this.segments);

  /// Default instance with all fields set to their default values.
  static final defaultInstance = DataPath._(_skir.KeyedIterable.empty);

  /// Returns a new mutable instance.
  /// Fields are initialized to their default values.
  static DataPath_mutable mutable() =>
      DataPath_mutable._(_skir.KeyedIterable.empty);

  /// Returns this instance (no-op).
  @_core.Deprecated("This instance is already frozen.")
  @_core.override
  DataPath toFrozen() => this;

  /// Returns a mutable shallow copy of this instance.
  DataPath_mutable toMutable() => DataPath_mutable._(this.segments);

  @_core.override
  _core.bool operator ==(other) {
    if (_core.identical(this, other)) return true;
    if (other is! DataPath) return false;
    return _skir.internal__listEquality.equals(
      _equality_proxy,
      other._equality_proxy,
    );
  }

  @_core.override
  _core.int get hashCode => _skir.internal__listEquality.hash(_equality_proxy);

  _core.List get _equality_proxy => [this.segments];

  @_core.override
  _core.String toString() => _skir.internal__stringify(this, serializer);

  /// Serializer for `DataPath` instances.
  static _skir.StructSerializer<DataPath, DataPath_mutable> get serializer {
    if (_serializerBuilder.mustInitialize()) {
      _serializerBuilder.addField(
        "segments",
        "segments",
        0,
        _skir.Serializers.iterable(DataPathSegment.serializer),
        "",
        (it) => it.segments,
        (it, v) => it.segments = v,
      );
      _serializerBuilder.finalize();
    }
    return _serializerBuilder.serializer;
  }

  static final _serializerBuilder = _skir.internal__StructSerializerBuilder(
    recordId: "editor/v1/path.skir:DataPath",
    doc: "",
    defaultInstance: defaultInstance,
    newMutable: (it) => (it != null) ? it.toMutable() : mutable(),
    toFrozen: (DataPath_mutable it) => it.toFrozen(),
    getUnrecognizedFields: (it) => it._u,
    setUnrecognizedFields: (it, u) => it._u = u,
  );
}

/// Mutable version of [DataPath].
final class DataPath_mutable implements DataPath_orMutable {
  _core.Iterable<DataPathSegment> segments;
  _skir.internal__UnrecognizedFields? _u;

  DataPath_mutable._(this.segments);

  /// If the value of [segments] is already mutable, returns it as-is.
  /// Otherwise, makes a mutable copy, assigns it back to [segments] and returns it.
  _core.List<DataPathSegment> get mutableSegments {
    final value = this.segments;
    if (value is _skir.internal__MutableList<DataPathSegment>) {
      return value;
    } else {
      return this.segments = _skir.internal__MutableList([...value]);
    }
  }

  /// Returns a deeply immutable copy of this instance.
  @_core.override
  DataPath toFrozen() => DataPath(segments: this.segments).._u = this._u;
}
