@file:Suppress("ktlint")

//  ______                        _               _  _  _
//  |  _  \                      | |             | |(_)| |
//  | | | |  ___    _ __    ___  | |_    ___   __| | _ | |_
//  | | | | / _ \  | '_ \  / _ \ | __|  / _ \ / _` || || __|
//  | |/ / | (_) | | | | || (_) || |_  |  __/| (_| || || |_
//  |___/   \___/  |_| |_| \___/  \__|  \___| \__,_||_| \__|
//
// Generated by skir-kotlin-gen
// Home: https://github.com/gepheum/skir-kotlin-gen
//
// To install the Skir client library, add:
//   implementation("build.skir:skir-client:latest.release")
// to your build.gradle.kts file

package skirout.editor.v1.catalog_presentation;

import build.skir.internal.MustNameArguments as _MustNameArguments;
import build.skir.internal.UnrecognizedFields as _UnrecognizedFields;
import build.skir.internal.UnrecognizedVariant as _UnrecognizedVariant;

sealed interface CatalogPresentationSubject_OrMutable {
    val target: skirout.editor.v1.type_catalog.TypeUse;
    val descriptor: skirout.editor.v1.typed_value.PortableValue_OrMutable;

    fun toFrozen(): skirout.editor.v1.catalog_presentation.CatalogPresentationSubject;
}

/** Deeply immutable. */
@kotlin.Suppress("UNUSED_PARAMETER")
class CatalogPresentationSubject private constructor(
    override val target: skirout.editor.v1.type_catalog.TypeUse,
    override val descriptor: skirout.editor.v1.typed_value.PortableValue,
    internal val _unrecognizedFields: _UnrecognizedFields<skirout.editor.v1.catalog_presentation.CatalogPresentationSubject>? =
        null,
): skirout.editor.v1.catalog_presentation.CatalogPresentationSubject_OrMutable {
    constructor(
        _mustNameArguments: _MustNameArguments =
            _MustNameArguments,
        target: skirout.editor.v1.type_catalog.TypeUse,
        descriptor: skirout.editor.v1.typed_value.PortableValue_OrMutable,
        _unrecognizedFields: _UnrecognizedFields<skirout.editor.v1.catalog_presentation.CatalogPresentationSubject>? =
            null,
    ): this(
        target,
        descriptor.toFrozen(),
        _unrecognizedFields,
    ) {}

    @kotlin.Deprecated("Already frozen", kotlin.ReplaceWith("this"))
    override fun toFrozen() = this;

    /** Returns a mutable shallow copy of this instance */
    fun toMutable() = Mutable(
        target = this.target,
        descriptor = this.descriptor,
    );

    /** Returns a shallow copy of this instance with the specified fields replaced. */
    fun copy(
        _mustNameArguments: _MustNameArguments =
            _MustNameArguments,
        target: skirout.editor.v1.type_catalog.TypeUse =
            this.target,
        descriptor: skirout.editor.v1.typed_value.PortableValue_OrMutable =
            this.descriptor,
    ) = skirout.editor.v1.catalog_presentation.CatalogPresentationSubject(
        target,
        descriptor.toFrozen(),
        this._unrecognizedFields,
    );

    @kotlin.Deprecated("No point in creating an exact copy of an immutable object", kotlin.ReplaceWith("this"))
    fun copy() = this;

    override fun equals(other: kotlin.Any?): kotlin.Boolean {
        return this === other || (other is skirout.editor.v1.catalog_presentation.CatalogPresentationSubject && this.target == other.target && this.descriptor == other.descriptor);
    }

    override fun hashCode(): kotlin.Int {
        return kotlin.collections.listOf<kotlin.Any?>(this.target, this.descriptor).hashCode();
    }

    override fun toString(): kotlin.String {
        return build.skir.internal.toStringImpl(
            this,
            _SerializerRegistry.CatalogPresentationSubjectSerializerImpl,
        )
    }

    /** Mutable version of [CatalogPresentationSubject]. */
    class Mutable internal constructor(
        _mustNameArguments: _MustNameArguments =
            _MustNameArguments,
        override var target: skirout.editor.v1.type_catalog.TypeUse =
            skirout.editor.v1.type_catalog.TypeUse.UNKNOWN,
        override var descriptor: skirout.editor.v1.typed_value.PortableValue_OrMutable =
            skirout.editor.v1.typed_value.PortableValue.partial(),
        internal var _unrecognizedFields: _UnrecognizedFields<skirout.editor.v1.catalog_presentation.CatalogPresentationSubject>? =
            null,
    ): skirout.editor.v1.catalog_presentation.CatalogPresentationSubject_OrMutable {
        /** Returns a deeply immutable copy of this instance */
        override fun toFrozen() = skirout.editor.v1.catalog_presentation.CatalogPresentationSubject(
            target = this.target,
            descriptor = this.descriptor,
            _unrecognizedFields = this._unrecognizedFields,
        );

        /**
         * If the value of [descriptor] is already mutable, returns it as-is.
         * Otherwise, makes a mutable copy, assigns it back to [descriptor] and returns it.
         */
        val mutableDescriptor: skirout.editor.v1.typed_value.PortableValue.Mutable get() {
            var value = this.descriptor;
            return when (value) {
                is skirout.editor.v1.typed_value.PortableValue -> {
                    value = value.toMutable();
                    this.descriptor = value;
                    return value;
                }
                is skirout.editor.v1.typed_value.PortableValue.Mutable -> value;
            }
        }
    }

    companion object {
        private val default =
            skirout.editor.v1.catalog_presentation.CatalogPresentationSubject(
                skirout.editor.v1.type_catalog.TypeUse.UNKNOWN,
                skirout.editor.v1.typed_value.PortableValue.partial(),
            );

        /** Returns an instance with all fields set to their default values. */
        fun partial() = default;

        /**
         * Creates a new instance of [CatalogPresentationSubject].
         * Unlike the constructor, does not require all fields to be specified.
         * Missing fields will be set to their default values.
         */
        fun partial(
            _mustNameArguments: _MustNameArguments =
                _MustNameArguments,
            target: skirout.editor.v1.type_catalog.TypeUse =
                skirout.editor.v1.type_catalog.TypeUse.UNKNOWN,
            descriptor: skirout.editor.v1.typed_value.PortableValue_OrMutable =
                skirout.editor.v1.typed_value.PortableValue.partial(),
        ) = skirout.editor.v1.catalog_presentation.CatalogPresentationSubject(
            target = target,
            descriptor = descriptor,
            _unrecognizedFields = null,
        );

        /** Serializer for [CatalogPresentationSubject] instances. */
        val serializer get() = _SerializerRegistry.CatalogPresentationSubjectSerializer;

        /** Describes the [CatalogPresentationSubject] type. Provides runtime introspection capabilities. */
        val typeDescriptor get() = _SerializerRegistry.CatalogPresentationSubjectSerializerImpl.typeDescriptor;
    }
}

private object _SerializerRegistry {
    val CatalogPresentationSubjectSerializerImpl = build.skir.internal.StructSerializer(
        recordId = "editor/v1/catalog_presentation.skir:CatalogPresentationSubject",
        doc = "",
        defaultInstance = skirout.editor.v1.catalog_presentation.CatalogPresentationSubject.partial(),
        newMutableFn = { it?.toMutable() ?: skirout.editor.v1.catalog_presentation.CatalogPresentationSubject.Mutable() },
        toFrozenFn = { it.toFrozen() },
        getUnrecognizedFields = { it._unrecognizedFields },
        setUnrecognizedFields = { m, u -> m._unrecognizedFields = u },
    );

    val CatalogPresentationSubjectSerializer = build.skir.internal.makeSerializer(CatalogPresentationSubjectSerializerImpl);

    init {
        CatalogPresentationSubjectSerializerImpl.addField(
            "target",
            "target",
            0,
            skirout.editor.v1.type_catalog.TypeUse.serializer,
            "",
            { it.target },
            { mut, v -> mut.target = v },
        );
        CatalogPresentationSubjectSerializerImpl.addField(
            "descriptor",
            "descriptor",
            1,
            skirout.editor.v1.typed_value.PortableValue.serializer,
            "",
            { it.descriptor },
            { mut, v -> mut.descriptor = v },
        );
        CatalogPresentationSubjectSerializerImpl.finalizeStruct();
    }
}
