@file:Suppress("ktlint")

//  ______                        _               _  _  _
//  |  _  \                      | |             | |(_)| |
//  | | | |  ___    _ __    ___  | |_    ___   __| | _ | |_
//  | | | | / _ \  | '_ \  / _ \ | __|  / _ \ / _` || || __|
//  | |/ / | (_) | | | | || (_) || |_  |  __/| (_| || || |_
//  |___/   \___/  |_| |_| \___/  \__|  \___| \__,_||_| \__|
//
// Generated by skir-kotlin-gen
// Home: https://github.com/gepheum/skir-kotlin-gen
//
// To install the Skir client library, add:
//   implementation("build.skir:skir-client:latest.release")
// to your build.gradle.kts file

package skirout.editor.v1.typed_value;

import build.skir.internal.MustNameArguments as _MustNameArguments;
import build.skir.internal.UnrecognizedFields as _UnrecognizedFields;
import build.skir.internal.UnrecognizedVariant as _UnrecognizedVariant;

sealed interface PortableValue_OrMutable {
    val actualType: skirout.editor.v1.type_catalog.TypeUse;
    val payload: skirout.editor.v1.type_catalog.DataValue;

    fun toFrozen(): skirout.editor.v1.typed_value.PortableValue;
}

/** Deeply immutable. */
@kotlin.Suppress("UNUSED_PARAMETER")
class PortableValue private constructor(
    override val actualType: skirout.editor.v1.type_catalog.TypeUse,
    override val payload: skirout.editor.v1.type_catalog.DataValue,
    internal val _unrecognizedFields: _UnrecognizedFields<skirout.editor.v1.typed_value.PortableValue>? =
        null,
): skirout.editor.v1.typed_value.PortableValue_OrMutable {
    constructor(
        _mustNameArguments: _MustNameArguments =
            _MustNameArguments,
        actualType: skirout.editor.v1.type_catalog.TypeUse,
        payload: skirout.editor.v1.type_catalog.DataValue,
        _unrecognizedFields: _UnrecognizedFields<skirout.editor.v1.typed_value.PortableValue>? =
            null,
    ): this(
        actualType,
        payload,
        _unrecognizedFields,
    ) {}

    @kotlin.Deprecated("Already frozen", kotlin.ReplaceWith("this"))
    override fun toFrozen() = this;

    /** Returns a mutable shallow copy of this instance */
    fun toMutable() = Mutable(
        actualType = this.actualType,
        payload = this.payload,
    );

    /** Returns a shallow copy of this instance with the specified fields replaced. */
    fun copy(
        _mustNameArguments: _MustNameArguments =
            _MustNameArguments,
        actualType: skirout.editor.v1.type_catalog.TypeUse =
            this.actualType,
        payload: skirout.editor.v1.type_catalog.DataValue =
            this.payload,
    ) = skirout.editor.v1.typed_value.PortableValue(
        actualType,
        payload,
        this._unrecognizedFields,
    );

    @kotlin.Deprecated("No point in creating an exact copy of an immutable object", kotlin.ReplaceWith("this"))
    fun copy() = this;

    override fun equals(other: kotlin.Any?): kotlin.Boolean {
        return this === other || (other is skirout.editor.v1.typed_value.PortableValue && this.actualType == other.actualType && this.payload == other.payload);
    }

    override fun hashCode(): kotlin.Int {
        return kotlin.collections.listOf<kotlin.Any?>(this.actualType, this.payload).hashCode();
    }

    override fun toString(): kotlin.String {
        return build.skir.internal.toStringImpl(
            this,
            _SerializerRegistry.PortableValueSerializerImpl,
        )
    }

    /** Mutable version of [PortableValue]. */
    class Mutable internal constructor(
        _mustNameArguments: _MustNameArguments =
            _MustNameArguments,
        override var actualType: skirout.editor.v1.type_catalog.TypeUse =
            skirout.editor.v1.type_catalog.TypeUse.UNKNOWN,
        override var payload: skirout.editor.v1.type_catalog.DataValue =
            skirout.editor.v1.type_catalog.DataValue.UNKNOWN,
        internal var _unrecognizedFields: _UnrecognizedFields<skirout.editor.v1.typed_value.PortableValue>? =
            null,
    ): skirout.editor.v1.typed_value.PortableValue_OrMutable {
        /** Returns a deeply immutable copy of this instance */
        override fun toFrozen() = skirout.editor.v1.typed_value.PortableValue(
            actualType = this.actualType,
            payload = this.payload,
            _unrecognizedFields = this._unrecognizedFields,
        );
    }

    companion object {
        private val default =
            skirout.editor.v1.typed_value.PortableValue(
                skirout.editor.v1.type_catalog.TypeUse.UNKNOWN,
                skirout.editor.v1.type_catalog.DataValue.UNKNOWN,
            );

        /** Returns an instance with all fields set to their default values. */
        fun partial() = default;

        /**
         * Creates a new instance of [PortableValue].
         * Unlike the constructor, does not require all fields to be specified.
         * Missing fields will be set to their default values.
         */
        fun partial(
            _mustNameArguments: _MustNameArguments =
                _MustNameArguments,
            actualType: skirout.editor.v1.type_catalog.TypeUse =
                skirout.editor.v1.type_catalog.TypeUse.UNKNOWN,
            payload: skirout.editor.v1.type_catalog.DataValue =
                skirout.editor.v1.type_catalog.DataValue.UNKNOWN,
        ) = skirout.editor.v1.typed_value.PortableValue(
            actualType = actualType,
            payload = payload,
            _unrecognizedFields = null,
        );

        /** Serializer for [PortableValue] instances. */
        val serializer get() = _SerializerRegistry.PortableValueSerializer;

        /** Describes the [PortableValue] type. Provides runtime introspection capabilities. */
        val typeDescriptor get() = _SerializerRegistry.PortableValueSerializerImpl.typeDescriptor;
    }
}

private object _SerializerRegistry {
    val PortableValueSerializerImpl = build.skir.internal.StructSerializer(
        recordId = "editor/v1/typed_value.skir:PortableValue",
        doc = "",
        defaultInstance = skirout.editor.v1.typed_value.PortableValue.partial(),
        newMutableFn = { it?.toMutable() ?: skirout.editor.v1.typed_value.PortableValue.Mutable() },
        toFrozenFn = { it.toFrozen() },
        getUnrecognizedFields = { it._unrecognizedFields },
        setUnrecognizedFields = { m, u -> m._unrecognizedFields = u },
    );

    val PortableValueSerializer = build.skir.internal.makeSerializer(PortableValueSerializerImpl);

    init {
        PortableValueSerializerImpl.addField(
            "actual_type",
            "actualType",
            0,
            skirout.editor.v1.type_catalog.TypeUse.serializer,
            "",
            { it.actualType },
            { mut, v -> mut.actualType = v },
        );
        PortableValueSerializerImpl.addField(
            "payload",
            "payload",
            1,
            skirout.editor.v1.type_catalog.DataValue.serializer,
            "",
            { it.payload },
            { mut, v -> mut.payload = v },
        );
        PortableValueSerializerImpl.finalizeStruct();
    }
}
