API_BASE_URL=https://api.typewritermc.com
AUTH_BASE_URL=https://auth.typewritermc.com
JWT_CLIENT_ID=typewriter-services
JWT_SCOPES=openid profile entitlements
NATS_URL=nats://nats.seamlezz.com:4222
OTEL_EXPORTER_OTLP_ENDPOINT=https://otlp.seamlezz.com
OTEL_TRACES_SAMPLER=parentbased_traceidratio
OTEL_TRACES_SAMPLER_ARG=0.1
