apiVersion: surrealdb.seamlezz.com/v1alpha1
kind: SurrealDBCredential
metadata:
  name: typewriter-migration
  namespace: typewriter
spec:
  policyRef:
    name: typewriter
  level: Database
  database: typewriter
  roles:
    - OWNER
  targetSecret:
    name: surrealdb-credentials-typewriter-migration
