name: Build Typewriter Engine

on: [workflow_call]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Java 
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21
      - name: Build Engine
        uses: ./.github/actions/build-engine
      - name: Upload Plugin
        uses: actions/upload-artifact@v2
        with:
          name: Typewriter.jar
          path: engine/engine-paper/build/libs/Typewriter.jar
