on:
  push:
    branches:
      - main
      - develop
    paths:
      - "adapters/SuperiorSkyblockAdapter/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Test Adapter
        run: ./gradlew test --scan
        working-directory: ./adapters/SuperiorSkyblockAdapter
      - name: Build Adapter
        run: ./gradlew buildRelease --scan
        working-directory: ./adapters/SuperiorSkyblockAdapter
      - name: Upload Adapter
        uses: actions/upload-artifact@v2
        with:
          name: SuperiorSkyblockAdapter.jar
          path: adapters/SuperiorSkyblockAdapter/build/libs/SuperiorSkyblockAdapter.jar
